### ISSUE TITLE
App crashes whenever I try to set my PGP key

### ISSUE THREAD

**Issue by Li357** [mssun/passforios#100]
I've tried using the Download from URL and ASCII-Armor Encrypted Key ways to set my PGP key, but every time I try to set the key, the app says "Fetching PGP Key" for a bit, then crashes. I'm on an iPhone 6s with iOS 10.3.2 (14F89).

**Comment by mssun** [comment]
Could be caused by your PGP key. Can you describe the steps that the key was generated? Then, I can reproduce your issue. Thanks.

**Comment by Li357** [comment]
So I used `gpg2` to generate my GPG ID and set up `pass`, then I exported the public and private keys with `gpg2 --export -a <ID>` and `gpg2 --export-secret-keys -a <ID>`. I'm new to this so I'm not entirely sure if I'm doing this correctly.

**Comment by mssun** [comment]
Seems correct. Sometimes it will crash because of a wrong key pair. Could you double check the input keys? BTW, which version did you use?

**Comment by mssun** [comment]
If you don't mind, could generate another key pair which can crash the app for me? Please email them to `developer@passforios.mssun.me`. That will be very helpful. Thank you.

**Comment by Li357** [comment]
I'm using version 0.2.7. When I copy paste the keys from the terminal, there were line breaks, could that affect it?

**Comment by mssun** [comment]
I don't think so. May be you can try to redirect output to a file to avoid. e.g., use command `gpg2 --export -a <ID> > pub.key` and `gpg2 --export-secret-keys -a <ID> > sec.key`

**Comment by Li357** [comment]
Do you mean I should regenerate a GPG ID and then export the keys and try?

**Comment by mssun** [comment]
No, the current is fine for you. I mean you can generate a new keys for my testing (in case you have used the current keys for encryption/decryption).

Or if you don't mind to share me your current keys to me then discard then after my debugging.

The purpose of this is for your security, never share your own keys to others :)

**Comment by Li357** [comment]
How should I generate a new key for you? I'm all new to this GPG/PGP thing.

**Comment by mssun** [comment]
That's OK, let's do this step by step first.

1. Find you key ID.
`gpg2 --list-secret-keys`

2. Export keys to files.
`gpg2 --export -a <ID> > pub.key`
`gpg2 --export-secret-keys -a <ID> > sec.key`

3. Share `pub.key` and `sec.key` to your device (e.g., via Notes app), or upload to your own server.

4. Use Pass for iOS and paste GPG keys.

If the app crashes again, send `pub.key` and `sec.key` to me by email.

**Comment by Li357** [comment]
Hmm, looks like I just had some extra whitespacing. It worked like a charm through notes. Sorry about that, my fault!

**Comment by mssun** [comment]
Not at all. This is an issue for us. We should notify user but not have a crash. Since this may be caused by an upstream library, we have to coordinate with other developers to fix the issue together. Anyway, thanks for the report.
