### ISSUE TITLE
Can't clone my self-hosted repo

### ISSUE THREAD

**Issue by bartekb81** [mssun/passforios#104]
I enter the URL (in ssh://bartek@server.me/path format), get prompted for password to my SSH key like five times in a row. Then I get a very generic error.

Are there any error details I could inspect somewhere?

**Comment by mssun** [comment]
Could be a wrong key or wrong passphrase. Can you try it again?

**Comment by bartekb81** [comment]
You were right, it was the wrong key. Sorry!
