### ISSUE TITLE
Pass browser extension doesn't appear on iOS 10.2

### ISSUE THREAD

**Issue by intelfx** [mssun/passforios#106]
I'm running (jailbroken) iOS 10.2 on iPhone 5S, using Pass for iOS 0.2.7 from AppStore. After I set up the repo, opened the browser (I tried both Safari and Chrome), navigated to a page with a login form and went to enable the Pass extension, I've found that it just isn't there. I tried reopening the browser and rebooting. What did I miss?

**Comment by yishilin14** [comment]
You have to "enable" the extension. That's how app extension works. 
Please refer to our [Wiki(Use the Pass extension to fill in Safari and apps)](https://github.com/mssun/passforios/wiki#use-the-pass-extension-to-fill-in-safari-and-apps).

**Comment by intelfx** [comment]
> Open Safari/Chrome and tap the Share icon.

OK

> Swipe left on the bottom row of icons and tap More.

OK

> Turn on Pass. Move Pass to the top of the list, if you like.

At this point, Pass just isn't there.

**Comment by yishilin14** [comment]
I checked out v0.2.7 from AppStore, the extension should work for Safari (limited support, only copying password is supported). Chrome is supported in v0.2.8, it is now in TestFlight.

I am not sure whether it is because your device is jailbroken. I never tried that.

**Comment by yishilin14** [comment]
I think Pass was not there for you because we set "IPHONEOS_DEPLOYMENT_TARGET=10.3" in v0.2.7. The problem will be fixed in the upcoming v0.2.8.

**Comment by intelfx** [comment]
Great, thanks! Is there an ETA of that release?

**Comment by yishilin14** [comment]
Definitely within a week.

**Comment by yishilin14** [comment]
Hi @intelfx. You may try v0.2.8 in the AppStore and see whether this issue has been resolved.

**Comment by intelfx** [comment]
Yes, works for me. Although usability-wise it is very bad, but that's for another issue.

**Comment by yishilin14** [comment]
If you have any specific suggestions, please leave them in the issue for leaving extension suggestions. 

We are still improving the extension and adding new features. We released the extension even if they were still in its early stages, because we believe that providing limited supported is better than providing nothing.

Thank you for your understanding.
