### ISSUE TITLE
can't add passwords to local git server

### ISSUE THREAD

**Issue by ViktorEvil** [mssun/passforios#109]
not sure if being a noob or not but passwords created in the app do not sync with my local git server

app just displays the number of changes in brackets by the title.

**Comment by yishilin14** [comment]
Hi, that number is the number of local commits. You have to "Pull to Refresh" in order to sync.

**Comment by ViktorEvil** [comment]
Yes I was pulling to refresh.

I've sorted it, turns out I was trying to sync to a non bare repo that was checked out (first time using a git server and just fumbling around)

Managed to get a bare repo on my server then I was able to push into it from my laptop and phone.

Thanks
