### ISSUE TITLE
Additions display randomly 

### ISSUE THREAD

**Issue by ViktorEvil** [mssun/passforios#113]
Additions do not display in the order they are written in the raw file

**Comment by yishilin14** [comment]
Thank you for your report. The problem has been fixed in the develop branch. If you have joined our TestFlight, you may try the latest version v0.2.9(4).

**Comment by yishilin14** [comment]
Fixed in AppStore v0.2.9 today and merged in the master branch c973bb7ebbe52b11d4c462a9ef626036cf0a86f9.
