### ISSUE TITLE
Broken lock screen

### ISSUE THREAD

**Issue by asymmetric** [mssun/passforios#115]
version: 0.2.9(4)
iOS 10.3.3

Sometimes, opening the app I'm presented with this screen. I think it only happens when resuming, i.e. when I've recently opened and closed the app.

![image](https://user-images.githubusercontent.com/101816/28674111-bb242312-72e4-11e7-985b-53620141afb3.png)

**Comment by yishilin14** [comment]
Thanks. I am aware of this lock-screen related issues for a while. It occurs from time to time when the device is not locked in the portrait mode. Will try to fix and reply to you.

**Comment by mssun** [comment]
@yishilin14 Fixed in develop branch, right?

**Comment by yishilin14** [comment]
@mssun Yep

**Comment by yishilin14** [comment]
Fixed in AppStore v0.2.9 today and merged in the master branch c973bb7ebbe52b11d4c462a9ef626036cf0a86f9.
