### ISSUE TITLE
How do I set up a TFA GitHub password repository?

### ISSUE THREAD

**Issue by Li357** [mssun/passforios#116]
I previously had all my passwords stored at GitLab and all was fine, but I decided to migrate to GitHub but forgot my passphrase and had to generate a new key and re-register all my passwords. I'm now trying to set up the Git Server on passforios but when I use my repository name and password, it fails because I have TFA for GItHub on. How do I go about setting passforios up? The documentation is unclear, I'm not sure how to continue.

**Comment by mssun** [comment]
You can try to use "Personal access tokens" in GitHub.

**Comment by Li357** [comment]
Thanks! It worked!
