### ISSUE TITLE
Github push/pull problems

### ISSUE THREAD

**Issue by laats** [mssun/passforios#117]
Awesome app! However, I am having problems syncing with a private organization repo I own at github. Am using ssh protocol. Cloning works fine however.

version 0.2.8 (10)
ios 10.3.3

Thanks!

**Comment by mssun** [comment]
I don't think there's difference between normal repo and organization repo. Can you provide more information for debugging?

**Comment by laats** [comment]
The repo is owned by me and is private and has me as a collaborator. The github clone url is: git@github.com:org-name/repo-name.git

In app:
Repo url: ssh://git@github.com/org-name/repo-name.git
user name: git
Auth: ssh key

I am using deployment key with write rights. Cloning the repo works just fine. When I try to sync in app (pulling down) nothing happens. When I go to Settings->General->About Repository->Commit Logs, I get the  Error Popup:

"Error
The operation couldn't be completed. (Foundation._GenericObjCError error 0.)"

The log is also empty.

I suspect I am not supplying enough info in the url for push/pull access, but I am not sure.

Hope this helps.

Best.

**Comment by mssun** [comment]
This is wired. It seems that this issue is not related with your GitHub setup. Is there anything special with your repo? Can you send me the steps you create the repo so that I can reproduce the issue?

**Comment by yishilin14** [comment]
In the latest version of TestFlight (v0.2.9(8)), we fix some bugs about git clone.
- Before each "git clone", we now erase the previous authentication method password (both git password and ssh key passphrase). 
- In previous versions, the only way to erase the previously set SSH key passphrase was to "erase everything".

Hope this new version makes testing different authentication methods easier.

**Comment by kroesche** [comment]
Confirming I see the same issue.  I am using 0.2.8 from the app store.  Using ssh with a local git server.  I can clone the repo and it works fine.  But after that I can't sync any more.  I see the same error message as @laats when I try to view the commit log.

**Comment by yishilin14** [comment]
In TestFlight v0.2.10(13), a more detailed pull/push error message (if any) will be displayed. Hope the new error message is more elaborated and helpful.

**Comment by yishilin14** [comment]
I am closing this issue now as there have been several updates of Pass. If there is any new push/pull related issues, please open a new one.
