### ISSUE TITLE
Passphrase is not being remembered

### ISSUE THREAD

**Issue by samdmarshall** [mssun/passforios#118]
After the last testflight update (0.2.9 (2)) I've been noticing that my gpg passphrase isn't being remembered automatically. Is this a bug or am I doing something wrong?

**Comment by yishilin14** [comment]
I don't know why. I don't think we have touched related codes. 

Would you please go to Settings->General and check whether "Remember passphrase" is on? Not sure whether close it and open it again would work.

**Comment by samdmarshall** [comment]
It is enabled; i've disabled and re-enabled it in the hopes it will stick this time.

**Comment by yishilin14** [comment]
I am closing this issue for now (clearing the issue board...).
If you anything went wrong, please feel free to reopen.  :-)
