### ISSUE TITLE
Hide otpauth url form additions section

### ISSUE THREAD

**Issue by szarsti** [mssun/passforios#119]
When using password with a line:

```
otpauth://...
```

, one gets one time password in dedicated section and also otpauth url in additions section. I think that line, once discovered as valid otp, should be ignored from additions.

It exposes slight risk when someone overlooks a person mobile screen. I imagine for the same reason password is replaced with '*', until explicitly revealed.

That change will not reduce any functionality, because one can still see the full otpauth url, by using 'Show Raw' option.

**Comment by yishilin14** [comment]
You can go to Settings-> General and check "Hide OPT Fields". Then all OTP related fields will be gone in the table view (still visible in Show Raw).

**Comment by szarsti** [comment]
Oh, I have missed that. That solves my problem. Thank you!
