### ISSUE TITLE
transfer the secret key from ios

### ISSUE THREAD

**Issue by pocin** [mssun/passforios#120]
I was wondering, whether it's possible to export the secret key from your ios device back to mac (via iTunes maybe?) or it's only one way?

**Comment by yishilin14** [comment]
We used to store keys in a place where users could get it from iTunes. We later removed it for security concerns (issue #97).

Technically, we could support this in various ways (e.g., show the ASCII-Armored keys somewhere or add an export button somewhere in "Advanced"). @mssun Any suggestions?

**Comment by pocin** [comment]
It's not that I necessarily want that feature :-) I do have my private key backed up on paper, but I might come across a situation where I can't access the backup immediately so was just curious If it's possible to use the app as a sort of "backup" (given that iphone is pretty safe place for stuff with the touch ID enabled). I don't know too much about the security stuff so I don't want to make any judgements.

**Comment by jotebe** [comment]
I think exporting is a very reasonable security risk and I would only advocate for it if GPG keys were able to be generated in-app, so a user could not generate a key that would be impossible to retrieve by default.

**Comment by mssun** [comment]
@jotebe Yes, I agree with you. We have not supported generating keys in the app currently. Issue closed.
