### ISSUE TITLE
Error: Failed to fetch from remote

### ISSUE THREAD

**Issue by raxod502** [mssun/passforios#123]
I tried to sync my password repository, and got this error message after about 30 seconds. How can I find out what the error is?

About Repository and Recent Commit Log are as expected, and I can access my passwords. Last Synced is not updated due to the error.

**Comment by yishilin14** [comment]
What version are you using now? When did you sync last time? Would you please try to setup up everything again and see what happens? Hope I am not asking too much....

It is kind of weird. We haven't touched codes related to syncing for a while.

**Comment by m31271n** [comment]
The same issue, I am using `0.2.8(10)`. Error occurs when pulling down password list to sync remote at Passwords Tab.

**Comment by raxod502** [comment]
I have deleted all local data and set up from scratch. Syncing now works as expected. I will leave this issue open because @m31271n has reported it also, but feel free to close it if desired.

**Comment by m31271n** [comment]
@raxod502 Thanks. Maybe it's time to set up from scratch. ;)

**Comment by m31271n** [comment]
@raxod502 Solved.

**Comment by raxod502** [comment]
Sounds like the error happens to people who haven't synced in a while, possibly long enough that the last time was before you guys made some backwards incompatible changes. Probably nothing to worry about going forward.
