### ISSUE TITLE
Can't sync from remote.

### ISSUE THREAD

**Issue by m31271n** [mssun/passforios#124]
+ Test environments: 0.2.8 / 0.2.9
+ Steps:
   1. configure passforios to clone repo
   2. edit an existing password
   3. sync repo at Password Tab
   4. error occurs: `Error: Failed to connect remote`

Is this a missing feature? or just a bug ?

**Comment by yishilin14** [comment]
Thank you. May I know more about your setup for further investigation? 
- Your repository configuration: ssh/https, Github? authentication method?

 I have no problem doing all these. And we haven't touched related codes for a while. I am wondering whether some updates of upstream libraries broke some things...

**Comment by m31271n** [comment]
+ protocol type: ssh
+ host provider: BitBucket
+ auth method: SSH key

**Comment by yishilin14** [comment]
Thank you. Will try to reproduce during the weekend!

**Comment by yishilin14** [comment]
In TestFlight v0.2.10(13), a more detailed pull/push error message (if any) will be displayed. Hope the new error message is more elaborated and helpful.

**Comment by m31271n** [comment]
Error message shows the reason. Thank you.
