### ISSUE TITLE
Option to not cache SSH passphrase

### ISSUE THREAD

**Issue by raxod502** [mssun/passforios#125]
I'd like to have passforios not cache my SSH passphrase, and instead prompt me for it every time I sync. This would be similar to the existing behavior, which is that there's an option to not cache the GPG passphrase.

**Comment by yishilin14** [comment]
Feature available in the develop branch now (d0bad8660b2326191dee9f96c520a248e4b36266). Will be available in TestFlight soon.

**Comment by posix4e** [comment]
WFM good to close?

**Comment by raxod502** [comment]
Yes, thanks.
