### ISSUE TITLE
Can't clone repo

### ISSUE THREAD

**Issue by XenGi** [mssun/passforios#129]
Ahoi,

I tried to use passforios but I can't clone my repo. Importing my GPG keys worked and also the SSH key was imported from http.

My settings are:

  - Git Repository URL: `ssh://myuser@1.2.3.4:123/myrepo.git`
  - Username: `myuser`
  - Authentication method: `SSH Key`

Then it asks for my SSH key password but after I enter it I get this error:

`Failed to clone repository from ssh://myuser@1.2.3.4:123/myrepo.git to file:///private/...`

**Comment by mssun** [comment]
Can you clone the repo using `git` on a PC via `ssh://myuser@1.2.3.4:123/myrepo.git` address?

**Comment by XenGi** [comment]
Turns out iOS didn't like my secure SSH server. I downgraded Kex and MACs and now it works.
