### ISSUE TITLE
ObjectivePGP w/Swift compiler error: “non-modular header inside framework module”

### ISSUE THREAD

**Issue by anonopanda** [mssun/passforios#130]
Can't build the project.

This is the result after running the install commands as instructed:
<img width="1242" alt="issue" src="https://user-images.githubusercontent.com/32401481/31036375-d6967302-a520-11e7-86a8-cf39ab8bce9c.png">

**Comment by mssun** [comment]
Hi, please try to use the develop branch. Something was broken in the master branch. Will merge develop into master once our App Store submission is accepted.

**Comment by anonopanda** [comment]
Tried on the development branch and I'm getting the same issue.

**Comment by yishilin14** [comment]
You may have to do `pod install` again after switching to the dev branch. The Podfile in the dev branch is different from that in the master branch.

**Comment by mssun** [comment]
@anonopanda Can you build the project right now? If yes, I will close this issue. Thanks.
