### ISSUE TITLE
Can't add password in a folder

### ISSUE THREAD

**Issue by jamespoore** [mssun/passforios#135]
Hi,

Not sure if anyone else who uses a folder structure experiences this. When I try to add a password into a folder, it is created at the root of the pass structure. This is quite annoying as I like to have passwords nested within folders.

I have to use the cli on a computer to move it into the folder I originally desired and then pull the repo. Is this a bug or an enhancement?

Otherwise, great app and love the features you've added so far.

**Comment by mssun** [comment]
Hi, please try to use `directory/sub-directory/.../password` as the name of a password entry to create a password inside the directory.

**Comment by fruityten** [comment]
Thanks for your quick reply.

OK, thanks, that is a solution. For other users/bug fixing - it needs to be:

myfolder/test

because 

/myfolder/test makes the app hang on 'saving' and then crash for me.

Thanks though!

**Comment by yishilin14** [comment]
> When I try to add a password into a folder, it is created at the root of the pass structure.

New commit 49180d74e63fd6766ee236db67f2de0cd71d8854 to the dev branch: When users click the "add" button inside a folder (say "aaa/bbb/"), "aaa/bbb/" is displayed in the "name" field as a hint. Hopefully this improves user experiences.

> I have to use the cli on a computer to move it into the folder I originally desired and then pull the repo. Is this a bug or an enhancement?

You could "edit" the corresponding file and change its "name" from "www.mysite.com" to "myfolder/www.mysite.com" to. By doing so, your file will be moved to the correct place.

> /myfolder/test makes the app hang on 'saving' and then crash for me.
 
New commit b9ef596bfb23055fb07171c16254509c69dacb8e to the dev branch: It seems like "/" is not the root folder of the password store repository. We ask users to remove the prefix "/" now. I also added a few more checks about the filename.

**Comment by mssun** [comment]
Merged in the master branch.
