### ISSUE TITLE
Safari extension view should support `domain.tld/username` scheme too + suffix matching

### ISSUE THREAD

**Issue by intelfx** [mssun/passforios#138]
Hello,

In my pass repository layout, the entries are organized by using directory name as host and file name as login, further grouped under `web/` top-level directory. Example follows:
```
Password Store
└── web
    ├── <...>
    │   └── <...>
    ├── github.com
    │   └── intelfx
    └── <...>
        └── <...>
```

With this layout, the Safari extension becomes practically unusable. When the Safari extension view is activated, the URL host is pasted into the search bar of the view, but the view itself filters by the last level (i. e. file names) only and so no entries are ever found.

This layout is not my invention — it is suggested by the [dannyvankooten/browserpass](https://github.com/dannyvankooten/browserpass) extension, so I suggest it could be implemented here too.

Finally, it would be nice to support suffix matching, so that an entry for `github.com` would show up when you visit `www.github.com` and suchlike.

More specifically, I suggest:
1. Match the entered text in all pathname levels (or just in the last two levels)
2. Allow the pathname text (matched-against) to be a suffix of the entered text (not the inverse!)

A few screenshots to illustrate the issue:
![How the extension view is spawned](https://user-images.githubusercontent.com/1158172/31868631-7a1fe606-b7a1-11e7-9c1b-21b949843686.PNG)
![What does the extension view actually expect](https://user-images.githubusercontent.com/1158172/31868632-7a4cda58-b7a1-11e7-9824-e895e878ac31.PNG)

**Comment by yishilin14** [comment]
Thank you for your suggestion. Will work on this this week.

**Comment by mssun** [comment]
Merged in the master branch.
