### ISSUE TITLE
Missing 'git push' on my device

### ISSUE THREAD

**Issue by t0rqd** [mssun/passforios#140]
This may be a user issue, it may be a flaw. i'm not sure.

I add a password on the phone, then pull down to update, but still see a (1) at the top of the Passwords tab. Checking the repository on the other side doesn't show a new entry, so either `git push` functionality is not working, or something us configured improperly.

Wiki page shows only `git pull` supported by pulling down on the list. Is this accurate, or not, and if so, how do you work around this when out and about needing to create a new password on the fly?

**Comment by yishilin14** [comment]
1. "Pull down to update" does a `git pull` first, then a `git push` if there are some new commits. Did you see the syncing status changing from "Sync Password Store" to "Done"? Does the `git pull` work?

2. `git push` is also supported by "pulling down to sync". I just corrected the Wiki page.

**Comment by t0rqd** [comment]
No, there was a problem with the pull down and the `git pull` not grabbing things, and the `git push` was not happening, but the "Done" was presenting itself as well. Interestingly, the commit log had some newer things, but not everything.

I ended up doing a full clone again on my phone and it is now working, so this may be able to be closed at this point. 

Thanks for updating the Wiki.
