### ISSUE TITLE
Can’t swipe back from screen edge when viewing folder

### ISSUE THREAD

**Issue by ilianaw** [mssun/passforios#141]
Minor accessibility issue — when viewing a folder, I can’t swipe from the left screen edge to the right to go back to the parent folder, like I can from a password entry.

Testflight build 0.2.10 (21)

**Comment by mssun** [comment]
This is an known issue. Since folders are changed in the same view (but animate similarly with multiple views), I don't know how to implement a "swipe back" function currently. I will dig into this issue.
