### ISSUE TITLE
Failed to clone repository, Underlying error: Failed to start SSH session: Unable to exchange encryption keys

### ISSUE THREAD

**Issue by Stanpol** [mssun/passforios#142]
I reinstalled the app from the appstore today and wanted to set up everything from scratch, but cloning my repo doesn't work anymore. I get the following error: Failed to clone repository ... Underlying error: Failed to start SSH session: Unable to exchange encryption keys.

So I made sure git url is right (well it was working before), tried to change ssh keys, tried to use password authentication, tried both wifi and carrier internet and nothing helps. On the other hand, cloning repo to my computer works without problem.
Any ideas what's going on? Quick search over internet suggests that similar problem occurs because of the git clients ssh library.

pgp keys are not set yet, the app is totally clean.

**Comment by mssun** [comment]
Did you use some special key algorithm? Pass is based on ObjectivePGP, I'm not sure if it is caused by it. Could you try to generate a new key for testing?

**Comment by Stanpol** [comment]
After debugging the connection, I figured out the mismatch between the algorithms.

Pass for iOS offers the following algorithms: diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1 
And it offers following MACs: hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96,hmac-ripemd160,hmac-ripemd160@openssh.com

while default [StreisandEffect](https://github.com/StreisandEffect/streisand) server offers other stronger encryption algorithms.
