### ISSUE TITLE
Hang at 99% CPU when adding password repo.

### ISSUE THREAD

**Issue by cjwirth** [mssun/passforios#146]
Hey! Thanks for putting in the work to make this! I've been using it for a few months, but I'm having problems with the latest version.

When I put in my credentials to clone my password repo, it just hangs with 99% CPU.

The line it's stuck on is this line in `PasswordStore.swift`:

```Swift
let credentialProvider = try credential.credentialProvider(requestGitPassword: requestGitPassword)
let options = [GTRepositoryCloneOptionsCredentialProvider: credentialProvider]

// Stuck Here
storeRepository = try GTRepository.clone(from: remoteRepoURL, toWorkingDirectory: tempStoreURL, options: options, transferProgressBlock:transferProgressBlock)

if fm.fileExists(atPath: storeURL.path) {
    try fm.removeItem(at: storeURL)
}
try fm.moveItem(at: tempStoreURL, to: storeURL)
storeRepository = try GTRepository(url: storeURL)
```

The `transferProgressBlock` is never called, and the progress HUD is never updated. 

I thought it might be an issue with ObjectiveGit, but I made a sample project that clones the same repo, and it worked just fine.

Any help figuring this out would be great! 
Thanks

Update: I only opened this ticket about 10 minutes ago, but I've been playing with this for a long time. I did get it to work by changing changing the `sharedContainerURL` to be `FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!`, and even then it took a few tries. The App Store version still fails for me.

**Comment by cjwirth** [comment]
😕  Well now the App Store version is working for me too.

It only works if I _paste_ my password in... even though I _know_ the password I was manually inputting was correct.

**Comment by mssun** [comment]
That's wired. I will check it tonight.

**Comment by mssun** [comment]
Hi, how about the the latest version in the App Store (0.3.0)? I updated several dependencies.

**Comment by yishilin14** [comment]
Feel free to reopen if this issue still exists in the latest version.
