### ISSUE TITLE
Face ID

### ISSUE THREAD

**Issue by chasgames** [mssun/passforios#151]
Firstly Great project! the app is super.

I was wondering how easy it will be to implement face ID?

Apple said they would convert touch ID to FaceID integration automatically, but for some reason it's not working in pass for me.

Thanks

**Comment by yishilin14** [comment]
Will check the upstream library PasscodeLock and see why Face ID is not working now.

**Comment by chasgames** [comment]
Great thanks, on my iPhone X, when i toggle the Touch ID, it says:

"Notice

Please enable Touch ID of your phone and setup the passcode lock for Pass."

**Comment by kevinpanaro** [comment]
I’m using FaceID right now. 

Steps I did to turn it on. 

Turn on passcode lock and setup a passcode. 

Turn on Touch ID

Exit and then reopen the app.

**Comment by chasgames** [comment]
Thanks, this works 👍
