### ISSUE TITLE
[Bug] [UI] Section headers do not scroll properly

### ISSUE THREAD

**Issue by jarhill0** [mssun/passforios#152]
An image would explain best what's happening: 

![screenshot](https://user-images.githubusercontent.com/10187488/34865716-96b14e50-f72e-11e7-84fc-1cdef19144c0.jpg)

The top of the "A" header is not sticking to the bottom of the search bar as it should, and items in the scroll list (such as "amazon" here) are showing through the gap.

I'm on an iPhone SE, iOS 10.3.2, Pass for iOS version 0.2.10. 

---

Thanks to those who work on this project — it's really powerful and simple.

**Comment by mssun** [comment]
Fixed in 3e8046eb29d4c6377300b2924be29e9cf5f60b64

Will be merged to stable this week.

**Comment by jarhill0** [comment]
Thanks for the fix!
