### ISSUE TITLE
Failed to clone repository .... Underlying error: Failed to start SSH session [Especially Github repo]

### ISSUE THREAD

**Issue by snakelab** [mssun/passforios#153]
Hi folks,

i am getting this error at trying to clone a git repo via ssh-key which i had uploaded:

Failed to clone repository .... Underlying error: Failed to start SSH session: Unable to exchange encryption keys

Does anyone here have a tip for me?

thanks

hartmut

**Comment by mssun** [comment]
Which key algorithm are you using?

**Comment by snakelab** [comment]
hi, thanks for your help. My key is 2048 SHA256 RSA

**Comment by Infinisil** [comment]
Getting the same error here, same key type (which is the default for `ssh-keygen`)

I get the following error from sshd:

    Jan 27 07:49:57 paul sshd[8630]: Unable to negotiate with 178.197.226.88 port 21947:
      no matching key exchange method found. Their offer: diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1 [preauth]

**Comment by snakelab** [comment]
ping

**Comment by Infinisil** [comment]
Well I know what's the problem and it might be a serious security concern. According to [Mozilla's security guidelines](https://wiki.mozilla.org/Security/Guidelines/OpenSSH#Modern_.28OpenSSH_6.7.2B.29), these are the recommended sshd options:

```

KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
```

And everything else should be considered insecure. Apparently the ssh library used in passforios doesn't support any of those! Especially SHA1 is considered broken. My distro (NixOS) has set these options as default, that's why it didn't work.

The problem ultimately lies in the libssh2 version being too old since [the latest one supports the necessary algorithms](https://www.libssh2.org/) (libssh2 is used by libgit2 which is used by objective-git which is used to clone the repository).

@mssun I suggest you to update some versions in hoping to get a more recent libssh2

@snakelab To fix this for now, you need to have access to the git server and add the following to your sshd_config:

```
KexAlgorithms +diffie-hellman-group14-sha1
MACs +hmac-sha1
```

**Comment by mssun** [comment]
@Infinisil  Thanks. I didn't notice this cause before. I found that objective-git points to the libgit2 (libssh2 @ f1cfa55) which is **five years old**.

**Comment by snakelab** [comment]
great work. As adding this algos is not an option for me, could it be fixed in passforios?!

**Comment by awmartin** [comment]
Is there a workaround for this? My host discontinued support for some of these key exchange methods, making passforios useless as-is.

**Comment by posix4e** [comment]
Same github just broke me

**Comment by awmartin** [comment]
No doubt this: https://githubengineering.com/crypto-deprecation-notice/

**Comment by posix4e** [comment]
I just had to switch to gitlab

**Comment by jtunison** [comment]
Looks like libssh2 version got bumped in objective-git on Feb 15: https://github.com/libgit2/objective-git/commit/17112f5321d9f781f43bcc8d50662c4189fa0089

But no objective-git release since then...

**Comment by jtunison** [comment]
See also https://github.com/mssun/passforios/issues/164

**Comment by snakelab** [comment]
This issue seems to have quite an impact to the project here, so i also opened an issue at the objective-git project and got good news:

https://github.com/libgit2/objective-git/issues/641#event-1500135494

So it seems that passforios just need to update the objective-git libs and we all would be happy!!!!
Please just do it.... thanks @mssun

**Comment by mssun** [comment]
I will work on this weekend. Thanks.

**Comment by tobiastom** [comment]
Just for the record: this will most likely not add `Ed25519` support, as that is not supported by libssh2 for now: https://github.com/libssh2/libssh2/issues/39

**Comment by supermarin** [comment]
any updates on this?

**Comment by mssun** [comment]
Hi, I have updated to the latest objective-pgp (`0.10.0-beta3`) in the develop branch and release a TestFlight. Please check out and test if it is ok now. Thanks.

**Comment by mssun** [comment]
Hi all, I'm trying to close this issue today. The only thing I can do is to use the master branch of objective-git. I don't know why I cannot use it via carthage. (https://github.com/libgit2/objective-git/issues/646) Do you guys know why this could happen?

**Comment by snakelab** [comment]
Please send me a invite to testflight: h.koenig@snakelab.de

**Comment by snakelab** [comment]
Hi @mssun, it is so sad, but it is not working for me ... i got the same error at using ssh-key for my repo ... :-/

**Comment by savyajha** [comment]
Has there been any progress on this? Using pass with bad encryption is worse than not using it at all. :/

**Comment by savyajha** [comment]
Oh wow. This is going to take a while, then. No worries, and thanks for letting me know. :)

**Comment by johnmee** [comment]
Major bummer.  So if my repo is on github is there a (temporary) workaround?

eg: If I put it somewhere that is not github (my own server) and loosen the permitted algorithms, will that let me push passwords from the phone again?

**Comment by yishilin14** [comment]
A temporary workaround suggested by @raxod502 in #170 

> Temporary workaround for me is to host my repository on GitLab rather than GitHub. (Actually, I have it on both, with GitLab mirroring automatically.)

GitLab Documentation - Repository mirroring: https://docs.gitlab.com/ee/workflow/repository_mirroring.html

**Comment by snakelab** [comment]
@mssun Hi bob, why don't you try this version with a newer openssl bib:

https://github.com/tiennou/objective-git/commits/master

**Comment by mssun** [comment]
@snakelab Did you mean this: https://github.com/tiennou/objective-git/commits/update/libgit2-0.27?

It seems that supporting latest openssl lib is still work-in-progress.

**Comment by snakelab** [comment]
Well, i mean this issue:
https://github.com/libgit2/objective-git/issues/648
where tiennou mentioned the update to the new ssl lib....

**Comment by mssun** [comment]
@snakelab  Thanks. I tried to build with the master branch and got an error. I have reported to the upstream: https://github.com/libgit2/objective-git/issues/654

**Comment by mssun** [comment]
@phatblat it works. Thanks.

**Comment by snakelab** [comment]
@mssun is a new release coming??

**Comment by mssun** [comment]
@snakelab Due to an issue of objective-git, we still cannot use the latest release for now. Thanks.

**Comment by jakerobers** [comment]
Adding link for convenience. It looks like it will get merged soon: https://github.com/libgit2/objective-git/pull/645

**Comment by savyajha** [comment]
Asked for the linked PR to get merged, seeing as their holdup seems to have been fixed. Hopefully we'll get a fix to that issue that's blocking the upgrade of objective-git here.

**Comment by mssun** [comment]
Hi all, I'm releasing a test flight because of the merged PR "Update libgit2 to 0.27" (https://github.com/libgit2/objective-git/pull/645). Please help me test if everything works well. Thank you!

**Comment by raxod502** [comment]
I can now clone repositories from GitHub with the latest update. Thanks!

**Comment by savyajha** [comment]
Using it on a private server, it works with the [Mozilla OpenSSH guidelines](https://infosec.mozilla.org/guidelines/openssh). Thank you!

**Comment by snakelab** [comment]
@mssun thanks for releasing this issue - it is also working for me now!

**Comment by delegacy** [comment]
Checked that the latest test flight app can synchronize with my GitHub repo now!

**Comment by OkanEsen** [comment]
Do we have any info on when we can expect this change to be pushed to production? Is there something we can do to help?

Thank you for your hard work @mssun!

**Comment by pbnsilva** [comment]
Any ETA on app store release ?
