### ISSUE TITLE
Integration with Krypton

### ISSUE THREAD

**Issue by robcohen** [mssun/passforios#154]
Is there any chance that Pass for iOS could be integrated with [Krypton](https://github.com/kryptco/krypton-ios)? It would probably require some code addition to pass for iOS, pass, and Krypton (both phone and desktop).

If this were possible it would be pretty incredible. Anyone else think this is a good idea?

**Comment by mssun** [comment]
Using Krypton to manage SSH key? Probably, yes, but we have to solve other issues first. I guess @yishilin14  and I did not have enough time to implement this in a short time. I will leave this feature for someone who is interested.

**Comment by robcohen** [comment]
https://github.com/kryptco/krypton-ios/issues/46
