### ISSUE TITLE
Sync over HTTPS with authentication not working

### ISSUE THREAD

**Issue by hadeshimself** [mssun/passforios#157]
I'm trying to sync over HTTPs but I'm always getting 401 errors from my server due to no authentication being sent. Here's a sample Apache log from earlier today:

2804:XXX:3a01 - - [22/Jan/2018:11:36:03 -0200] "GET /git/pass.git//info/refs?service=git-upload-pack HTTP/1.1" 401 3716 "-" "git/2.0 (libgit2 0.25.1)"

The app will try to fetch this URL even before asking me for a password. After asking for the password a second time the app stays in a loop for a while (~30 seconds) and comes back to the previous screen.

I tried embedding the username in the URL (https://user@server), but that didn't work either.

**Comment by yishilin14** [comment]
Hi, sorry for the late reply. Are you able to sync now? 

---
From our Wiki: https://github.com/mssun/passforios/wiki#https-url-example

HTTPS URL example
Git repository URL: https://gitlab.com/passforios-demo/demo.git
Username: passforios-demo
Supported authentication Method: Password, SSH Keys
Remarks: https is a must

**Comment by yishilin14** [comment]
The ObjectiveGit framework gets updated a while ago, I do hope this issue is solved automatically. I am closing old issues. But feel free to reopen if the problem is still there.
