### ISSUE TITLE
App Extension not working

### ISSUE THREAD

**Issue by tillkrischer** [mssun/passforios#158]
I managed to set up the Safari Extension, but I can not seem to get the App extension to work.

When I press the 1Password button in a supported App the list comes up empty.
If I install 1Password or LastPass, those show up fine in the menu.

Is there something I am missing, to enable this feature?

**Comment by yishilin14** [comment]
My "Pass" appears in the menu in supported Apps. But the auto-filling does not work anymore.
Will try to fix in soon.

**Comment by yishilin14** [comment]
I just tested it with our latest TestFlight version 0.3.1(7), it works for me. Version 0.3.0(5) also works for me. Could you please try again?

——
In order to see Pass in the menu together with 1Password, you have to enable the Pass extension manually. Please refer to the last section of our wiki about how to do so : https://github.com/mssun/passforios/wiki

**Comment by mssun** [comment]
@yishilin14 Can we enable this function by default?

**Comment by tillkrischer** [comment]
<img src="https://media.giphy.com/media/TGq7llSTMoQAFonqB2/giphy.gif">

Still have the issue of Pass not showing up in the menu.
This is on the Testflight 0.3.1(7)

**Comment by mssun** [comment]
![1331523033572_ pic](https://user-images.githubusercontent.com/1270392/38433673-9f78233a-3980-11e8-8783-2593a4cccaa5.jpg)
![1361523033603_ pic](https://user-images.githubusercontent.com/1270392/38433681-a9bc32e6-3980-11e8-9a93-8067781a5503.jpg)

I can use it, very interesting.

**Comment by yishilin14** [comment]
@tillkrischer  Are you able to get Pass work on filling any other apps?

**Comment by tillkrischer** [comment]
@yishilin14  I also tried Overcast and Dropbox (same thing)



Something seems to be messed up with my activities menu. I have Dropbox installed, but I don't see the "Save to Dropbox" option either.

**Comment by mssun** [comment]
@tillkrischer ture. Very strange, could be a bug in iOS.

**Comment by yishilin14** [comment]
Feel free to test v0.3.7(12) in TestFlight and see whether Pass shows up as an extension. :-)

**Comment by tillkrischer** [comment]
@yishilin14 Works for me now, Thank you so much!
