### ISSUE TITLE
Unable to clone repo from Github

### ISSUE THREAD

**Issue by eligundry** [mssun/passforios#164]
Hey all, I tried starting fresh and reinstalled the app from the app store. When I attempt to clone the repo, I get the following error message: `Underlying error: credentials callback returned an invalid cred type`. This happens with both a ed25519 and plain old rsa private key.

Also, if it helps, I am on iOS 11.3 beta 3.

**Comment by jtunison** [comment]
See also https://github.com/mssun/passforios/issues/153

**Comment by yishilin14** [comment]
I am trying to move all related discussions to #153 . New updates will be posted there. So I am closing this issue now. Feel free to reopen if necessary. :-)

**Comment by edganiukov** [comment]
I have the same error: `Underlying error: credentials callback returned an invalid cred type`
Using github with https and  bot RSA 2048 or 4096 and ed25519 keys.

**Comment by jamestamplin** [comment]
For those that may benefit:

This error was thrown for me as I was trying to provide the HTTPS URL with SSH keys. 

Ensure you're using ssh://, see the wiki setup for more: https://github.com/mssun/passforios/wiki#ssh-url-example
