### ISSUE TITLE
Failed to clone repository: Failed to start SSH Session: Unable to exchange encryption keys.

### ISSUE THREAD

**Issue by shadyproject** [mssun/passforios#170]
I have pass configured to use ssh with a public key authentication and a github account.  After initial setup, when I try to clone my pass repository, I get the following message:

```
Failed to clone repository from ssh://git@github.com/shadyproject/pass-storage to file file:///private/var/mobile/Containers/Shared/AppGroup/BA8c12A9-05AB-48A0-9931-58B-B3B67E4DD/Library/password-store-temp
Underlying error: Failed to start SSH session: Unable to exchange encryption keys
```

Any ideas as to how to fix this?

**Comment by raxod502** [comment]
This started happening to me with a recent update, with no changes to my settings.

**Comment by savyajha** [comment]
This has something to do with [Issue 153](https://github.com/mssun/passforios/issues/153)

**Comment by raxod502** [comment]
Temporary workaround for me is to host my repository on GitLab rather than GitHub. (Actually, I have it on both, with GitLab mirroring automatically.)

**Comment by yishilin14** [comment]
I am trying to move all related discussions to #153 . So I am closing this issue now. :-)
