### ISSUE TITLE
Unable to clone repo

### ISSUE THREAD

**Issue by alexmironof** [mssun/passforios#171]
Fatal error: path/to/repo.git doesn’t appear to be a git repository.

Maybe my server is misconfigured? But I still can clone it with git from my PC

**Comment by mssun** [comment]
Thank you for the report. I don't know if it is related with this issue: https://github.com/mssun/passforios/issues/153, but I definitely have to solve it as soon as possible.

**Comment by alexmironof** [comment]
Thanks for the response! Also I’m using ssh connection

**Comment by mssun** [comment]
@alexmironof What key algorithm are you using?

**Comment by alexmironof** [comment]
@mssun I’m using recommended ssh generation method for github: it’s 4096 rsa

**Comment by yishilin14** [comment]
Are you cloning Github repo? If so, I would like to close this issue and move all related discussions to #153 . New updates will be posted there.

**Comment by alexmironof** [comment]
@yishilin14 No, I'm using my own dedicated server. I've got `OpenSSH _7.4p1` and `git version 2.11.0`

**Comment by alexmironof** [comment]
Closing this in prefer of https://github.com/mssun/passforios/issues/186
