### ISSUE TITLE
Comparibility with In-App Logins

### ISSUE THREAD

**Issue by hermannsblum** [mssun/passforios#172]
Many Apps allow to fill in login-credentials through password managers such as 1password. Clicking a button, this opens a share-menu-like dialog:
![GitHawk Upload by hermannsblum](https://i.imgur.com/YjbXMRE.jpg)
As this dialog lists more apps than just 1password, I suppose that it would also be possible to easily integrate passforios, as the search and fill-in should work in the same way as for safari.

**Comment by mssun** [comment]
It works for me too. You need to tap more and select Pass in the extension manually. Thanks for the report.

**Comment by oanhof** [comment]
Hi. I have the same problem. It works in safari but does not show up in other apps. It is not available to activate in the more section.

Did some research and it seems to work when changing the Info.plist of the passExtenstion to look something like this:

```
<key>NSExtension</key>
	<dict>
		<key>NSExtensionAttributes</key>
		<dict>
			<key>NSExtensionActivationRule</key>
			<string>SUBQUERY (
    extensionItems,
    $extensionItem,
    SUBQUERY (
    $extensionItem.attachments,
    $attachment,
    ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "org.appextension.find-login-action" ||
    ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.url" ||
    ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.plain-text"
    ).@count == $extensionItem.attachments.@count
    ).@count == 1</string>
			<key>NSExtensionJavaScriptPreprocessingFile</key>
			<string>passProcessor</string>
		</dict>
		<key>NSExtensionMainStoryboard</key>
		<string>MainInterface</string>
		<key>NSExtensionPointIdentifier</key>
		<string>com.apple.ui-services</string>
	</dict>
```

sources:
https://stackoverflow.com/a/38819917
https://github.com/bitwarden/mobile/blob/master/src/iOS.Extension/Info.plist

**Comment by yishilin14** [comment]
@oanhof Thank you so much! I will give it a try asap.

**Comment by hermannsblum** [comment]
Huups, sorry
And yes, I can confirm that pass did not show up in the options for apps to add, however I did not have that much insight in it, hopefully the suggestion from @oanhof fixes this.

**Comment by yishilin14** [comment]
Feel free to test v0.3.7(12) in TestFlight and see whether Pass shows up as an extension. :-) 
Related commit: a45127be41bb2c167653f74499ed4ade5b2d36b0

**Comment by oanhof** [comment]
Works for me now with the Testflight version. 👍
