### ISSUE TITLE
Progress dialog and yes-no dialog are shown on top of one another

### ISSUE THREAD

**Issue by raxod502** [mssun/passforios#173]
When cloning a repository using an SSH key which requires a passphrase, I see the following UI:

<details><summary>click to expand</summary><p>

![image](https://user-images.githubusercontent.com/6559064/38209137-3d0fcb82-3668-11e8-89ef-a10a1fbbba12.png)
</p></details>

<p>

The popup on the bottom is this:

<details><summary>click to expand</summary><p>

![image](https://user-images.githubusercontent.com/6559064/38209161-52d222e4-3668-11e8-9618-c962248f4139.png)
</p></details>

<p>

It seems to me that the question about caching the passphrase should only be shown after the repository is cloned, or perhaps before cloning starts, but not at the same time.

**Comment by yishilin14** [comment]
Oops, it has been a year. I hope 5439ad0f5b9e170ba63dafe2df5d7bfc99113423 fix this.
