### ISSUE TITLE
Pass shouldn't display the secret key in the UI

### ISSUE THREAD

**Issue by CCheCastaldo** [mssun/passforios#174]
If I enable remember pgp key passphrase then the only thing stopping someone with access to my phone is pass’s passcode lock and/or the touch id. If I turn off remember pgp key passphrase then I have added an extra layer of security - even if someone accessed the pass app, unless they knew my pgp secret key passphrase they couldn’t decode my keys. However, I noticed that even with the pgp passphrase turned off you can still see my secret key in it’s entirety by clicking on PGP key > ASCII-Armor Encrypted Key. The private key is sitting right there in the box. I would think that with the passphrase not saved in memory there should be no way to view the secret key without typing it. Or perhaps, even better, pass simply shouldn't display the secret key in the UI regardless. 

Bob, thanks for considering this.

**Comment by ttyz** [comment]
What you see is the encrypted key. You would need to decrypt it first to use it, and you would need to enter the password for that. I personally see no issue in showing the encrypted key.

**Comment by CCheCastaldo** [comment]
You are right. I forgot that armor not only converts my key from binary to ASCII but it also encrypts it. For me, my private key is encrypted with the SHA-1 of my passphrase, which is used as the key for AES-128 to encrypt my private key.

Not to be combative about this, but if some is able to see the armor encrypted version of my private key, then couldn't they use it to brute force attack my passphrase and decrypt the AES key used to armor my private key in the first place? After that, they have what they need to decrypt the private key (the salt and the IV) by just doing gpg --list-packets on my private key. Why provide someone this line of attack? It just seems like there is no reason to see the armored private key at all after it is first entered into passforios.

Forgive me in advance for any flaws in my understanding of GnuPG.

**Comment by djmoch** [comment]
I agree with the OP on this. Even granting the secret key is encrypted in its ASCII format, you’ve basically created an exfiltration channel for someone to export that key and conduct an offline attack.
