### ISSUE TITLE
New logo for Pass

### ISSUE THREAD

**Issue by ihtiht** [mssun/passforios#176]
Hi, I designed a logo for the Pass application. The main idea in this design is to demonstrate Pass's function. I hope you like it? If you like, I can give all the necessary logo files in the format and size you want.

![pass_final](https://user-images.githubusercontent.com/36369736/38783345-29698d42-4109-11e8-90b2-0ddb00224b7e.jpg)

![pass](https://user-images.githubusercontent.com/36369736/38783373-c663cea0-4109-11e8-8167-91fd40a24148.jpg)

**Comment by djmoch** [comment]
This looks great, but if I can offer my (unsolicited) opinion, I’m fond of the simplicity of the current logo. Just one guy’s opinion!

**Comment by mssun** [comment]
Amazing design! Thanks @ihtiht. I agree with @djmoch, current logo looks very minimal. I still prefer the current one. BTW, I used Sketch to draw the current logo, and the source file is also included in the code base: the `icon.sketch` file.

**Comment by mssun** [comment]
@djmoch Thanks again. I am still happy with my previous design. I'm closing this issue. Feel free to reopen if you have an updated version. Thanks.
