### ISSUE TITLE
Text-field containing password treated as regular text

### ISSUE THREAD

**Issue by david-bergstrom** [mssun/passforios#179]
The field containing the password on the screen where passwords are created/edited is treated as a regular text input field. This causes two problems:  

1. It is a security issue as a third-party keyboard can read the password and later suggest it back to the user when the user is using some other app.
2. It makes it cumbersome to manually enter a password as the keyboard might try to autocorrect the password into some similar word.

I have attached a screenshot which hopefully makes the problem clear:

![img_1400](https://user-images.githubusercontent.com/3671917/39251257-1ee29688-48a3-11e8-8c7c-a99226aaffce.PNG)

**Comment by yishilin14** [comment]
@david-bergstrom Good point!

**Comment by yishilin14** [comment]
@mssun Setting textContentType="password" doesn't solve the problem.

**Comment by yishilin14** [comment]
I Googled a bit. And I can't find an elegant solution for now.

There are two options with pros and cons.
- Set "textField.secureTextEntry = YES". 
    - Pros: Only the system keyboard is allowed.
    - Cons: The password will be masked. Can't see the password, especially the generated ones.
- Disable 3rd party keyboard in the app. 
    - Pros: Secure, of course.
    - Cons: Might be extremely inconvenient. Can't use your favorite 3rd party keyboard to enter things other than the password.

I don't know how to force the app to use the system keyboard, without setting "textField.secureTextEntry = YES" and masking the password. Any suggestions?

**Comment by savyajha** [comment]
Nothing wrong with masking the password. It's done in nearly every app which requires password input. I'd suggest using `textField.secureTextEntry = YES` and masking the password.

**Comment by mssun** [comment]
I think we can do it like 1Password:

![Image](https://i.imgur.com/Dkkttqs.jpg)

**Comment by yishilin14** [comment]
@savyajha Personally, I would like to take a look at the password before saving it. 

@mssun Looks like a good idea.

**Comment by savyajha** [comment]
@yishilin14 I'm so used to autogenerating passwords I don't even remember the last time I looked at them. XD
