### ISSUE TITLE
App crashes when decrypting

### ISSUE THREAD

**Issue by dl7tny** [mssun/passforios#181]
IOS: 11.3.1 (15E302)
Device: iPhone X and iPhone 6 Plus
Pass: 0.3.1 (15)
GPG Key: 2.048 bit DSA (fairly old)

I can browser the folder tree with all passwords but as soon as i try to decrypt one password, the app asks me for my key passphrase and then silently crashs. I can restart the app and play this game endless.

**Comment by SimplyDanny** [comment]
Does the problem only occur with specific password files or with all of them?

**Comment by mssun** [comment]
Is this related to the latest update in App Store? If so, can you try to re-import keys? Thanks.

**Comment by dl7tny** [comment]
No it existed before the last update in the app store and still exists with the current Version.

**Comment by dl7tny** [comment]
Tried to re-import the gpg key, but the app still crashes when decrypting.

**Comment by yishilin14** [comment]
Are you able to encrypt a new password file?

**Comment by dl7tny** [comment]
No. "Cannot encrypt. Missing required MPI. Invalid Key"

**Comment by yhager** [comment]
same issue here, with an ipod touch 6.

**Comment by mssun** [comment]
Seems that the Objective PGP does not support MPI for DSA: https://github.com/krzyzanowskim/ObjectivePGP/blob/develop/ObjectivePGP/Packets/PGPPublicKeyEncryptedSessionKeyPacket.m#L155

**Comment by yhager** [comment]
This could explain my issue, my key is DSA. What would you recommend I do? Change my key? wait?

**Comment by dl7tny** [comment]
The testflight version from last night (0.4.1 (1)) seems to fix the problem. I can now decrypt my passwords.

**Comment by mssun** [comment]
Ok, cool. How about @yhager ? Can I close this issue?

**Comment by yhager** [comment]
@mssun, yes! Latest version works for me too. Thanks!

**Comment by mssun** [comment]
Thanks @yhager. I'm closing this issue.
