### ISSUE TITLE
QR code scanner broken

### ISSUE THREAD

**Issue by alexdavid** [mssun/passforios#183]
The ssh key qr code scanner seems to be broken again since the latest update:

![image](https://user-images.githubusercontent.com/751581/39736543-4f3970c2-5235-11e8-87fd-ec1f956adafa.png)

**Comment by yishilin14** [comment]
Mine is working. And the "scanner output" log appears if I disable the camera permission for Pass.

Is it possible that your Pass does not have access to the camera? You could go to your system setting and enable the camera permission.

The wording here is bad. We will change it, say to "Pass does not have permission .....".

**Comment by alexdavid** [comment]
You are completely right. Not sure how that got turned off.

Thanks!
