### ISSUE TITLE
SSH key problems

### ISSUE THREAD

**Issue by khinsen** [mssun/passforios#184]
I am trying to set up passforios as documented for a self-hosted git server accessible via ssh. I installed the private key via iTunes, which seems to have worked.

When I try to clone my repository, passforious asks me for my SSH passphrase although my key does not have one. That looks suspect. When I enter an empty passphrase, the questions comes up again. After a few repetitions, I get the error message:

   Underlying error: Failed to authenticate SSH session: Waiting for USERAUTH response

On the server, the error message is:

   sshd[6284]: error: maximum authentication attempts exceeded for git from xx.xx.xx.xx port xxxxx ssh2 [preauth]

I generated another key with a passphrase, but that doesn't make a difference. After entering the passphrase  a few times, I get the same error message.

I use both the repository and the SSH key with other machines/software, so I a reasonably sure that everything else is set up correctly.

What can I do to debug this?

**Comment by khinsen** [comment]
Some more experimentation showed that it's my key that somehow caused the problem, although it's the same one I use with another iOS app (Working Copy) to access my git server. I generated a new key specifically for passforios, and with that key it works just fine.

**Comment by mssun** [comment]
What algorithm did you use to generate the ssh key?

**Comment by khinsen** [comment]
RSA2, both for the old key that doesn't work and for the new key that does. They are also both 2048 bits long. I cannot see any obvious difference between the two keys.

**Comment by mssun** [comment]
We have updated libgit2/libssh2/openssl and shipped a TestFlight 0.8.0 (41) with this update. Please help me to confirm this problem is fixed. Refer: https://github.com/mssun/passforios/issues/305#issuecomment-555885978

**Comment by khinsen** [comment]
I was too late to do the TestFlight, but I did update to the current release and test again with my key: it works. Thanks!
