### ISSUE TITLE
Add support for Elgamal keys by upgrading ObjectivePGP to 0.12.0

### ISSUE THREAD

**Issue by tsibley** [mssun/passforios#185]
See the recent release at https://github.com/krzyzanowskim/ObjectivePGP/releases/tag/0.12.0 which was spurred by [this issue](https://github.com/krzyzanowskim/ObjectivePGP/issues/12).

Upgrading the dep should fix the crash I was encountering here: https://github.com/mssun/passforios/issues/145

**Comment by mssun** [comment]
Good, I'm working on it.

**Comment by mssun** [comment]
Fixed in https://github.com/mssun/passforios/commit/868e91e99ccc3bd32cf56f997a2bb7644600fdd1.

**Comment by tsibley** [comment]
@mssun Thank you!  I look forward to the next release that contains the improvement.

**Comment by mssun** [comment]
I guess the latest AppStore release resolves this issue. I'm closing it now. Feel free to reopen if you have further questions on this. Thank you all.
