### ISSUE TITLE
Underlying error: unsupported URL protocol

### ISSUE THREAD

**Issue by apfohl** [mssun/passforios#186]
Hi,

I’ve just upgraded to v0.4.0 (4) on my iPhone and discovered an error that my Git remote URL does not seem to work anymore. I’m using the SSH variant: ssh://git@host/pass.git with an SSH key.

When I try to clone, I get an error message: Faild to clone repository from ssh://git@host/pass.git to file:///... Underlying error: unsupported URL protocol.

Maybe this has something to do with the updated dependencies? Nothing has changed at the server side, as the pass CLI is working normally.

Please let me know, if I can provide further information to help solving this bug. For now I leave the state as is (broken).

@apfohl

**Comment by intelfx** [comment]
Yeah, really nice. I attempted to re-clone the pass repo and was left without one at all.

**Comment by mssun** [comment]
Thanks for the report. I'll look into this issue, tonight.

**Comment by posix4e** [comment]
Same on gitlab

**Comment by opposablebrain** [comment]
@mssun Thanks for getting on this quickly. In the meantime, can you recommend any obvious workarounds?

**Comment by opposablebrain** [comment]
@mssun I see you commented a while back on a seemingly related issue ([objective-git2#646])(https://github.com/libgit2/objective-git/issues/646) (see OP error message). Is it possible that the release that carthage fetches failed to include libssh?

FWIW, if I force objective-git to use 0.13.0, everything works fine.

**Comment by bexelbie** [comment]
If it helps, I am seeing this on an SSH file access machine that is not a traditional git forge.  Appears to be directly related to the update on 23 May, 2018

**Comment by mssun** [comment]
Sorry for the recent release. I am releasing a new version (fallback to objective-git 0.13.0).

**Comment by opposablebrain** [comment]
Thanks, @mssun! I will donate $50 to app development if you add a few basic tests, e.g. access a test repo successfully to fetch, add, and push; over https and ssh. I mean that.

**Comment by ViktorEvil** [comment]
Same error syncing to a local git server, started after the latest update

**Comment by jamespoore** [comment]
When will the new/fixed version be available on the App Store?

Thanks

**Comment by bexelbie** [comment]
Can you revert the update on the app store for those of not using https?

**Comment by mssun** [comment]
I'm reverting to the old version. Publishing on App Store still needs some time for review. Please stay tuned. Thanks.

**Comment by mssun** [comment]
Hi all, I'm releasing a test flight because of the merged PR "Update libgit2 to 0.27" (https://github.com/libgit2/objective-git/pull/645). Please help me test if everything works well. Thank you!

**Comment by brvier** [comment]
I can test if you have testflight invite. 
Regards

**Comment by Thor77** [comment]
As noone else reported back: With the current build available from the AppStore it works just fine :+1:

**Comment by mssun** [comment]
0.5.0 is released on AppStore. I guess there is no such issue right now.

I'm closing this issue. Free fell to reopen this if you have further questions. Thank you all!
