### ISSUE TITLE
SSH clone error

### ISSUE THREAD

**Issue by migmedia** [mssun/passforios#192]
I got the following error using a keyfile: 
`...
Underlying error: Failed to authenticate SSH session: Unable to extract public key from private key file: Wrong passphrase or invalid/unrecognized private key file format`

When I use a password:
`Underlying error: callback returned unsupported credentials type`

Both operations causes a log-entry: 
`Connection closed by authenticating user XXXXXX 192.168.XX.XX port 54939 [preauth]`

So the SSH Server didn't get a valid authentication. 
How can I debug further?
Are there known problematic SSH-server config options?

**Comment by tobiastom** [comment]
I do have the same issue with the latest release. Many it’s related to #153?

**Comment by yishilin14** [comment]
This is not related to #153.

I think it is because the key algorithm / key format / git setup is not supported by Pass. We are trying to document some known issues in https://github.com/mssun/passforios/wiki/Supported-Unsupported-Key-Algorithms .

@migmedia Please take a look at that link and see whether that helps. :-)

**Comment by iamfilipc** [comment]
I have the exact same problem. Same message. I am on latest ios 10 32bit - if it helps. Do we have a solution for this please? I can't wait to use it on my iphone :)

**Comment by iamfilipc** [comment]
Resolved here #218 by wonderful @hreese.

**Comment by charlesmercadal** [comment]
I was getting the same error above when using password auth (callback returned unsupported credentials type).  I was also having no luck with key-based auth. (password box kept popping up repeatedly as per bug #243 )

I noticed in the sshd_config provided by default on my system (FreeBSD 11.2), the following was commented out:
```
#PasswordAuthentication no
```
I'm no sshd expert, but after looking at some verbose output of ssh, I'm thinking there must be a difference between keyboard-interactive and password that never occurred to me in previous usage.   I uncommented and changed to:
```
PasswordAuthentication yes
```
after restarting sshd, I was able to complete my clone using password based auth.

Maybe this will be helpful for others with the same trouble.

(My first ever post to GitHub, apologies if I've messed up the formatting in advance.)

**Comment by migmedia** [comment]
> I was getting the same error above when using password auth (callback returned unsupported credentials type). I was also having no luck with key-based auth. (password box kept popping up repeatedly as per bug #243 )
> 
> I noticed in the sshd_config provided by default on my system (FreeBSD 11.2), the following was commented out:
> 
> ```
> #PasswordAuthentication no
> ```
> 
> I'm no sshd expert, but after looking at some verbose output of ssh, I'm thinking there must be a difference between keyboard-interactive and password that never occurred to me in previous usage. I uncommented and changed to:
> 
> ```
> PasswordAuthentication yes
> ```
> 
> after restarting sshd, I was able to complete my clone using password based auth.

Indeed, in my `sshd_config` is the same setting `PasswordAuthentication no` but it's intetionally there.

I have found a work-around by installing [Gogs](https://gogs.io/).
