### ISSUE TITLE
iPhone X Crashes After Setting Up "Passcode Lock"

### ISSUE THREAD

**Issue by Recognition101** [mssun/passforios#193]
Reproduction Instructions:

1. Install passforios version 0.4.1 from the App Store on an actual (non-simulator) iPhone X (iOS 11.4)
2. Go to Settings > Passcode Lock, enable it by typing any password twice.
3. Exit to the home screen.
4. Re-open the App. Observe the app instantly crashes.
5. Try to open the app share extension. Observe the app share extension instantly crashes.

From the crash logs, I see this:

```
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: TCC, This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSFaceIDUsageDescription key with a string value explaining to the user how the app uses this data.
Triggered by Thread:  5
```

Looks like you need to add a key/value pair to your Info.plist. The simulator does not display this problem, presumably because it does not have FaceID.

**Comment by jaydisc** [comment]
Same issue with 0.4.1(1) from TestFlight on iOS 12b1.

**Comment by mssun** [comment]
The update: 0.5.0 (2) has been released in TestFlight.

**Comment by jaydisc** [comment]
Working nicely here on 12b1.

FWIW, I often find the requirement of picking yet another passcode to enable Face/TouchID in each app to be annoying. 1Blocker is an example app that lets you activate FaceID without picking a PIN.

Perhaps an option to secure the SSH or GPG passphrase(s) with FaceID would be a nicer option and avoid that need for Yet Another PIN.
