### ISSUE TITLE
iOS 12 supports third-party keychains! (Password Autofill)

### ISSUE THREAD

**Issue by adtac** [mssun/passforios#196]
https://developer.apple.com/documentation/authenticationservices?language=objc

I'm no iOS developer, but I'm so excited for this feature. In fact, I got so excited I downloaded the public beta on my main device (there are so many other nice features in this version).

I'd love to use my favourite password manager (hint: it's pass :P) natively instead of having to either use the Safari sharesheet or switch apps and copy the password over.

In any case, thank you so much for this app :)

**Comment by mssun** [comment]
Great, thanks for sharing. We will work on that.

**Comment by TheLastProject** [comment]
I've been trying this on TestFlight for a bit now, works great for me :)

**Comment by remofritzsche** [comment]
Is there already a release planned for this or can I join test flight somehow? Would be amazing! Thank you guys :)

**Comment by yishilin14** [comment]
The autofill feature has been released in January (v.0.5.1).....

Showing credentials in the QuickType bar has not been implemented though.
