### ISSUE TITLE
Option to hide alphabetic scrollbar and sections

### ISSUE THREAD

**Issue by jeffrey182** [mssun/passforios#197]
Please add option to hide the alphabetic scrollbar and alphabetic sections.

**Comment by jeffrey182** [comment]
The alphabetic sections are clutter when using folder mode with a few items in each folder.

**Comment by yishilin14** [comment]
What do you think if we show all A-Z at all times?

**Comment by jeffrey182** [comment]
I think showing A-Z at all times would be undesirable.  I see the folder view as being analogous to the pass for unix display.  It's also similar to a file manager where A-Z wouldn't be typically shown.

**Comment by jeroenleenarts** [comment]
I'd suggest a threshold. Below X items in a folder, no index. And above, show index.

With very few items the index is indeed clutter. So let's only show it above X number of items.

**Comment by mssun** [comment]
The commit (b9edcea21499881ad6de11671e940b6e8f02f437) fixes this issue. Basically, the behavior is similar with that in Apple's Contact app.
