### ISSUE TITLE
[Feature Request] default to search all

### ISSUE THREAD

**Issue by bexelbie** [mssun/passforios#198]
I use directories to organize my passwords on disk. It’d save a lot of clicks if I could default to search all, not search current.

**Comment by yishilin14** [comment]
Make sense. I would like to get opinions from you guys about this feature and see whether we should change our current default to search all. :-)

[![](https://api.gh-polls.com/poll/01CJNWKB9E9A555KHVHWV2MS1P/Default%20to%20search%20all)](https://api.gh-polls.com/poll/01CJNWKB9E9A555KHVHWV2MS1P/Default%20to%20search%20all/vote)
[![](https://api.gh-polls.com/poll/01CJNWKB9E9A555KHVHWV2MS1P/Default%20to%20search%20current)](https://api.gh-polls.com/poll/01CJNWKB9E9A555KHVHWV2MS1P/Default%20to%20search%20current/vote)

Deadline: July 29, 2018 (AoE).

**Comment by bexelbie** [comment]
Would an alternative solution be to add an option button for this in the preferences?  This way we don't have to upset the workflow of those who want folder level default?

**Comment by yishilin14** [comment]
I think we can "remember" the last choice (default/all) made by users. And use it as the default in the next search.

**Comment by yishilin14** [comment]
In Testflight v0.5.1(8).

**Comment by mssun** [comment]
A new version (0.5.1) has been published in App Store.
