### ISSUE TITLE
SSH Clone Failure

### ISSUE THREAD

**Issue by djmoch** [mssun/passforios#200]
I almost hope I'm doing something wrong and stupid, because this seems like a pretty basic thing...

I had been using [Gogs](https://gogs.io) as my Git server, but recently switched to [CGit](https://git.zx2c4.com/cgit/about), meaning that my repository URL has changed. For some reason, the new URL (not publicly accessible) causes the failure message below. The underlying error doesn't make sense to me, since I've verified _both_ that the path is a repo _and_ I can clone it using `pass git clone` on my laptop.
![18-07-21 08-51-25 0059](https://user-images.githubusercontent.com/6044662/43035824-bf05b6e0-8cc3-11e8-8e04-e9a467ed6969.png)

I'm hesitant to point the finger at Pass, because I've made stupid mistakes with the SSH clone URL's in the app before. Any ideas about what might be going on?

**Comment by OkanEsen** [comment]
Maybe this is related to #153?

**Comment by djmoch** [comment]
That doesn't seem to be the issue in my case. I can see the server accepting the SSH key (which, for the record, is RSA 4096 & SHA256). It's also showing a different underlying cause.

**Comment by djmoch** [comment]
This is odd. I was able to work around the issue by specifying the clone URL as an absolute path. (ex: `ssh://git@git.djmoch.org//srv/git/pass.git`, note the double-slash after the server name). I'll go ahead and close this, with the hope that the "paper trail" is useful in case anyone else encounters this.

**Comment by mssun** [comment]
This is a wired issue. I didn't notice that there should be a double-slash after the server name. I'll put it in the wiki.
