### ISSUE TITLE
Clone via https fails ssh is working

### ISSUE THREAD

**Issue by nylocx** [mssun/passforios#202]
I just set up a complete fresh pass repo on a gogs git server and checked it with the pass application on my desktop, everything works fine.
I then installed passforios on a fresh iPhone 6 (latest IOS 11) and tried to clone via https (https://example.com/username/passwordstore.git). It asks for my password and after I enter it nothing happens just the normal screen where I can hit clone in the upper right corner. After 3 tries pass hangs with the preparing message and its spinning wheel.

After reinstalling and trying everything I could imagine I gave up and created an ssh-key for the same server and it worked instantly.

I'm not sure why this happens as I don't get an error message, but maybe others can contribute more information.

**Comment by yishilin14** [comment]
I can clone my gitlab repo via https.
I have not tried the gogs git server. Are you able to see some related logs from the server side?

**Comment by yishilin14** [comment]
Not sure whether #200 is related.

> This is odd. I was able to work around the issue by specifying the clone URL as an absolute path. (ex: ssh://git@git.djmoch.org//srv/git/pass.git, note the double-slash after the server name). I'll go ahead and close this, with the hope that the "paper trail" is useful in case anyone else encounters this.

**Comment by nylocx** [comment]
I just got a new phone and see the same issue this time with exactly the same repo that is working fine with password auth on my old phone. I can’t clone.

From my server log I see a csrf token
2018/09/22 06:55:44 [TRACE] Session ID: 55a9bc4e84dd80ae                          
2018/09/22 06:55:44 [TRACE] CSRF token…

So maybe this it what breaks the cloning.

**Comment by mssun** [comment]
Hi @nylocx, is this still a valid problem in the latest version (TestFlight 0.8.0 (41))?
