### ISSUE TITLE
Sync problems with 2FA

### ISSUE THREAD

**Issue by lovejavaee** [mssun/passforios#206]
It's a great app, but unfortunately it can not sync with GitHub repository when your GitHub open Two Factor Authentication.

**Comment by mssun** [comment]
You can use personal access tokens:

https://blog.github.com/2013-05-16-personal-api-tokens/

**Comment by bauen1** [comment]
This doesn't work if the server is using e.g. https://github.com/google/google-authenticator-libpam .
Could this maybe be reopened ?
