### ISSUE TITLE
Support for folders

### ISSUE THREAD

**Issue by chrishawes** [mssun/passforios#21]
Pass allows the creation of passwords in folders.

For example: 
’pass insert Business/cheese-whiz-factory’

Currently the app displays all passwords in the top level.

**Comment by mssun** [comment]
In current version, the folder information will be shown under the password name in password details view. I will work on in next few release later.

**Comment by mssun** [comment]
Now support folders by several commit start from: 050a960167e830192e3457b648b7904c6edc67a7

Since internal core data is changed, note that you have to reinstall the app to erase the data.

**Comment by mssun** [comment]
I'm closing this issue. Feel free to open new issues if this function is broken.

**Comment by chrishawes** [comment]
Amazing! Many thanks :)

I've been meaning to fork your repo and work on improving the setup instructions and perhaps add some in app help documentation.

**Comment by mssun** [comment]
Thank you, that would be very helpful.
