### ISSUE TITLE
Support iTunes File Sharing

### ISSUE THREAD

**Issue by ttyz** [mssun/passforios#22]
Uploading keys using some web server is a fine option, but I think it would be much more secure to use the file sharing mechanism to get the ssh and gpg keys to the device.

**Comment by mssun** [comment]
Yes, you are right. I am considering to use other ways to share keys. Current solution is to fill in ASCII armor keys. I plan to support import by file sharing services such as DropBox.

**Comment by ttyz** [comment]
I did try to implement this feature, and it seems to be successful. I will make a PR after doing some clean up of the code.
