### ISSUE TITLE
Security concerns

### ISSUE THREAD

**Issue by stefanoco** [mssun/passforios#223]
I love this application. Before suggesting it's usage company wide, I'm a bit concerned about security: I'm pretty sure that SSH and GPG keys are stored according IOS best prectices but I can't find any hint about this in the documentation. Can we assume that keys are securely stored in the IOS enclave, so that no access to keys (and thus to encrypted cloned pass files) is possible even having physical access to the iPhone (if locked of course)?

**Comment by yishilin14** [comment]
Keys are stored in [NSUserDefaults](https://developer.apple.com/documentation/foundation/nsuserdefaults) via [radex/SwiftyUserDefaults](https://github.com/radex/SwiftyUserDefaults) ("Modern Swift API for NSUserDefaults. (Related codes: https://github.com/mssun/passforios/blob/master/passKit/Helpers/DefaultsKeys.swift)

According to Apple's document, "sandboxed app cannot access or modify the preferences for any other app." And I think normal people won't have access to files in iPhone when it is locked.

I am not a security guy, but I googled "NSUserDefaults security" a bit. It seems like keychain is more suitable for keeping the keys.

@mssun Any ideas?

**Comment by mmcdole** [comment]
@yishilin14 I agree that the Keychain seems like a more suitable place for this sensitive data.  Data stored in NSUserDefaults is stored unencrypted which for something this sensitive isn't ideal.

It should be fairly easy to write something that migrates user's keys to the keychain and removes them if they exist in NSUserDefaults.

**Comment by jmpolom** [comment]
Keychain for sure: https://developer.apple.com/documentation/security/certificate_key_and_trust_services/keys/storing_keys_in_the_keychain

**Comment by mmustapic** [comment]
From what I see in the code and when inspecting simulator files, the private key is stored in UserDefaults and in the NSDocumentDirectory folder. I think ObjectiveGPG expects to find the keys in the filesystem. In theory a non-jailbroken phone would not expose this files, but probably it is better to store the private key in the keychain.

The secure enclave cannot store keys not generated in it, so a different strategy is needed for that (generating a key in the SE and encrypting the GPG key with that?)

**Comment by ursetto** [comment]
This means GPG and SSH private keys get backed up to iCloud Backup, correct? I believe most apps only back up your secret data when you do a local encrypted backup through iTunes, either by putting them in the keychain or marking them specially (somehow).

**Comment by SimplyDanny** [comment]
I'm currently working on this one. After playing a little bit around it seems like at least PGP keys can be stored in the Keychain. Doing so actually makes the key handling much simpler as nothing needs to be moved around in the filesystem. Hope I can open a PR in a few days.

**Comment by yishilin14** [comment]
Thanks to @SimplyDanny, keys are now stored in keychain in v0.6.0. The key migration will be done automatically during the update.

**Comment by stefanoco** [comment]
Excellent 

--
  Stefano Costa
  R&D, Managing Director
  Bluewind Embedded Systems
  M. +39 335 6565749
  Twitter @stefanobluewind
  www.bluewind.it

**Comment by tobiastom** [comment]
Thank you @simplyDanny!
