### ISSUE TITLE
Allow filtering of unsynced entries

### ISSUE THREAD

**Issue by asymmetric** [mssun/passforios#238]
It would be very useful if pass allowed me to easily see exactly which entries haven't been synced yet.

Right now all I see is a small counter on the bottom left, and I have to scroll through all the entries to see which ones are unsynced.

Thanks for all your work!

**Comment by yishilin14** [comment]
One workaround: `Settings -> About Repository -> Local Commits`.

**Comment by yishilin14** [comment]
Any suggestions about how the UI should show a few unsynced entries among a long list of synced entries?

**Comment by asymmetric** [comment]
My preference would be if tapping on the lock icon would allow me to select (or switch between) all, unsynced, and synced entries.

**Comment by mssun** [comment]
This commit (a4b1f87b56d459c68c3d38a2e9de303c4eeacb45) has fixed this issue. Now you can tap the title to select all password and unsynced password.

The fix is still in TestFlight, hopefully will ship in this month.

**Comment by mssun** [comment]
Closed, 0.8.0 (41) has been published in App Store.

Feel free to reopen this or create a new one if there are more related issues.
