### ISSUE TITLE
Crash when tapping PGP botton

### ISSUE THREAD

**Issue by ttyz** [mssun/passforios#24]
After a fresh start, when I tap the "PGP Key" Button the application crashes.

Here is some info from the debug window:
```
Terminating app due to uncaught exception 'NSGenericException', reason: 'Your application has presented a UIAlertController (<UIAlertController: 0x7ff5b8f286a0>) of style UIAlertControllerStyleActionSheet. The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.'
```

I am using an iPad Air to test the application.

EDIT:
The issue is not present when application is running in the sidebar.

**Comment by mssun** [comment]
Thanks for the report. This is due to a bug in showing ActionSheet. I will work on it.

**Comment by mssun** [comment]
Resolved. Please try again. Feel free to report bugs on iPad. I don't have enough time to test it on iPad.

**Comment by ttyz** [comment]
Great! Now it is resolved. iPad is my primary device, so I will be on the look
