### ISSUE TITLE
Security issue: Autofill extension shows list of passwords underneath/before passcode screen appears

### ISSUE THREAD

**Issue by davidjb** [mssun/passforios#250]
When the autofill extension is called up (eg via Safari or similar), the extension shows the list of passwords inside the password store _before_ the Pass's passcode screen is shown.  This reveals sensitive information about the contents of the password store to an unauthenticated user.  Here's what it looks like in a screen recording:

https://imgur.com/a/NdWrX4o

Watch carefully and you'll see the password store appear and slide up first, showing the entry for Amazon, the only item that matches the URL in this case.  Then, the passcode lock UI is shown on top of the password store.  It's easiest to see in the Simulator when `Debug --> Slow Animations` is turned on, but I originally saw it happening in real-time on a physical device when the GPU/CPU was busy with other tasks, thus slowing down redrawing (password store was visible for a few seconds before the passcode then was requested).

Tested with the latest `master` (8351c16d75f930f1c22addedfaadb93303cbf470), but I've seen this happening for a while in release versions.  

I've not dug into this issue in great depth but the view is being considered to be loaded irrespective of the state of the passcode lock.  For instance, the `viewDidLoad` function (https://github.com/mssun/passforios/blob/master/passAutoFillExtension/Controllers/CredentialProviderViewController.swift#L106) and the data population is thus running at the same time that the passcode lock is being presented.

**Comment by yishilin14** [comment]
I haven't figured out a good way to present the passcode screen... Not an expert... Do you have any suggestions to fix this?

**Comment by mssun** [comment]
Hi @davidjb, I have fixed this issue in the latest beta version 0.10.0 (67). Can you help me to verify if this still an issue?

**Comment by davidjb** [comment]
Thanks @mssun - I’ve updated to the latest beta version as described by the issue is still there. It’s easiest to see on the iOS simulator with animations slowed down (sliding effect) or with accessibility options Reduce Motion and Prefer Cross-fade Transitions enabled where you can see the pass entries visible before the login screen appears.

**Comment by mssun** [comment]
I see. Let me figure out the root cause. Thanks.

**Comment by mssun** [comment]
Hi @davidjb, should be fixed in the latest TestFlight.

**Comment by davidjb** [comment]
Thank you @mssun - tested and looks great. Well done!
