### ISSUE TITLE
[Feature Request] Detect and Display Notes

### ISSUE THREAD

**Issue by bexelbie** [mssun/passforios#255]
Right now passforios assumes everything is a key/value or line oriented value.  I put notes in my password files, where needed and have an entire folder of nothing but notes.

It would be nice to have a way to indicate to pass that some data should be displayed as a block or always in raw mode.

I wonder if something like a signature marker (two dashes on a line) would work.  For example:

Password with note:
```
<password>
<userid>
<key>:<value>
--
Note text
   indented text
```
Note only file:
```
<blank line>
<blank line>
--
Note text
here
and here
   and indented here
```

Obviously this is not a breaking feature need :D

**Comment by SimplyDanny** [comment]
Pass for iOS supports the YAML operators `|` and `>`. You can write

    1234
    login: someone
    note: |
      a note
      using
      multiple lines

for example. The note block will be displayed in one text field retaining the line breaks. With `>` instead of `|` line breaks will be ignored.

**Comment by yishilin14** [comment]
What about showing the "raw" mode by default when there is no key:value pair?

**Comment by bexelbie** [comment]
While what @SimplyDanny describes works, I think implementing what @yishilin14 proposes is also good.  This way it becomes less cumbersome for notes-only entries but the other syntax works well for mixed use.

**Comment by mssun** [comment]
> What about showing the "raw" mode by default when there is no key:value pair?

We cannot distinguish these two since our syntax assumes the first line is a password.

```
one line password
```

```
note line one
note line two
```

I think @SimplyDanny's solution is good enough (more general), but we need to introduce the syntax in wiki or other places.

**Comment by yishilin14** [comment]
> I think @SimplyDanny's solution is good enough (more general), but we need to introduce the syntax in wiki or other places.

Done: https://github.com/mssun/passforios/wiki#data-organization

**Comment by SimplyDanny** [comment]
@yishilin14: Your written documentation is not fully correct. Actually, the app only supports the YAML syntax `|-` and `|>` for multiline fields (respecting and not respecting new lines). Full YAML support is not implemented anymore. It has been removed in [ddddfda](https://github.com/mssun/passforios/commit/ddddfda9317ab652a20b7e88057785d04f259b25).

**Comment by yishilin14** [comment]
Oops. I updated the wiki again.
