### ISSUE TITLE
SSH keys with no access to iTunes

### ISSUE THREAD

**Issue by wpcarro** [mssun/passforios#257]
Is there a documented way of adding SSH keys in `passforios` if you don't have access to iTunes? Maybe something similar to the way we can add PGP keys...

I store my `.password-store` in a private repository that I believe needs SSH access. All of my other attempts to access it have failed. Eager to set this up and remove my 1Password dependency.

**Comment by yishilin14** [comment]
https://github.com/mssun/passforios/wiki

**Comment by wpcarro** [comment]
The only mention I see in the wiki for ASCII-armor imports relates to PGP keys.

I do see the:

```shell
$ cat ~/.ssh/id_rsa
```

In the app. Thanks for pointing that out. I may update the wiki once I get this working. I'm having a lot of trouble getting SSH working.

**Comment by yishilin14** [comment]
Just update the wiki page: https://github.com/mssun/passforios/wiki#importing-ascii-armor-encrypted-ssh-key. :-)
