### ISSUE TITLE
Error when performing TLS handshake with bitbucket.org

### ISSUE THREAD

**Issue by danielmoore-info** [mssun/passforios#269]
I'm trying to configure passforios to use a repository on bitbucket.org. When I enter the repository information into the app and press 'clone' the app waits for a while and produces the following error:

![60829258_2304477579807690_4408900610720530432_n](https://user-images.githubusercontent.com/28050016/58150830-30b60d80-7cab-11e9-98af-f180d6735040.jpg)

This does not occur when I use github.com. I would like to use bitbucket.org as they have free private repositories. I don't like the idea of someone browsing the repository on github.com to determine which services I have an account with.

Phone info:
iPhone XR
iOS 12.2

**Comment by danielmoore-info** [comment]
Closing issue. Just learned that GitHub private repositories are now free _facepalm_.

**Comment by yishilin14** [comment]
Could be related to https://bitbucket.org/blog/deprecating-tlsv1-tlsv1-1-2018-12-01.

Anyway, happy to see you got it work!
