### ISSUE TITLE
Issues of 0.6.0(20) in TestFlight

### ISSUE THREAD

**Issue by yishilin14** [mssun/passforios#274]
Here are some known issues in 0.6.0(2). We are working on it. If you found more issues, please report below. Thank you so much.

- [ ] Cannot edit an entry. Nothing happens or the app crashes.

**Comment by yishilin14** [comment]
@ZortacDev Do you have any ideas about how to decrypt entires encrypted in ASCII-Armored?

**Comment by ZortacDev** [comment]
My decrypt function should decrypt both armored and binary formats correctly and detect the format automatically. I'll look into it in a couple hours and check that that works correctly.On Jun 15, 2019 08:52, Yishi Lin <notifications@github.com> wrote:@ZortacDev Do you have any ideas about how to decrypt entires encrypted in ASCII-Armored?

**Comment by yishilin14** [comment]
@ZortacDev Emmm, strange enough, I cannot reproduce now.

**Comment by yishilin14** [comment]
My bad, I am using at the wrong version.
