### ISSUE TITLE
Possible macOS port?

### ISSUE THREAD

**Issue by tylernguyen** [mssun/passforios#276]
Hi,

Your app is currently the best pass client, thank you for your work! Since there's no native Mac pass client as of now. Are there any possible plans to port passforios to macOS now that Apple has a transition layer for the process?

**Comment by savyajha** [comment]
Fwiw, [gopass](https://www.gopass.pw/) works really well for me. Maybe you'd want to have a look at it? You can also setup Alfred workflows if you want autofilling everywhere in the OS.

**Comment by tylernguyen** [comment]
> Fwiw, [gopass](https://www.gopass.pw/) works really well for me. Maybe you'd want to have a look at it? You can also setup Alfred workflows if you want autofilling everywhere in the OS.

Hi, thank you for your suggestions. However, I'm looking for something with a GUI and a UX that's more friendly. And I think that a port to macOS would just be perfect.

**Comment by savyajha** [comment]
If you just want it in your browser, then you can use [Browserpass](https://github.com/browserpass) for either Chrome or Firefox.

**Comment by mssun** [comment]
@tylernguyen I did watch the latest WWDC. It's possible to port to macOS, but I think the UI should be re-design. In the meantime, you can use gopass and browserpass.

Overall, I think we can give it a try.

**Comment by tylernguyen** [comment]
> 
> 
> @tylernguyen I did watch the latest WWDC. It's possible to port to macOS, but I think the UI should be re-design. In the meantime, you can use gopass and browserpass.
> 
> Overall, I think we can give it a try.

Hi @mssun, thank you for your reply. I do think the current UI is sufficient, however. Unless there's a specific problem that you worry about. Also, I've tried browserpass will stick with it for now but I still think a ported pass will serve me better.

**Comment by mssun** [comment]
HI @tylernguyen, come back to this. I'm thinking about creating a native macOS app but not porting our existing iOS app. Though some code can be shared, but UI need to be redesigned.

**Comment by tylernguyen** [comment]
> HI @tylernguyen, come back to this. I'm thinking about creating a native macOS app but not porting our existing iOS app. Though some code can be shared, but UI need to be redesigned.

A native app would be even better! The only reason I suggested porting is that I thought it might save some time now and more development time in the future. But if you feel that a native app is doable, that would be the best!

**Comment by mnussbaum** [comment]
It's not a full interface but if you need a quick native pop-up HUD interface for selecting passwords on mac OS I've made one at https://github.com/mnussbaum/PassHUD

**Comment by cip123** [comment]
I would also love to have a Mac version of this app. 

The command-line is excellent for quick reading a pass, but a GUI version would be best if you want to edit/delete your passwords more easily. I plan to start working on this, heavily copying some of your code. 

It would be cool if some of the shared functionality would be separated into libraries to be imported into any project.

**Comment by willkramer** [comment]
> I would also love to have a Mac version of this app. 

Given the convergence with iOS apps and M1 Macs it might make sense to test out how the app runs natively in macOS first. My primary computer is an Intel-based Mac so I can't test it myself easily but in theory it should work.

My thought process is that for future enhancements and simplicity it would be easier to have one code base that covers iOS and macOS.

**Comment by SimplyDanny** [comment]
I can confirm that it runs pretty good on M1 Macs. It works like the iOS app, except that the UI is not very Mac-like and in parts not intuitive. That said, it can be used, but some work is required until it can be listed as "Verified for macOS" in the App Store.

**Comment by irvin** [comment]
pass for iOS work nicely before 0.12 but start to crash on open after 0.13

**Comment by irvin** [comment]
the testflight version from https://github.com/mssun/passforios/issues/609#issuecomment-1465308416 seems to fixed ipad and on macOS together.

**Comment by yangm97** [comment]
@tylernguyen why was this closed? I thought the success stories from Apple Silicon users could entitle a build for intel macs? 

I'm not aware of any other project supporting safari given apple has limited its extension support for those bundled with signed apps.
