### ISSUE TITLE
Allow gpg keys export

### ISSUE THREAD

**Issue by DirectorX** [mssun/passforios#277]
Allow gpg keys export in case of lossing access to the main machine, the user should be able to recover this situation using keys that stored in the app.

**Comment by pteasima** [comment]
+1

Asking for a friend... :D

**Comment by rnkn** [comment]
-1

Please don't add a security hole like this. Private PGP keys should be locked in the deepest dungeon.

**Comment by DirectorX** [comment]
‏So we should not allow secret keys without a passphrase in the first place

**Comment by rnkn** [comment]
That is really not related to adding an export feature?
Also what do you mean "we"?

**Comment by DirectorX** [comment]
Ok then

And the “we” thing... Suppose I have a split personality.

**Comment by yishilin14** [comment]
I agree with @SimplyDanny. Won't add the export feature back.
