### ISSUE TITLE
Search content as well as name

### ISSUE THREAD

**Issue by muellerj** [mssun/passforios#280]
Currently, the search field only seems to match on the names of items. It would be nice if it could also match on certain fields of the content (not the password) such as the `url`. 

This would make the experience inside the browser a lot smoother for items that are not called exactly like the url which they belong to. 

Thanks for all the great work.

**Comment by mssun** [comment]
Thanks for the feedback. We do not support search in the content because the content only decrypted when you want to use it. Under this model, only the password names  (file names) are plaintext in the app's perspective. That is to say, we don't want to index the (decrypted) content for searching.

**Comment by muellerj** [comment]
Thanks for the explanation, that makes sense. Would it maybe be possible to match the filename more liberally against the search string. 

For example: Search string is `manage.mailbox.org` (pre-filled from the url of the website). Name of the item I would like to match is `Mailbox (Jonas)`. 

I don’t know what algorithm is currently employed, but maybe the name of the item could be split on white space and then each part matched against the search string?

**Comment by yishilin14** [comment]
The current search algorithm is probably too simple. It returns entries whose names contain the search string. (https://github.com/mssun/passforios/blob/cc493cb490de848e67a4d2ca742860b538bd37d1/pass/Controllers/PasswordsViewController.swift#L494-L497) 

Does anyone know a more mature search algorithm? I'd be happy to improve the search experience.

**Comment by muellerj** [comment]
I guess this could go as complicated as one would want it to - some fuzzy search algorithms I like are https://github.com/garybernhardt/selecta and https://github.com/lotabout/skim.

For starters and without needing a huge implementation, it would be sufficient I guess to improve the search experience when the search field is pre-filled from calling the App from a website. In this case (if the search string looks like a URL), I would only match on the domain name (e.g. `"manage.mailbox.org" -> "mailbox"`.

What do you think?

I'm not experienced in Swift, but if you want I could get some traction and put together a pull request.

**Comment by yishilin14** [comment]
>  In this case (if the search string looks like a URL), I would only match on the domain name (e.g. "manage.mailbox.org" -> "mailbox".

This sounds great and easy to implement. I'll do it!

**Comment by muellerj** [comment]
Awesome, thank you!

**Comment by muellerj** [comment]
Reminder for me: This looks like it could point in the right direction: https://stackoverflow.com/questions/6162522/get-the-domain-part-of-an-url-string

**Comment by yishilin14** [comment]
Searching "manage.mailbox.org" could find an entry like "Mailbox (xxx)" now.

Related commit: 6bf47163667596482abfaa72edad9c6249aded87

Test cases: https://github.com/mssun/passforios/blob/6bf47163667596482abfaa72edad9c6249aded87/passKitTests/Models/PasswordTableEntryTest.swift

**Comment by muellerj** [comment]
Confirmed! Thanks a lot for implementing that 👍
