### ISSUE TITLE
PGP Key ID is not shown in Setting

### ISSUE THREAD

**Issue by mssun** [mssun/passforios#287]
Originally, we show PGP Key ID in the Setting view in the side of PGP row. I found that our gopenpgp wrapper returns an empty string. @ZortacDev , could you help me to check this issue? Thanks.

![Simulator Screen Shot - iPhone Xs Max - 2019-07-17 at 23 48 22](https://user-images.githubusercontent.com/1270392/61435523-7da21300-a8ed-11e9-8297-4d9be2fabb8f.png)

**Comment by ZortacDev** [comment]
Yeah I noticed this too. This is an issue of GopenPGP as the FirstKeyID field of the KeyRing struct is always empty. There is an easy workaround however by accessing the Key directly. I'll be submitting a PR for a fix later today.
