### ISSUE TITLE
Error cannot import the key

### ISSUE THREAD

**Issue by urbanslug** [mssun/passforios#290]
I have an RSA 4096 gpg key that used to work but suddenly stopped a few days ago. So I removed it and tried to readd it to pass via scanning a QR code and via iTunes file sharing. 

Both methods give me the error "Error: cannot the import key"
What could have changed? I think there was a recent update to pass?

iOS version 12.3.1
Pass version 0.6.0 (30)

**Comment by kraem** [comment]
I experienced the same thing.

I redid everything and made sure to export them ascii armored. Was able to import the key successfully.
`gpg2 *-a* --export $ID > pub.gpg`
`gpg2 *-a* --export-secret-keys $ID > priv.gpg` 

Also; Are you sure you're not using subkeys? Seems to be a bug related to that (https://github.com/mssun/passforios/issues/285)

**Comment by urbanslug** [comment]
I **am** using subkeys. 
Thanks for pointing me to https://github.com/mssun/passforios/issues/285, that's the problem I'm having. 
It all  makes sense now because my keys just suddenly stopped working. I tried to I re-import and even uninstalled and reinstalled pass for iOS.

**Comment by sitya** [comment]
Same here. It has worked fine for ages, then suddenly stopped to work and I cannot make it work again. I am also using subkeys, but with this key it worked, nothing changed. I use:
iOS version 12.3.1
Pass version 0.6.0 (30)

**Comment by osneven** [comment]
Yes I also have the same issue. Is there a way to download an older version of the app until it works again?

**Comment by mdenushev** [comment]
Same error on `iOS 12.3.1` and `Pass 0.6.0 (30)`. If I can help you by testing in Testflight just let me know.

**Comment by sitya** [comment]
0.7 fixed for me, thanks!

**Comment by urbanslug** [comment]
In my case I can import the subkeys but I can't decrypt any of the passwords.
I keep running into "Cannot show password // Cannot decrypt password [Cancel | Try Again]"

I've explained it also in https://github.com/mssun/passforios/issues/286#issuecomment-517831026

**Comment by urbanslug** [comment]
Sorry, the subkeys work in 0.7.0(15)

I was probably making an error by exporting my subkeys with `--export-secret-keys ` instead of `--export-secret-subkeys`. 
This issue is OK to close now if everyone feels that it's been resolved.
