### ISSUE TITLE
Pass for iOS does not work on AWS CodeCommit

### ISSUE THREAD

**Issue by mssun** [mssun/passforios#294]
> I try to store my passwords with pass on CodeCommit. On Fedora it works including MFA but I did not figure it out how to manage it on iOS. SSH is currently not an option, so we are using https.

This issue is reported via email.

**Comment by iliana** [comment]
I use CodeCommit for my repository and it works fine; I'm using [the "HTTPS Git Credentials" mode](https://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-gc.html#setting-up-gc-iam).

**Comment by mssun** [comment]
@iliana, thanks for providing the solution. I'm closing this issue.
