### ISSUE TITLE
Do not forget pgp passphrase on decryption error

### ISSUE THREAD

**Issue by Peter4825** [mssun/passforios#296]
Sometimes things go wrong, and the decryption for a certain password entry might fail because it is corrupt for example.  Or, because an entry has been encrypted  for another gpg key.

Whenever the decryption of any entry fails, passforios deliberately forgets the passphrase of the gpg key, assuming that it is a password error and not something else.  This is logical, if the password is invalid, then you need to be able to input it again.  However, it happens too often for me that the password is not the issue, but something else like the file not being encrypted for this gpg key, or just a corrupt file. I have a very long passphrase, and I've had to enter it many times now, while it never was the password that was the problem.

Can you make sure that passforios does not forget the passphrase for the gpg key when a generic error occurs?  Either by hinting on decryption error that one needs to go to a menu to reset it, or by verifying that it really really is a password error and not something else?

**Comment by mssun** [comment]
Thanks @Peter4825, I understand the annoyance. To make it more convenient, I think we should distinguish different error types and give different cleanup functions.

**Comment by yishilin14** [comment]
In version later than 0.8.0(14), pgp passphrase will not be cleaned up due to failed decryption.
