### ISSUE TITLE
Quck-start guide on wiki needs a bit of cleanup

### ISSUE THREAD

**Issue by rayx** [mssun/passforios#298]
There are a few typos in the `Setting up password repository` section in `Quick-start guide for Pass for iOS`, which make it rather confusing to first time user. 

1) In `HTTPS URL example` section:

        Supported authentication Method: Password, SSH Keys

    I think `SSH Keys` should be removed.

2) In `Using SSH keys uploaded via iTunes file sharing` section:

        Then, click "Settings->PGP Key->iTunes File Sharing" to import your keys.

    `PGP key` is typo. Should be `SSH key`.

In addition, it seems to me that `Using SSH keys uploaded via iTunes file sharing` section should be moved under `Importing ASCII-armor encrypted SSH key` section because it's one way to upload SSH keys (the latest version of pass supports other options which are not mentioned in the wiki)

**Comment by yishilin14** [comment]
Thank you. Updated: https://github.com/mssun/passforios/wiki
