### ISSUE TITLE
multiline field syntax in wiki is incorrect

### ISSUE THREAD

**Issue by rayx** [mssun/passforios#300]
The [wiki](https://github.com/mssun/passforios/wiki#yaml-support) suggests to use "|-" and "|>". They don't work with the app because it uses its own parser for multiline string support. BTW, I doubt if "|>" is even a valid YAML syntax, I think the author meant ">-".

The correct syntax should be "|" and ">". See [this](https://github.com/mssun/passforios/blob/master/passKit/Parser/Parser.swift#L39) and [this](https://github.com/mssun/passforios/blob/master/passKit/Parser/Constants.swift#L38).

**Comment by rayx** [comment]
I'd also suggest changing the section title to something like `YAML-like multiline field support` or just `multiline field support` because the current title is a bit misleading.

**Comment by yishilin14** [comment]
Thank you. Updated: https://github.com/mssun/passforios/wiki#yaml-like-multiline-field-support.
