### ISSUE TITLE
App doesnt forget the PGP key passphrase

### ISSUE THREAD

**Issue by adelsz** [mssun/passforios#303]
I believe there is a critical bug that can be reproduced on version 0.7.0 as follows:
1. Have the "Remember PGP Key Passphrase" toggle turned off.
2. Open some saved password and enter a correct PGP passphrase
3. Try opening another password, enter an incorrect PGP passphrase
4. **Current result:** you get access to the second password even though you entered an invalid passphrase.
**Expected:** you are denied access to passwords.

**Comment by SimplyDanny** [comment]
The bug is already fixed with #302.

**Comment by mssun** [comment]
Fix has been merged. Thanks for your report.
