### ISSUE TITLE
iOS 13-dark theme?

### ISSUE THREAD

**Issue by nielsk** [mssun/passforios#306]
Any chance to get a dark theme for iOS 13? Most is dark now on my device except the glaring white of Pass :)

**Comment by nielsk** [comment]
There is a blog post which describes apparently what to do:
https://schiavo.me/2019/implementing-dark-mode/

**Comment by mssun** [comment]
Yes! Looks very easy to implement this.

**Comment by nielsk** [comment]
It looks good but when dark mode is enabled the screen where you have to enter the password for pass itself (unlockable with Face ID) is white with a black password field.

**Comment by nielsk** [comment]
Here is a screenshot: https://drive.google.com/file/d/1g133WSP81pPRd_ku44Ks0Ya1jOj50qV3/view?usp=drivesdk

I would have expected a dark screen like the rest of the app

**Comment by mssun** [comment]
I think there is a new PR about this https://github.com/mssun/passforios/pull/311. I did push the build into TestFlight. Will do it then.

**Comment by nielsk** [comment]
That was fast 👍

**Comment by mssun** [comment]
Closed, 0.8.0 (41) has been published in App Store.

Feel free to reopen this or create a new one if there are more related issues.
