### ISSUE TITLE
Build fails on Xcode 11

### ISSUE THREAD

**Issue by sdekoning0** [mssun/passforios#312]
After cloning the repo and running `carthage update && carthage bootstrap --platform iOS && ./gopenpgp_build.sh && open pass.xcodeproj` Xcode fails to build because of 'Target Integrity' errors, related to cocoapods? Is there any way to resolve these issues?

<img width="282" alt="Screenshot 2019-09-25 at 13 28 53" src="https://user-images.githubusercontent.com/43604043/65597002-6c821c00-df98-11e9-8806-3835f1fe2033.png">

**Comment by yishilin14** [comment]
README.md is outdated. I will update it tonight.

You also have to `pod install`. See https://github.com/mssun/passforios/blob/master/.travis.yml for more details about building.

**Comment by sdekoning0** [comment]
Thanks, I managed to build using the travis yaml example.
