### ISSUE TITLE
Security issue: opening entries without a passphrase

### ISSUE THREAD

**Issue by vedran6** [mssun/passforios#321]
It appears that under certain conditions it is possible to view password entries without entering the repository key passphrase.

Reproduction steps:

1. Use a passphrase-protected PGP key
2. Open a password entry and get prompted for the key passphrase
3. Enter the passphrase correctly, press OK and view the password entry
4. Go back to the main directory tree
5. Open another password entry and get prompted for the key passphrase
6. Do not enter the passphrase or enter it incorrectly, press OK

Upon the completion of step 6, the selected entry will be displayed despite the fact that the passphrase was entered incorrectly. The amount of time elapsed between steps 4 and 5 does not appear to matter.

It appears that once the repository key passphrase is entered, it is cached somewhere until the app is force-closed and it is possible to open additional entries without subsequent authorization. If this is an intended behavior, subsequent queries should not prompt for the passphrase. If it is not intended, it is a security issue. Either way, passphrase caching should most likely be a configuration option.

**Comment by yishilin14** [comment]
Thank you for your report.
I think this issue is introduced by some of my recent commit..... I will fix it by this weekend.

**Comment by SimplyDanny** [comment]
@vedran6 are you sure this happens also in the most recent version of Pass? The same behavior was described in #303 some time ago and is now actually assumed to be fixed. At least, I cannot reproduce it again in the Simulator.

**Comment by vedran6** [comment]
@SimplyDanny yes. The issue occurs in version 0.7.0 (15) on iOS 13.

**Comment by SimplyDanny** [comment]
The issue has been fixed in 0.8.0. Would be perfect if you could verify it in the current beta version.

**Comment by mssun** [comment]
Closed, 0.8.0 (41) has been published in App Store.

Feel free to reopen this or create a new one if there are more related issues.

**Comment by vedran6** [comment]
I confirm that the issue is resolved in 0.8.0.
