### ISSUE TITLE
About gpg keys

### ISSUE THREAD

**Issue by jvillasante** [mssun/passforios#325]
So, I don't know where to ask this question.
I'm new to IOS, coming from android.

Is there a way to import only your public gpg key and use your yubikey?
I mean, if you have to actually import your private key to an iphone device, what's the point? right?
That's how I do it on android.

Thanks in advance!

**Comment by SimplyDanny** [comment]
Support for Yubikeys is not yet implemented, see #42.

**Comment by jvillasante** [comment]
Ok, thanks for the heads up. I'm closing this. Sorry for asking questions here!
