### ISSUE TITLE
Cannot run on device

### ISSUE THREAD

**Issue by sanderdekoning** [mssun/passforios#335]
I am getting the following crash when trying to run on device:

2019-11-25 10:08:42.254415+0100 pass[20697:4298035] [User Defaults] Couldn't read values in CFPrefsPlistSource<0x283702500> (Domain: [$group.bundle.identifier], User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null), Contents Need Refresh: Yes): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file
passforios/passKit/Models/PasswordStore.swift, line 58

Is there anything I can do to get this running again? I cannot access my passwords on my device now.

**Comment by mssun** [comment]
Hi, did you compile the app by yourself?

**Comment by sdekoning0** [comment]
Hi, yes I did. I cloned the master branch and following the build instructions from the Wiki page. I also deleted the prior version I had installed on device to ensure that it's not an upgrade path issue.

**Comment by mssun** [comment]
It seems that the app cannot get the Bundle with provided identifier.

https://github.com/mssun/passforios/blob/e83a2f941ee3db3805e78d122105897ecfaed2ad/passKit/Models/PasswordStore.swift#L58

https://github.com/mssun/passforios/blob/f69f8bb86721181ee0eac42868457c3409fbe8e3/passKit/Helpers/Globals.swift#L13-L15

Did you change the bundle identifier?

**Comment by sdekoning0** [comment]
Indeed, yes I changed the bundle identifier as instructed in the wiki.
![Screenshot 2019-11-25 at 20 27 50](https://user-images.githubusercontent.com/43604043/69571291-0e86aa80-0fc2-11ea-9774-6a913821abc9.png)
![Screenshot 2019-11-25 at 20 28 37](https://user-images.githubusercontent.com/43604043/69571340-29f1b580-0fc2-11ea-951a-9b5c1c05fb7a.png)

**Comment by mssun** [comment]
HI @sdekoning0, if you want to change the bundle identifier, you need to change for all targets. Please tell me if that works for you. Thanks.

**Comment by yishilin14** [comment]
Providing a script to do this automatically would be a great idea.

**Comment by sdekoning0** [comment]
I did; I only didn't change the bundle identifier for `passKit` framework target. It turns out this was the culprit. Now I can run it on device. It would be a good idea to add this to the wiki, in addition to changing the bundle identifier for pass project and pass target.

Indeed a script, perhaps in GoLang, could make these steps less error-prone

**Comment by mssun** [comment]
I updated the wiki and added one line script to replace all names. (https://github.com/mssun/passforios/wiki/Building-Pass-for-iOS#run-on-real-devices). I'm closing this issue.
