### ISSUE TITLE
SSH clone URL malformed ":"

### ISSUE THREAD

**Issue by sdekoning0** [mssun/passforios#336]
Whenever a ssh://git@gitlab.com:xxxx/xxxx.git is provided, the ":" causes a malformed URL error. However, at least GitLab uses the ":" format. Changing the ":" to "/" resolves the error, however it is not clear why this does not work, and the error does not state any illegal characters were used.

**Comment by mssun** [comment]
Finally, I understand the git related protocol. According to the document [1]:

> Git supports transferring data in packfiles over the ssh://, git://, http:// and
> file:// transports.

"ssh://", "http://" and "file://" are three most popular supported protocols, and their URLs should be like these:
  * `ssh://user@example.com:port/repo.git`: regular ssh URL
  * `user@example.com:/path/to/repo.git`: scp like URL, note that **no scheme prefix in the URL**
  * `http://example.com:port:/path/to/repo.git`: http URL
  * `https://example.com:port:/path/to/repo.git`: https URL

Our current implementation has some issue. I'm updating them right now.

- [1] https://github.com/git/git/blob/master/Documentation/technical/pack-protocol.txt

**Comment by sdekoning0** [comment]
Great, awesome!
