### ISSUE TITLE
Missing pull button

### ISSUE THREAD

**Issue by kellerkind** [mssun/passforios#343]
I am using pass since 2 years to manage my credentials windows (qtpass) and linux systems (original `pass`) and now I am able to use it also on iphone with your app.

The initial setup works (using iFunBox instead of iTunes for sharing the required files). I am currently struggling that I can not explicitly pull the remote repository when changes are done from my other systems.

There is no `pull` or `push` button in the app. 

I am using `iOS 12.4.4` on `iPhone 5s`.

**Comment by yishilin14** [comment]
In the "Passwords" tab, you could scroll down to sync.

**Comment by yishilin14** [comment]
Please feel free to re-open if necessary.
