### ISSUE TITLE
May be rejected by UIFileSharingEnabled key set to true

### ISSUE THREAD

**Issue by mssun** [mssun/passforios#36]
I got this information from:
http://stackoverflow.com/questions/10767517/rejected-by-uifilesharingenabled-key-set-to-true

I think it would be better to keep keys in Documents directory and repository in another private directory.

**Comment by mssun** [comment]
This is related to #22.

**Comment by ttyz** [comment]
Yes, I was thinking of it already. Also a short explanation for the user on how they can upload keys using iTunes may be nice somewhere.

**Comment by mssun** [comment]
Right. When you mentioned iTunes file sharing in the first time, I even didn’t realise this function is a way to upload files.

**Comment by mssun** [comment]
I briefly mention to uploading keys through iTunes in the Wiki page. https://github.com/mssun/passforios/wiki

I think it could be better to have some explanation about this function in the app. Currently the "Use uploaded keys" option is not easy to understand.

**Comment by mssun** [comment]
I'm closing this issue. Will consider providing better explanation in UI.
