### ISSUE TITLE
Failed to fetch from remote -- Underlying Error: callback returned unsupported credentials type

### ISSUE THREAD

**Issue by ktleary** [mssun/passforios#363]
Pass for ios was working with a self-hosted repo shared with the linux client. The Linux side is still working but ios suddenly started returning 

`"Failed to fetch from remote -- Underlying Error: callback returned unsupported credentials type"`

I looked around other issues (123, 192, 186)  and found similar errors, but resolutions such as restarting sshd haven't worked.

The problem started when ios Pass started asking for a github password, although I set it up to use keys.

Any suggestions on how to resolve (and avoid the error in the future)?

Follow-up: Somehow the option to use github password instead of ssh had been flipped in the settings - not something I recall doing since everything was working fine for months. Will close this.

**Comment by norsebladetug** [comment]
Your follow up actually helped me with the same issue, thanks.  :)
