### ISSUE TITLE
possible to add multiple gpg pub keys

### ISSUE THREAD

**Issue by dbgeek** [mssun/passforios#369]
**Feature request**

It would be nice to be able to add multiple public GPG keys. I´m using multiple keys in my repo. So if Adding a new password  I would like to encrypt it with multiple keys.

I have a shared setup where each one has its own key. 

Now if I add a password on my iPhone I have to push it and download it to my laptop and re-encrypt with everyone's keys. It would be awesome to do that directly in the iPhone.

**Comment by simlay** [comment]
Pretty sure this is a dup of #52.

**Comment by dbgeek** [comment]
Did not see that it already existed an issue. Thanks will close this.
