### ISSUE TITLE
'Corrupt Key'-- GPG 4096 vs 2048 byte issue?

### ISSUE THREAD

**Issue by lyterk** [mssun/passforios#372]
I've tried to import a key that's worked on Android and all of my Linux machines. It doesn't work, and throws [this error here](https://github.com/mssun/passforios/blob/master/passKitTests/Crypto/PGPAgentTest.swift#L94) (I'm not super familiar with Swift (or Apple in general for that matter), but I'm assuming that you can use the logic in your unit tests in your actual application logic)

My key has 4096 bytes, exported with ASCII armor. I've also tried using [this](https://github.com/yishilin14/asc-key-to-qr-code-gif) on my ascii-armored private/public key and importing them w/ the QR code format-- it recognizes the format, but throws the same error.

I've tried it with [this key here](https://github.com/mssun/passforios/issues/258), to see if it was my key specifically, or my version of the app (which I thought was unlikely, it seems pretty well-tested). That key worked ok.

So, what I'm thinking is, in that [test file](https://github.com/mssun/passforios/blob/master/passKitTests/Crypto/PGPAgentTest.swift#L94) you specify that you're expecting a 2048 byte key (again, not familiar w/ Swift, but I think that's just a naming convention-- I'm not sure where the actual instantiation/declaration happens). My key doesn't fit that format and fails as corrupt. So I'm thinking it might be possible to somewhere just add the different byte sizes that RSA keys can take.

I don't think I went out of my way to create this key with extra security, so 4096 might've been the default on the machine I was using at the time. When I tested creating a new key with gpg v2.2.12, it went to 3072. So your users might be seeing more of this error.

**Comment by mssun** [comment]
@lyterk, thanks for reporting this issue. RSA 4096 should also work, and I have added to the test cases.

How do you generate and export the key? Can you give me an example so that I can debug it.

**Comment by mssun** [comment]
I have added the test for RSA4096 and RSA4096 subkey here https://github.com/mssun/passforios/blob/master/passKitTests/Testbase/TestPGPKeys.swift#L33.

```
gpg --list-keys 787EAE1A5FA3E749AA34CC6AA0645EBED862027E
pub   rsa4096 2020-04-11 [SC]
      787EAE1A5FA3E749AA34CC6AA0645EBED862027E
uid           [ultimate] passforios <developer@passforios.mssun.me>
sub   rsa4096 2020-04-11 [E]
```

**Comment by lyterk** [comment]
Thanks for adding that test, much appreciated.

I went back through my shell history, looks like I said `gpg --full-generate-key`, and the output it gives you is `RSA keys may be between 1024 and 4096 bits long.
What keysize do you want? (3072)`, so I must've picked 4096. So not quite as default as I'd originally thought.

I'll get TestFlight set up on my iPad to verify the new commit works-- feel free to close this issue. I'll reopen if I still have issues.

**Comment by mssun** [comment]
Good, thanks.
