### ISSUE TITLE
0.10.0 (18) update broke gpg decryption

### ISSUE THREAD

**Issue by ismail** [mssun/passforios#376]
After the update it asked me for my GPG password again (it was saved before) and no matter what I enter, it fails to decrypt the key. I made sure the entered password is indeed correct.

**Comment by mssun** [comment]
Can you re import the pgp key? There are some breaking changes.

**Comment by ismail** [comment]
> Can you re import the pgp key? There are some breaking changes.

Just tried but it results in the same error.

**Comment by adadnc** [comment]
I'm facing the same problem. Even after reinstallation and reimporting my keys

**Comment by aristocrates** [comment]
This sounds like similar to https://github.com/mssun/passforios/issues/377 ("prompted with password Passphrase for a key that I do not have the on the phone") - I am experiencing the same problem (the key id in the popup is one which I definitely don't have the private key for on my phone).

I have not yet attempted to reimport my public keys and private key.

**Comment by mssun** [comment]
This is wired. I tested the multi key setup with password store like this: https://github.com/mssun/passforios-password-store. Anything different for yours?

If possible, could you guys first "Settings -> Erase All Password Store Data" and then setup again with the latest testflight (Version 0.10.0 (20))?

Also, please share with me how do you import the key (copy/paste, file, itunes, or URL).

If you can create a test password store for me, that will be very great!

**Comment by hakusaro** [comment]
@mssun `0.10.0 (20)`, a non-clean/upgrade install I ran has `1894E3BA` as the last line in `.gpg-id`. This is not available on the device (or anywhere, in my case, because that pgp key was generated in a yubikey). I could follow the erase process but doing so would result in a situation where I can't help test the upgrade. The selected PGP key in settings is `1E42781E`, so I would expect the app to only try to decrypt based on this key.

The key was imported from iTunes, I think. It says "Load From File" as the selected option.

**Comment by mssun** [comment]
@hakusaro You mentioned that `1894E3BA` is in the `.gpg-id` file but you are  using a different key (`1E42781E`) for encryption/decryption?

**Comment by hakusaro** [comment]
Yeah, sorry. This is gonna get semi-complicated.

_Probably worth noting: For users who need this to work now, you can always roll back to previous builds in TestFlight by selecting previous builds and picking a working version. Pass for iOS will work as usual at that point._

I'm using gopass multi recipients like as described in #338.
1. There are 3 keys that can decrypt any of the items in the password store. All 3 key fingerprints are in `.gpg-id` line by line.
2. Pass for iOS takes the last fingerprint (the last line of the file) and assumes it has the last private key in that file.
3. Assumption 2 is invalid.
4. If I re-order the file it prompts for the right passphrase, but sadly, don't have that passphrase anymore. My trust model involves transferring the passphrase to a mobile device once, and at that point its saved in Pass for iOS and lost. So I can't test further at this point without re-generating a new key and rekeying, which would take a significant amount of time.

I would be more than happy to provide you a test store if I could but sadly it would take a lot of time and I'm going to bed soon. If you can wait a couple days I can probably get you a full reproduction scenario.

<img width="682" alt="Screen Shot 0002-04-14 at 21 02 56" src="https://user-images.githubusercontent.com/532647/79297611-7ebf9b00-7e93-11ea-9704-348dbf5527e6.png">

Sample of `gopass new` in my case:

<img width="682" alt="Screen Shot 0002-04-14 at 21 09 16" src="https://user-images.githubusercontent.com/532647/79297895-613f0100-7e94-11ea-97f6-e98553158735.png">

I'm not sure whether or not it was your intent to support `gopass` users in this state, but the previous builds just did by default.

**Comment by mssun** [comment]
Oh, now I understand the reason. This is a little different than I expected. I thought there's only one ID in `.gpg-id` file, which is the case of #147.

I'll try to figure out how to support gopass's multi recipients.

**Comment by hakusaro** [comment]
@mssun if it makes you feel any better you already had it working in the previous version, but we just couldn't encrypt new items or changes. 💚

**Comment by ismail** [comment]
> This is wired. I tested the multi key setup with password store like this: https://github.com/mssun/passforios-password-store. Anything different for yours?
> 
> If possible, could you guys first "Settings -> Erase All Password Store Data" and then setup again with the latest testflight (Version 0.10.0 (20))?

I could but then what will the users upgrading to the stable release will do?

> Also, please share with me how do you import the key (copy/paste, file, itunes, or URL).

I used copy/paste ( Tried QR first but pass said imported keys were invalid.)

**Comment by mssun** [comment]
Sure, I’ll implement migration logic these days. Thanks!

**Comment by hakusaro** [comment]
@ismail this is only in TestFlight for now

**Comment by mssun** [comment]
For others who have the similar issue, but details are different with @hakusaro, please let me know. Thanks!

**Comment by ismail** [comment]
> @ismail this is only in TestFlight for now

True, but we need to make sure existing stuff works. If we all restart from scratch then who will test the upgrade path? :)

**Comment by hakusaro** [comment]
@ismail me :)

**Comment by ismail** [comment]
> @ismail me :)

Always good to have a backup plan ;)

**Comment by ismail** [comment]
Well, deleted all data, imported ssh key/gpg key, cloned the repo and still the same error.

**Comment by mayo** [comment]
I get prompted with the right key (the key shown in the dialog is the last 8 characters of the key, so harder to look for it), but the passphrase is not accepted. (I know I'm putting in the right passphrase).

The potential issue here may be that I'm using "!" at the end of the keys in .gpg-id to force specific use of keys, and PassForiOS might be misinterpreting the ! as part of the key itself?

My `.gpg-id`:
```
97F7C85D4DBF4151!
BA2B1758E747301B!
2A948A0FDED36E5C!
```

**Comment by mayo** [comment]
@mssun I have a slightly different setup, as I use sub keys.

I get prompted with the right key (the key shown in the dialog is the last 8 characters of the key -- `ED36E5C!` -- in this case, so harder to look for it), but the passphrase is not accepted.

The potential issue here may be that I'm using `!` at the end of the keys in .gpg-id to use sub-keys, and PassForiOS might be misinterpreting the `!` as part of the key itself?

My `.gpg-id`:
```
97F7C85D4DBF4151!
BA2B1758E747301B!
2A948A0FDED36E5C!
```

I've tried re-importing my key using the file method, but with no luck

**Comment by mssun** [comment]
Thanks @mayo. Very helpful. Actually, I didn't know that you can add `!` in the end of key id to use sub keys. This is supported by `pass` command line right? Is there any documentation describing this usage? Basically, I want to collect all different usages of `.gpg-id` file.

**Comment by mayo** [comment]
@mssun The command line `pass` supports the `!`, as it's a gnupg/gpg concept and pass just executes gpg.

I can't find a more extensive description in gpg docs, but the ! makes use of the sub key explicitly, so the root/parent key is not required/used. You can see this mentioned in the gpg man page, for eg. in the "How To Specify a User ID" section:

> When using gpg an exclamation mark (!) may be appended to force using the specified primary or secondary key and not to try and calculate which  primary  or  secondary key to use.

**Comment by muellerj** [comment]
If it helps, I can confirm that 0.10.0 (21) breaks decryption for me. My setup is as simple as it gets (just one key).

**Comment by mssun** [comment]
@muellerj Thank you. What's in your `.gpg-id` file? Does it match the key ID used fr encryption? I'm trying to collect all cases and will solve it this weekend.

**Comment by muellerj** [comment]
Yes, my `.gpg-id` file just references the key, that I`m using:

``` sh
$ cat .gpg-id
tiggers@tiggercloud.net
```

Hope this helps!

**Comment by mssun** [comment]
Yes, very helpful. Thank, will fix it.

**Comment by nielsk** [comment]
I am on (20), same problem.
I ascii-armored my public and private key, downloaded the files to my iPhone (put them on my qnap, downloaded the files from there, saved them to 'Files on my iPhone'). Problem persists.

**Comment by nielsk** [comment]
And tbh I have no idea what the .gpg-id-file is. I have exported only the key I use for pass and imported it to Pass for iOS.

**Comment by ismail** [comment]
Now with the (22) update problem changed for me. When trying to decrypt, I get:

"PGP private key (0x381FA1D72D72DA97) not found."

I click "Select Key" and I see "2D72DA97" note that this is the suffix from the allegedly missing key. And as soon as I select this key, everything works. But this whole dialog and select happens each time I try to see a password.

**Comment by mssun** [comment]
To give you an update, the latest TestFlight (0.10.0 (22)) provides a mitigation of this issue by implemeting a fail-safe mechanism if key is not found. Still, this is not perfect by any means, and a lot of things can be improved for the multi key support. This mitigation is to make sure the current TF version won't break encryption/decryption.

**Comment by ismail** [comment]
> To give you an update, the latest TestFlight (0.10.0 (22)) provides a mitigation of this issue by implemeting a fail-safe mechanism if key is not found. Still, this is not perfect by any means, and a lot of things can be improved for the multi key support. This mitigation is to make sure the current TF version won't break encryption/decryption.

See my comment, just posted before you :)

**Comment by mssun** [comment]
Thanks @ismail. Your comment is very helpful!

**Comment by ismail** [comment]
Note that I use "keyid-format 0xlong" in gpg.conf hence the longer keyid.

**Comment by mssun** [comment]
Yes, the next step is to handle different formats of `.gpg-id`.

**Comment by muellerj** [comment]
0.10.0 (22) fixes my problem. I can now (after selecting the key and re-entering the passphrase) decrypt my passwords. 

Thanks for the fix!

**Comment by nielsk** [comment]
Yes. For me it works now, too. Thanks!

**Comment by nielsk** [comment]
No. It fixes it only partially. For every item I try to decrypt it tells me that it cannot find the key and I have to select the key each time. Oh and I have only one key. 
And when I try to use it in a browser via the “Password”-Interface it tells me that it cannot find the key but doesn’t let me select a key.

**Comment by nielsk** [comment]
(24) fixes all the problems for me :)

**Comment by hakusaro** [comment]
On `0.10.0 (24)` I'm still prompted for the passphrase I don't have anymore. If I just need to rekey, please let me know -- but downgrading still works so I've downgraded again for day to day use.

**Comment by muellerj** [comment]
I am also re-prompted for the passphrase on 0.10.0 (24)..

**Comment by ismail** [comment]
> I am also re-prompted for the passphrase on 0.10.0 (24)..

What happens if you enter the passphrase?

**Comment by muellerj** [comment]
Decryption works fine. I just wanted to remark, that the passphrase was not ported across the update.

**Comment by nylocx** [comment]
I'm not sure where the app gets the public keys from if multiple id's are in .gpg-id. Should I concatenate my private key with the mentioned public keys and than set this as my PGP-Key?

**Comment by hakusaro** [comment]
@nylocx in gopass land, the public keys are stored in the password store so that it can read them and encrypt passwords for them.

**Comment by nylocx** [comment]
Thanks, I know that gopass does that, but I wasn’t sure if pass for iOS knows about the directory. https://github.com/mssun/passforios/issues/338#issuecomment-617056524

**Comment by mssun** [comment]
> I'm not sure where the app gets the public keys from if multiple id's are in .gpg-id. Should I concatenate my private key with the mentioned public keys and than set this as my PGP-Key?

To use multiple keys, you can combine keys (public/private separately) in to one file and import in the app.

> Thanks, I know that gopass does that, but I wasn’t sure if pass for iOS knows about the directory. [#338 (comment)](https://github.com/mssun/passforios/issues/338#issuecomment-617056524)

Right now, Pass for iOS does not support to import keys from the directory you metnioned.

**Comment by ismail** [comment]
This was fixed, closing.
