### ISSUE TITLE
Secure note storage

### ISSUE THREAD

**Issue by paulmillr** [mssun/passforios#378]
I suggest:

1. To mark files that have `Note` in their names or files from `Notes` directory to have special treatment.
2. For consistency with `pass`, a note is structured like ordinary password file. With one key difference: everything after the first line (after `password` line) is treated as Markdown and is displayed with nice font similar to the iOS Bear.app

<img width="261" alt="Screen Shot 2020-04-14 at 2 30 04 PM" src="https://user-images.githubusercontent.com/574696/79220329-7435df00-7e5c-11ea-9af6-04faea84e45d.png">

**Comment by yishilin14** [comment]
"To mark files that have Note in their names or files from Notes directory to have special treatment."

If this is not how everyone uses Pass, this may cause side effects...

**Comment by paulmillr** [comment]
We could add a setting for that, of course.

**Comment by KizzyCode** [comment]
A quick idea: how about using something like
```
-----BEGIN MARKDOWN NOTE-----
```
in the first line to indicate that the file contains a markdown  note. 

This has a few advantages IMHO:
 1. It does not rely on a custom file/folder name scheme
 2. If you see the plaintext (e.g. using the `pass` command line tool) you know immediately what’s going on
 3. It shouldn’t break any existing implementation 
 4. Annotations like this are pretty standard in the GPG context, so it’s more likely to become a quasi-standard among GUI-Apps
