### ISSUE TITLE
Beta and AppStore-versions with different names/ids for parallel installation

### ISSUE THREAD

**Issue by nielsk** [mssun/passforios#379]
Since I rely on Pass, the current breakage of the beta leads me to not be able to use it anymore. It would be great if we could have both versions installed in parallel. Then we could still test if the beta is broken for us, but still be able to access our passwords with the working AppStore-version.
Is that possible and does not add to much overhead?

**Comment by mssun** [comment]
Yes, it is possible. Let me figure out how to make this workflow work.

**Comment by nylocx** [comment]
Yay, finally a workaround for having two pass stores ;).
But I like the idea too of having different Versions, even so the beta is working for me after readding my SSH key.

**Comment by mssun** [comment]
I have created a Pass Beta app in AppStore for TestFlight only. It is still under review. Hopefully, it will be available these days. I plan to import all tests from the original app (Pass) to this new one (Pass Beta).

**Comment by mssun** [comment]
We are using Pass Beta (https://testflight.apple.com/join/whK4zUFG) for TestFlight. Thanks for the suggestion!
