### ISSUE TITLE
PGP key Expiration date change

### ISSUE THREAD

**Issue by eric-stanley** [mssun/passforios#380]
Once the PGP key is expired, I am extending the expiration date to another 2y. Now, if I update the PGP keys in the app, will my keys (data in github) will still be decrypted successfully? or is there other ways to do it?

**Comment by SimplyDanny** [comment]
If you mean your password files with “data in github“, updating the key in the app (and everywhere else you use it) is sufficient.

**Comment by eric-stanley** [comment]
Thank you. That clarifies my doubt
