### ISSUE TITLE
Darck mode bug: white bar on animation

### ISSUE THREAD

**Issue by jean-io** [mssun/passforios#385]
Hi 👋 

When I change pane on my iPhone X, I get this weird animation bug: white bars between two panes.
It happens on taping an entry or a folder. Or when I go back in app.

Any ideas on a fix?

![image](https://user-images.githubusercontent.com/4070933/81684262-198da400-9457-11ea-915a-83fb30d979ce.gif)

_By the way, thank for this great app! 🍺_

**Comment by SimplyDanny** [comment]
This should have been fixed within #367. In a recent beta version you won’t notice it anymore.

**Comment by jean-io** [comment]
Nice to ear👌
When can we expect an update in the App Store?

**Comment by SimplyDanny** [comment]
This is something I cannot answer, unfortunately.

**Comment by jean-io** [comment]
@mssun is it possible for you to update? Thank 🍺

**Comment by mssun** [comment]
Should be fixed in the App Store release. Closed.
