### ISSUE TITLE
Suggestions about setting password repository

### ISSUE THREAD

**Issue by yishilin14** [mssun/passforios#39]
1. **Always add a "cancel" option in the "Please fill in the password of your Git account" dialog.** The reason for seeing this dialog is probably "wrong repository url" or "wrong/missing username". It does not make sense if we have to try the wrong password for several times before being able to double check the git repo url or username.
2. **Before asking the password, check and make sure that both the "git repo url" field and the "username" field are non-empty.** Currently, I am able to hit "Save" without both url and username.
3. **Do no go back to the "Settings" page before git clone successes."** Currently, If something went wrong, users would have to open "Password Repository" again in order to edit/check the repo url or username.
4. **Help users save the time of manually entering "https://" in the git repo url field.** I guess everyone has to enter "https://" anyway, right?
3. **Make suggestions for the username.** It is possible to make suggestions about the "username"? For example, if the git repo url looks like "https://github.com/helloworld/xxxxx*", the corresponding username is probably "helloworld".

**Comment by mssun** [comment]
Thank you so much! All sound legit improvements. Can you put them in seperate issues? Then I can solve them one by one.

**Comment by yishilin14** [comment]
Will separate issues next time [facepalm].

**Comment by mssun** [comment]
- [x] show cancel button by default: 44f148c7ea1bdf6da6ddc4e25bb8b79c4b2cee78
- [ ] check fields before save
- [ ] clone repository in the Password Repository store view but not the main setting view
- [ ] improvements of user experience on typing URL
- [ ] make suggestions for the username

**Comment by mssun** [comment]
Closing.

Moved to my Trello TODO list.
