### ISSUE TITLE
Cannot show password: PGP public key may be expired or incompatible with the private key

### ISSUE THREAD

**Issue by n2ygk** [mssun/passforios#391]
I'm getting this error both with pass 0.9.0 and 0.10.0 under Testflight.

I've made a brand-new keypair with a very simple passphrase and tested it with `pass`:
```
x$ gpg -k passwordstore
pub   rsa2048 2020-06-12 [SC] [expires: 2022-06-12]
      9FD5612DB477B2E98AAD6CDE5EC7817FA441DD52
uid           [ultimate] Alan Crosswell (passwordstore) <alan@crosswell.us>
sub   rsa2048 2020-06-12 [E] [expires: 2022-06-12]

x$ pass 
Password Store
└── fios-router
x$ pass fios-router  # gpg passphrase popup happens
xxxxx
name: foo
x$ ps ax | grep gpg
65852   ??  Ss     0:06.59 gpg-agent --homedir /Users/ac45/.gnupg --use-standard-socket --daemon
80170 s001  S+     0:00.00 grep gpg
x$ kill 65852
x$ gpg -d ~/.password-store/fios-router.gpg  # gpg passphrase popup happens
gpg: encrypted with 2048-bit RSA key, ID 0991C0ABEDAE6E55, created 2020-06-12
      "Alan Crosswell (passwordstore) <alan@crosswell.us>"
xxxxx
name: foo
x$ gpg --export-secret-keys -a 9FD5612DB477B2E98AAD6CDE5EC7817FA441DD52 >priv
x$ gpg --export -a 9FD5612DB477B2E98AAD6CDE5EC7817FA441DD52 >pub
x$ http-server .
Starting up http-server, serving .
Available on:
  http://127.0.0.1:8080
  http://192.168.1.10:8080
Hit CTRL-C to stop the server
[2020-06-12T16:37:23.621Z] "GET /pub" "pass/24 CFNetwork/1125.2 Darwin/19.4.0"
(node:80087) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
[2020-06-12T16:37:23.652Z] "GET /priv" "pass/24 CFNetwork/1125.2 Darwin/19.4.0"
```

Screenshots:
![IMG_2461](https://user-images.githubusercontent.com/4356471/84526079-b20f8200-acaa-11ea-8624-69f793cfcb1c.png)

![IMG_2463](https://user-images.githubusercontent.com/4356471/84526078-b20f8200-acaa-11ea-8540-8afa28f8cee1.png)

Is there a way to turn on debug logging?

**Comment by n2ygk** [comment]
What's really got me flummoxed is that I can't find this error in the source code:
```
passforios$ grep -nr 'PGP public key may be expired or incompatible with the private key' .
./pass/en.lproj/Localizable.strings:137:"KeyExpiredOrIncompatibleError."    = "PGP public key may be expired or incompatible with the private key.";
passforios$ grep -nr  KeyExpiredOrIncompatibleError  .
./pass/de.lproj/Localizable.strings:137:"KeyExpiredOrIncompatibleError."    = "Der öffentliche PGP-Schlüssel ist eventuell abgelaufen oder inkompatibel mit dem privaten Schlüssel.";
./pass/en.lproj/Localizable.strings:137:"KeyExpiredOrIncompatibleError."    = "PGP public key may be expired or incompatible with the private key.";
```

**Comment by n2ygk** [comment]
pass version is v1.7.3

**Comment by SimplyDanny** [comment]
> What's really got me flummoxed is that I can't find this error in the source code:
> 
> ```
> passforios$ grep -nr 'PGP public key may be expired or incompatible with the private key' .
> ./pass/en.lproj/Localizable.strings:137:"KeyExpiredOrIncompatibleError."    = "PGP public key may be expired or incompatible with the private key.";
> passforios$ grep -nr  KeyExpiredOrIncompatibleError  .
> ./pass/de.lproj/Localizable.strings:137:"KeyExpiredOrIncompatibleError."    = "Der öffentliche PGP-Schlüssel ist eventuell abgelaufen oder inkompatibel mit dem privaten Schlüssel.";
> ./pass/en.lproj/Localizable.strings:137:"KeyExpiredOrIncompatibleError."    = "PGP public key may be expired or incompatible with the private key.";
> ```

At least I can help you with this point. The error message comes from the enum [here](https://github.com/mssun/passforios/blob/68381eb784d1cad176f02b050a15f2239854e99e/passKit/Helpers/AppError.swift#L21). If it is asked for the `errorDescription` it appends `"Error."` to its name to create a key for the localized strings files. That's why you cannot find the key as a whole in the code.

**Comment by n2ygk** [comment]
After a while of messing around, it appears that my key imports didn't work right when using node http-server.
```
$ npm info http-server

http-server@0.12.3 | MIT | deps: 10 | versions: 40
```
I ended up emailing the ascii-armored keys to myself and then pasting them and it works.

I expect it's because of a default Content-type inferred from lack of file extensions:
`application/x-mspublisher` vs. `text/plain`
```
y$ wget http://127.0.0.1:8080/pub
--2020-06-14 10:35:23--  http://127.0.0.1:8080/pub
Connecting to 127.0.0.1:8080... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1826 (1.8K) [application/x-mspublisher]
Saving to: ‘pub.1’

pub.1                        100%[==============================================>]   1.78K  --.-KB/s    in 0s      

2020-06-14 10:35:23 (249 MB/s) - ‘pub.1’ saved [1826/1826]

y$ wget http://127.0.0.1:8080/pub.txt
--2020-06-14 10:35:51--  http://127.0.0.1:8080/pub.txt
Connecting to 127.0.0.1:8080... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1826 (1.8K) [text/plain]
Saving to: ‘pub.txt’

pub.txt                      100%[==============================================>]   1.78K  --.-KB/s    in 0s      

2020-06-14 10:35:51 (249 MB/s) - ‘pub.txt’ saved [1826/1826]
```
