### ISSUE TITLE
Continually prompt for password

### ISSUE THREAD

**Issue by yishilin14** [mssun/passforios#40]
How to reproduce?

1. Settings - About - Erase All Password Store Data
2. Settings - Password Repository - Add a correct git repository url and a non-empty wrong username, hit "Save" and provide whatever password.

Then, Pass continually prompts for the password (not being able to "cancel" at all).

**Comment by mssun** [comment]
I reproduce your issue. After providing wrong username/password combination for three times, the alert window will have an cancel button. Can you try to reproduce your issue again towards the latest master branch? I'm not sure if my recent code refactoring fix this bug silently.

**Comment by mssun** [comment]
BTW, I have revised to show cancel button by default in commit: 44f148c7ea1bdf6da6ddc4e25bb8b79c4b2cee78

**Comment by yishilin14** [comment]
Showing the cancel button by default naturally fixes the bug.

**Comment by mssun** [comment]
Thanks for your responsive feedback. I am closing this issue.
