### ISSUE TITLE
Crash on reading password. Broken without changing settings.

### ISSUE THREAD

**Issue by carlf** [mssun/passforios#400]
I'm having some kind of problem. It's hard to explain clearly but it's reproducible. When I try to open a password entry, the app crashes immediately. This happens both with the current release and the version on TestFlight. I have wiped everything with "Erase All Password Store Data" repeatedly. I have also re-installed multiple times and even tried uninstalling from the storage section of the settings app. No matter what I do, it crashes as soon as it reads a password entry.

Even stranger, I have the current release version on my iPad and it works perfectly every time. The same ascii-encoded keys were used on both.

Cloning the repo works fine every time.

I'm at my wits end at this point. This is my primary password storage mechanism and I really don't want to go back to typing these heinously long passwords I have generated over the last several years.

**Comment by carlf** [comment]
Also another odd observation. For pure voodoo purposes I tried entering my public and private keys without saving the gpg password and it prompts me every time for the password. The odd thing is that even after I clear out the gpg keys and replace them it never asks again whether I would like to store the password.

**Comment by carlf** [comment]
I gave it another try from scratch. I uninstalled the beta app, installed the app store version fresh, imported my SSH, private, and public keys. The git repo clones perfectly. It accepts my password and saves it. It still crashes every time when I try to open a given password. The keys were sent to myself via signal and then copied and pasted into the app. I verified the header and footer are there and that the keys match the output of `gpg --export -a <key-id>` and `gpg --export-secret-keys -a <key-id>`. I am using the exact same config on my iPad and it is working fine with the same process and on the same version of the app. I feel like I must be doing something wrong but I'm completely lost as to what I am doing wrong.

**Comment by carlf** [comment]
I have also tried using `gpg --export-secret-subkeys -a <key-id>` as I am using subkeys. My keychain looks like this:

```
λ gpg -k
/home/cflippin/gnupg/pubring.kbx
--------------------------------
pub   rsa4096/0x7CED037602AB1C90 2019-01-29 [SC]
      Key fingerprint = 10BE 9A80 AB50 6159 FC73  195B 7CED 0376 02AB 1C90
uid                   [ultimate] Carl Flippin <cflippin@opentable.com>
uid                   [ultimate] Carl Flippin <carlf@carlf.io>
sub   rsa4096/0x63D102022B1552B3 2019-01-29 [S] [expires: 2021-01-30]
sub   rsa4096/0x7264A690007AE8D5 2019-01-29 [E] [expires: 2021-01-30]
sub   rsa4096/0x3255E72506B270F0 2019-01-29 [A] [expires: 2021-01-30]
```
The result in both cases is an immediate crash both in the App Store version and in the TestFlight version.

**Comment by carlf** [comment]
I think I have muddled this too much to be of much use. Going to open a clearer issue.

**Comment by pakdev** [comment]
Did you ever open another issue? I get random crashes when trying to read passwords too, but they occur on both my phone/iPad. Really frustrating

**Comment by carlf** [comment]
I didn't. I somehow got my problem solved but with a gun to my head I don't know that I could adequately explain how. :-(
