### ISSUE TITLE
Latest beta (0.10.0 (31)) crashes when invoked from Safari to fill in a password field

### ISSUE THREAD

**Issue by ismail** [mssun/passforios#404]
This is on iOS 13.6, when you click Passwords from Safari to invoke password auto-fill Passforios crashes. Attached is the backtrace.
[passAutoFillExtension-2020-07-23-134801.ips.beta.txt](https://github.com/mssun/passforios/files/4965689/passAutoFillExtension-2020-07-23-134801.ips.beta.txt)

**Comment by ismail** [comment]
Still happening with the latest beta 0.10.0 (38)

**Comment by ismail** [comment]
Any comments on this? The backtrace misses any useful debuginfo I'm afraid. I'm open to try some other way to debug this.

**Comment by dermorz** [comment]
I had similar issues with one of the recent beta builds. The reason on my device was some change related to gpg compatibility. After resetting my gpg key+config on the app and re-importing the private key vis itunes it was solved for me. 

Maybe you have the same issue? At least it would be worth a shot. 🤷🏻‍♂️

**Comment by ismail** [comment]
> I had similar issues with one of the recent beta builds. The reason on my device was some change related to gpg compatibility. After resetting my gpg key+config on the app and re-importing the private key vis itunes it was solved for me.
> 
> Maybe you have the same issue? At least it would be worth a shot. 🤷🏻‍♂️

This is a clean installation since the beta app changed, so I don't think that would help.

**Comment by dermorz** [comment]
I never had to do the whole setup (adding keys) again after the beta updated through TestFlight. But if you say all app data was wiped before/after/during installing the new version, you're probably right. I just thought it might be that since your issue doesn't seem to be a general issue happening to everyone.

**Comment by ismail** [comment]
> I never had to do the whole setup (adding keys) again after the beta updated through TestFlight. But if you say all app data was wiped before/after/during installing the new version, you're probably right. I just thought it might be that since your issue doesn't seem to be a general issue happening to everyone.

Are you sure you use the new beta app? Because the app identifier changed and you have to re-setup. That rename broke something, I think people are still on the un-renamed beta.

**Comment by ismail** [comment]
FWIW https://testflight.apple.com/join/whK4zUFG is the new beta that I'm testing and having this problem.

**Comment by dermorz** [comment]
Ah, now it makes sense. Thanks for clearing that up.

**Comment by ismail** [comment]
@mssun I'd appreciate a comment here, should I go back to the old-nonrenamed beta?

**Comment by ismail** [comment]
Fixed with 0.10.0 (43) update, thank you @SimplyDanny and @mssun !
