### ISSUE TITLE
Keyboard not appearing for search in Safari autofill

### ISSUE THREAD

**Issue by sebseager** [mssun/passforios#412]
When autofilling a form in Safari (iOS 14.0), the keyboard does not appear when the search bar is tapped. The website URL does fill into the search bar properly though, and an outline of the keyboard does sometimes appear if the app switcher/multitasking is entered.

**Comment by insanerwayner** [comment]
This seems to be the case after the iOS 14 update anytime you click the "Passwords" from the keyboard when filling passwords.   

Been having to go to the Pass app copy then past into whatever app I am logging into.

**Comment by insanerwayner** [comment]
This seems to be resolved now.

**Comment by seb-seager** [comment]
> This seems to be resolved now.

Agreed—I see the same, though the keyboard now does not dismiss interactively on TableView scroll. So once you've called up the keyboard you can't dismiss it again by dragging downwards, and any rows in the bottom half/third of the screen are inaccessible.

**Comment by alixmartineau** [comment]
I still have this problem on iOS 14.2 (iPhone 11 Pro).
Keyboard doesn't show to search for an entry.
Keyboard doesn't show either to enter passphrase when selecting an item from the list.
This is only a problem when opening Pass from the "Passwords" shortcut on the iOS keyboard while focused on a text field from within an app or Safari.

**Comment by insanerwayner** [comment]
> I still have this problem on iOS 14.2 (iPhone 11 Pro).
> Keyboard doesn't show to search for an entry.
> Keyboard doesn't show to enter passphrase when selecting an item from the list either.
> 
> Note: This is only a problem when opening Pass from the "Passwords" shortcut on the iOS keyboard while focused on a text field from within an app or Safari.

Yes this problem seems to have returned for me as well.

**Comment by greg-minshall** [comment]
(thanks so much for Pass for IOS!)  but, sadly, i, too, have this issue.

**Comment by sebseager** [comment]
> I still have this problem on iOS 14.2 (iPhone 11 Pro).
> Keyboard doesn't show to search for an entry.
> Keyboard doesn't show to enter passphrase when selecting an item from the list either.
> 
> Note: This is only a problem when opening Pass from the "Passwords" shortcut on the iOS keyboard while focused on a text field from within an app or Safari.

Ditto—I'm seeing this again as well, on iOS 14.2 stable.

**Comment by mssun** [comment]
Hi, this should be fixed in the latest beta version.

**Comment by mssun** [comment]
The 0.10.0 version has been released to App Store. Closed.

**Comment by greg-minshall** [comment]
thanks so much for the fix, and for pass for ios!!

**Comment by mssun** [comment]
Thank you @greg-minshall. Sorry for the delay.
