### ISSUE TITLE
UI: overlapping text with custom OS font size

### ISSUE THREAD

**Issue by glowinthedark** [mssun/passforios#422]
When a bigger font size is configured in system wide accessibility settings in iOS the app screen UI contains overlapping labels and widgets.

![78AAB143-2021-4332-978D-C0453CB4270F](https://user-images.githubusercontent.com/48893368/93808933-eea92d00-fc4c-11ea-9f0d-de08ecd1a5de.png)

Version: latest at the moment of creating this issue

Steps to reproduce:

 1. System Settings: Display and Brightness > Text Size
 2. Set a bigger Text Size than the default.
 3. Open the Settings screen in Pass.

**Comment by SimplyDanny** [comment]
Let me have a look ...

**Comment by mssun** [comment]
![image](https://user-images.githubusercontent.com/1270392/103807589-77d14d80-500b-11eb-9ca0-756210d37454.png)


Fixed.

**Comment by mssun** [comment]
0.11.0 has been released in App Store. Closed.
