### ISSUE TITLE
Can’t open or edit item, added from other devices 

### ISSUE THREAD

**Issue by ShahzarKibriya** [mssun/passforios#425]
I have three devices Linux, android, ios(iPad).
In iPad whenever i tries to open any entry added from android or linux-cli, the app gets close automatically.

iPadOS 14.0.1
Pass 0.9.0 (21)

**Comment by PenguinSnail** [comment]
I'm also having a similar issue on an iPhone 12 Mini iOS 14.2.1 with Pass 0.9.0 (21).
The app always crashes immediately whenever I try to open any entry regardless of if it was created on linux or on my phone, and on binary and ascii armored gpg files. I can still create entries on my phone, but then I can't open it again without the app crashing immediately.

**Comment by mssun** [comment]
Pass for iOS should be compatible with other clients. Can you describe how to create an entry which makes the app crash? Thanks.

Also, please use this link (https://testflight.apple.com/join/whK4zUFG) for the latest TestFlight version. Thanks.

**Comment by PenguinSnail** [comment]
The app crashes for me regardless of where the pass entry was made. I can create new entries in the app but when I try to view them later it crashes. I have installed and setup the latest beta but the issue is still present.

**Comment by mssun** [comment]
Hi all, I have read some recent crash logs and found that the crash point is in the GPG library. Can you give me some information for you GPG key? Could be some algorithms which the library doesn't support.

**Comment by PenguinSnail** [comment]
I've been using a rsa4096 key and have imported it by copy/pasting the ASCII armored export. However, this is the exact same key I used before I upgraded my phone and iOS version so that seems very strange that it suddenly won't work. Is there any specific information about my key that may be of use?

**Comment by mssun** [comment]
RSA4096 should work. You said you can create key but cannot view a key. Is that possible you are using a wrong public key?

**Comment by PenguinSnail** [comment]
Sorry it's taken a few days, but I've triple checked it's the correct key and am still having the same issue. What's even more odd is that when I create a new item within the app itself - meaning that item is guaranteed to be using that specific key - I can't open it again without the app crashing.

**Comment by ShahzarKibriya** [comment]
It is working fine now, don't know how and when it got fixed.
