### ISSUE TITLE
One-time password token support

### ISSUE THREAD

**Issue by evanwalsh** [mssun/passforios#43]
Hello! Any chance of support for OTP support (as implemented by [pass-otp](https://github.com/tadfisher/pass-otp))?

**Comment by mssun** [comment]
Good suggestion. We will work on it later.

**Comment by yishilin14** [comment]
Hi. We are now providing a very limited support for Time-based One-time Password Algorithm (TOTP).

We are able to generate one-time passwords for TOTP tokens, if one's encrypted password file contains **all five** related key-value pairs as follows. 

```
otp_secret: AAAAAAAAAAAAAAAAAAAAA
otp_type: totp
otp_algorithm: sha1
otp_period: 30
otp_digits: 6
```

The five lines could be in any order. It is ok if there are other none-related lines. If you use [pass-otp](https://github.com/tadfisher/pass-otp) to insert otp entries, you will get the correct format! 

We are still working on to providing a more user friendly UI (e.g., to refresh totp, to show the lifecycle of totp). Have fun.

**Comment by evanwalsh** [comment]
@yishilin14 Wonderful!

**Comment by mssun** [comment]
I guess you can update README to include this feature in. That's a very appealing feature.

**Comment by yishilin14** [comment]
HMAC-based one-time password (OTP) is now supported (0dccd91). 

We are able to generate a HOTP tokens if the password file contains the following key-value pairs.

```
otp_secret: AAAAAAAAAAAAAAAAAAAAA
otp_type: hotp
otp_counter: 30
otp_digits: 6 (optional, default 6)
```

These lines could be in any order. It is ok if there are other none-related lines. If you use pass-otp to insert otp entries, you will get the correct format!

I plan to close this issue now. Although we do need a better UI and a better documentation...
