### ISSUE TITLE
Build fails on Xcode 12.1

### ISSUE THREAD

**Issue by wazdra** [mssun/passforios#430]
Hi !

I've been desperately trying to build passforios on Xcode 12.1, as I'd like to contribute to the project. However, I haven't managed yet, because of the carthage bug : I get an xcrun lipo error during `./wcarthage update`
It looks like the workaround isn't going enough in depth (or maybe did I miss something, I'm not really experienced with Xcode)
Did any of you tried to rebuild from scratch since Xcode 12.1 ?

Cheers

**Comment by wazdra** [comment]
The issue seems to come from Base32 dependency of OTP.
I swapped OTP from Carthage to Cocoapods (along with all dependencies except obj-git). `./wcarthage` seems to do the trick now, and `pod install` works as well. However, `./gopengpg_build.sh` fails because of cross-compiling : `unsupported GOOS/GOARCH pair darwin/arm`. I am still trying to fix that, and then I will go on to pod integration

**Comment by SimplyDanny** [comment]
The Go issue might come from the fact that you are not using version 1.14.*. You can install it via `brew install go@1.14`.

**Comment by wazdra** [comment]
Yeah, I just noticed that ! I  [PRed](https://github.com/mssun/passforios/pull/431) to add this to the readme.
I just finished building dependencies through Carthage, pods and go successfully, but things are still not working out :
`/Users/wazdra/Documents/passforios/pass.xcodeproj The linked and embedded framework 'ObjectiveGit.framework' is missing one or more architectures required by this target: i386.`
I'm now trying to go through this but I'm moving slowly (Xcode is so vast...)
I hope you don't mind me documenting my way through building here.

**Comment by wazdra** [comment]
Ok, so I haven't yet managed to build with all the dependencies on pods, but I found the issue with carthage (going back and forth...) : the `wcarthage` script is outdated. There is an [officially documented script](https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md) on the homepage of Carthage's github. I'll just make sure everything builds, then I'll come back to you.
We can either change wcarthage to the script given, or point out to the script to Xcode 12 users so they do put it in their path. Honestly, I don't know what is best practice. Putting scripts in path shouldn't be done that lightly

**Comment by wazdra** [comment]
With the new script, dependencies are correctly built. This has been [PRed](https://github.com/mssun/passforios/pull/433)
