### ISSUE TITLE
Swiftlint fails in Xcode 12.1

### ISSUE THREAD

**Issue by wazdra** [mssun/passforios#434]
At the moment, `swiftlint --strict` fails because of automatically generated files. [Here](https://framabin.org/p/?8f57403b57e9a85c#q7peBYfoXVA2gkiZgEQdkCmvBN2r+/VjvGOXPR7VkoQ=) is the result. I'm new to Swift and Xcode, so I'm a bit lost. In the mean time, I managed to build removing the rules `implicit_return,strict_fileprivate,attributes` from `.swiftlint.yml` but I am sure this is not the right way to do.

**Comment by SimplyDanny** [comment]
Looks like you have the `DerivedData` folder directly in your project. This is configurable. In my case it is located at `~/Library/Developer/Xcode/DerivedData` (the default). You can set it in Preferences -> Locations for all projects. The project settings can overwrite it, but this isn't the case for Pass for iOS.

The DerivedData folder contains additional Swift files which are considered by SwiftLint. Issues in these generated files fail your build.

**Comment by wazdra** [comment]
Ok, everything works perfectly now ! Sorry for the issue, and thank you :)
