### ISSUE TITLE
Wrong text encoding

### ISSUE THREAD

**Issue by banteg** [mssun/passforios#44]
Password entries are decoded as **latin1** instead of **utf8**. This should be «проверка».

![slice](https://cloud.githubusercontent.com/assets/4562643/23445609/2b76f774-fe6f-11e6-8ea4-3bf854410dbc.png)

**Comment by mssun** [comment]
Thanks for the report. We will work on this issue.

**Comment by mssun** [comment]
Fixed. Please try again.

**Comment by banteg** [comment]
Looks great, thank you!
