### ISSUE TITLE
github deprecating passwords

### ISSUE THREAD

**Issue by mathematicalmichael** [mssun/passforios#441]
I got this email today:

---

You recently used a password to access the repository at xxxxx/pass with git using git/2.0 (libgit2 0.28.3).

Basic authentication using a password to Git is deprecated and will soon no longer work. Visit https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information around suggested workarounds and removal dates.

**Comment by SimplyDanny** [comment]
Good hint! But, I think, how a user authenticates at GitHub is not the responsibility of Pass. You may choose to use SSH instead or use a token as a replacement for the password.

**Comment by mssun** [comment]
Thanks for the reminder. I believe you can still use personal token [1], which is secure than user password directly.

[1] https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token

**Comment by mathematicalmichael** [comment]
oh good looks, thanks. I didn't see a way for ssh keys to be used with the Pass app but tokens make sense!

**Comment by mssun** [comment]
Hi @mathematicalmichael, you can also use SSH key for git authentication actually.

**Comment by mathematicalmichael** [comment]
@mssun oh awesome! thanks, I found the setting under "Password Repository."
