### ISSUE TITLE
0.10.0 build 58 breaks git protocol

### ISSUE THREAD

**Issue by ismail** [mssun/passforios#444]
My repository URL starts with git@github.com:ismail with build 58 when I try to pull from repo I get "unsupported URL protocol" error. Build 54 works fine.

**Comment by SimplyDanny** [comment]
I face the same issue with the `ssh://user@server` scheme.

**Comment by mssun** [comment]
I didn't touch codes related with git cloning. Let me check...

**Comment by mssun** [comment]
I just did a quick experiment. I can clone from gitlab with ssh://user@server scheme and SSH key.

**Comment by mssun** [comment]
Ok, I see the problem. The TestFlight versions are built in CI. Something wrong with building the objective-git in CI.

**Comment by mssun** [comment]
Fixed in build 61. Please try again. Thanks for the report!

**Comment by ismail** [comment]
Confirmed fixed, thank you once again!
