### ISSUE TITLE
[0.10.0 Build 61] Autofill-extension search no longer works

### ISSUE THREAD

**Issue by ismail** [mssun/passforios#445]
Go to a password field and press Passwords, the password list shows up with Search field empty and _all_ passwords listed. Enter a search term and nothing happens., clicking search after entering a term doesn't work either.

**Comment by mssun** [comment]
Fixed in build 64.

**Comment by ismail** [comment]
Search is indeed fixed but search field comes up empty. It used to come with current URL which filtered the results.

**Comment by mssun** [comment]
@ismail, can you help to test the build 67, which supports password suggestion and selecting passwords from the QuickType bar when enabling AutoFill.?  Thanks.

**Comment by ismail** [comment]
In general this seems to work, but there are some oddities, e.g.

For _news.ycombinator.com_ the suggestions are (among others):

bbc.com
c-and-a.com
economist.com
faz.net
news.ycombinator.com
nytimes.com
sz.de
t-mobile.net

etc., so I think matching algorithm needs some work. I don't mind broad matches but for some hostnames like _imap.suse.de_ it nearly matches all entries, it used to match only two.

**Comment by mssun** [comment]
Thanks for your feedback. Yes, something wrong with the matching algorithm. Let me fix it.

**Comment by ismail** [comment]
Just tested build 68 and now it works as before, that is it does still have some broad matches but it's not a big list.

But the point is, there is no regression anymore, thanks for the prompt fixes!

**Comment by mssun** [comment]
Great! The current matching algorithm is pretty straightforward and indeed does a broad matches.

https://github.com/mssun/passforios/blob/571281b655ce0544cf89eb190004639e5e151be0/passKit/Models/PasswordTableEntry.swi#L30-L42

This definitely can be improved, but I don't have time for this currently.

**Comment by raywu** [comment]
Thanks for fixing this! I have been using the App Store build and haven't seen this fix gone up. I know you mentioned this is in build 68. I downloaded the TestFlight build and saw this issue was fixed. Do you have an estimate on when you'd publish to App Store?
