### ISSUE TITLE
Autofill does not work for apps after 0.10.0 upgrade iOS 14.3

### ISSUE THREAD

**Issue by nholik** [mssun/passforios#449]
After upgrading to 0.10.0, selecting a password to autofill from an app no longer works.  Websites in safari work fine, but from an app clicking does nothing.  This is on iphone 11 iOS 14.3.  Let me know if further information would be helpful.

**Comment by mssun** [comment]
Could you tell me the name of the app? Thanks.

**Comment by nholik** [comment]
Pretty much all apps I've tried do not allow filling in, two examples are etrade and tdameritrade

**Comment by mssun** [comment]
Thank you. This is very helpful!

**Comment by mssun** [comment]
Fixed in 6280b15. Will be released in the TestFlight channel.

**Comment by nholik** [comment]
Thanks for the quick response, I'll try out the TestFlight version this weekend.

**Comment by mssun** [comment]
I'm closing this issue. 0.11.0 has been released in App Store. Feel free to reopen if the issue still exits.

**Comment by nholik** [comment]
Working good, thanks
