### ISSUE TITLE
0.10 version doesn't scan my qr codes anymore

### ISSUE THREAD

**Issue by Peter4825** [mssun/passforios#451]
Hi,

I've updated to the latest 0.10.0 version, and due to the multiple pgp key issue I decided to just delete my PGP key and try again.  By doing so I discovered that the 0.10.0 version's QR code scanner seems to be broken.
I've downloaded the testflight beta 0.11.0 (6) version, and also with this version I cannot seem to get the QR code scanner to work.

As a test, I've created a new ssh key and QR code as follows:
ssh-keygen -t rsa -f passtest -N ""
cat passtest |  qrencode -o passtest.png

Since this is a test key, I just attached the png to this ticket as it is:
![passtest](https://user-images.githubusercontent.com/37265833/104094449-479ae080-5291-11eb-86b5-2532432b03b5.png)

When scanning this with passforios it says "one scanned qrcode" but it does not seem to automatically accept this qr code, and there is no button "done scanning" so I just don't know how to continue, I'm stuck at the scanning screen.

Note that I did have the issue with my GPG-keys, the ssh example above was just an easy test-case as it also happens to be a problem with scanning ssh keys.

Note, my gpg key is too big.  I've made the QR code as follows: cat gpgpubkey | qrencode -S -v 40 -l L -t png -o gpgpubkey.png
which generates 2 seperate png files.  When first scanning the 2nd image, the scanner clearly states "Looking for the first frame", so it recognizes that the QR code is a multipart.  When scanning the 1st image, it says "One scanned QR code", followed by "2 scanned QR codes" when shown the 2nd image.    Again no automatic realisation that the scan is complete and no button to "save" and continue.   If I then scan the 1st QR code again, it even says  "3 scanned QR codes" and if I keep rotating between my 2 png's, it keeps on counting 4,5,6 scanned qr codes...  So it seems something is broken there...

Note that with I initially imported my GPG/ssh keys with a previous version and that the files were accepted and imported with QR codes, so I assume they are valid as they have worked before...

**Comment by mssun** [comment]
Thanks for the report. I have fixed the issue in 87d1dd5.

This is caused by a new line character in the footer of the ascii armored key. Will release a new TestFlight version. Thanks.

**Comment by PierrickGT** [comment]
> Thanks for the report. I have fixed the issue in 87d1dd5.
> 
> 
> 
> This is caused by a new line character in the footer of the ascii armored key. Will release a new TestFlight version. Thanks.

Tried to import with latest test flight version, 0.11.0 (11), and I can now import my keys by scanning QR codes but it's adding a `-n` at the beginning, so when I save, I get the error message that the keys can't be read.
![image](https://user-images.githubusercontent.com/2401738/104237194-ff79ea80-5457-11eb-8a1b-0a69a21f999c.jpeg)
![image](https://user-images.githubusercontent.com/2401738/104237202-030d7180-5458-11eb-9fb4-ef07b5672ee6.jpeg)

**Comment by mssun** [comment]
This is very wired... Can you share with me the QR code of your public key?

**Comment by PierrickGT** [comment]
> This is very wired... Can you share with me the QR code of your public key?

![QR1](https://user-images.githubusercontent.com/2401738/104285331-c66f6380-54b3-11eb-977b-48172aa4563a.png)
![QR2](https://user-images.githubusercontent.com/2401738/104285334-c707fa00-54b3-11eb-9124-ff9628ff3935.png)

I'm using this tool to generate the QR codes: https://github.com/4bitfocus/asc-key-to-qr-code

**Comment by mssun** [comment]
Hi @PierrickGT, I'm using the iOS builtin Camera app to scan the first QR code and it shows the `-n` prefix you mentioned. I'm pretty sure your original QR code contains a `-n`.

**Comment by PierrickGT** [comment]
> Hi @PierrickGT, I'm using the iOS builtin Camera app to scan the first QR code and it shows the `-n` prefix you mentioned. I'm pretty sure your original QR code contains a `-n`.

Ah yes you're right, my script to generate QR codes was adding this `-n`. I fixed it and everything is working perfectly now.
Thanks for your help and your awesome app!

**Comment by mssun** [comment]
Thanks for your confirm. Closed.
