### ISSUE TITLE
v 0.11.0 (8) Testflight Beta: Cannot import keys

### ISSUE THREAD

**Issue by MarkusZoppelt** [mssun/passforios#452]
Cannot import gpg keys into application.

I tried:
- Import via copying ascii-armored keys into application
- iTunes filesharing

Method used for exporting keys from desktop:
```
gpg --export -a <gpg-id> > gpg_key.pub
gpg --export-secret-keys -a <gpg-id> > gpg_key
```

**Comment by mssun** [comment]
Thanks! How do you generate the key?

**Comment by MarkusZoppelt** [comment]
I did a generic 
`gpg --generate-key ` for a rsa4096 key.

FYI, I already used that key for both passwordstore and Pass for iOS for years and it worked perfectly until v.0.10.0 released Jan 6 2021.

And also btw, this is my pubkey: https://keybase.io/zoppelt/pgp_keys.asc?fingerprint=a4c813d69454762b56e6b36447e40c6c5db65951

**Comment by mssun** [comment]
Just tried your public key. I can successfully import it.

**Comment by MarkusZoppelt** [comment]
It just worked for me too. No idea why.

Sorry. Closing this issue.
