### ISSUE TITLE
Improve support for gopass (GOPASS-SECRET-1.0)

### ISSUE THREAD

**Issue by WolfangAukang** [mssun/passforios#453]
Hey, first I wanted to thank you for the app. It's really been great and with having it available on Github gives me more trust in using it.

Now, my issue is that I use Gopass. It seems Gopass handles the information differently for each key. Let me throw an example:
```
GOPASS-SECRET-1.0
Comment:
Password: here1sp@ssword
Totp: Here is a TOTP key
Url: service.com
Username: me
```

So, my issue when using Pass is that for these secrets, the following happens:
- The password will show the header above (`GOPASS-SECRET-1.0`). Makes sense, because that's how it's done through Pass AFAIK.
- For the TOTP, it shows the secret key on the additions section (which can be dangerous somehow). But again, not your fault, because Pass handles it differently with the otpauth section, which is a long totp url.

I wanted to see if there is a way to implement some kind of compatibility with this format from Gopass.

**Comment by mssun** [comment]
@WolfangAukang Thanks for bringing up this issue. Does gopass has a detailed specification for their password entry?

**Comment by WolfangAukang** [comment]
Unfortunately I can't seem to find anything detailed about it, only about the [totp section](https://github.com/gopasspw/gopass/blob/ad8484179787a519eca600406cfb589868910916/docs/usecases/secure-otp.md).

**Comment by kifirkin** [comment]
I remember that `mime` was introduced at version [1.10.0](https://github.com/gopasspw/gopass/blob/b9b0f1be985f5a3ae25a77852064aaf1e042c952/CHANGELOG.md#1100)

But I think it was removed later.
Try to run `gopass fsck` to fix leftover mime

**Comment by WolfangAukang** [comment]
@kifirkin quick question, what would be the idea of executing this command? I have executed it but don't know what to check

**Comment by kifirkin** [comment]
@WolfangAukang to check whether it fixed problem, try to `gopass edit` that secret, with seems to be broken in PassForIos

**Comment by WolfangAukang** [comment]
No luck, unfortunately.

I even tried the `gopass config mime false` with no luck. (`Error: Error setting config value`)

**Comment by kifirkin** [comment]
Check wether `gopass fsck` has arguments for that case, or maybe better to ask `gopass` folks for the answer?

**Comment by WolfangAukang** [comment]
No luck with `gopass fsck`. I'm going to ask them for a way to at least change the mime, thank you!

**Comment by janrito** [comment]
looks ike this format is deprecated anyways https://github.com/gopasspw/gopass/blob/ee3d5183cd858df3aa30b5e8bf96fee89028e4fc/docs/secrets.md#deprecated-formats

**Comment by WolfangAukang** [comment]
Honestly (and no offense to the devs, I had a great time using `gopass`) I have already stopped using it. So I'm going to close the issue.
