### ISSUE TITLE
PGP authentication subkey error: unable to extract public key from private key

### ISSUE THREAD

**Issue by baj0k** [mssun/passforios#454]
Hello,

I've been using passforios successfully for some time now. I am hosting my pass repository locally and today I changed my rsa key to a gpg authentication subkey. I am using the gpg-agent to connect to the machine with a new key, but after importing my new key to the app I am unable to clone my password-store repo due to an error: "Failed to authenticate SSH session: Unable to extract public key from private key".

I think the issue might be that the new key is using pgp key format starting and ending with
-----BEGIN PGP PRIVATE KEY BLOCK-----
...
-----END PGP PRIVATE KEY BLOCK-----
which is not the correct format that the ssh is expecting.

I know that the problem is with ssh itself rather than passforios, but I would like to ask if anyone managed to use gpg authentication subkeys with pass somehow  (Maybe there is a possibility to convert pgp private key format to openssh)?. Would it be overkill to integrate some kind of gpg-agent into passforios? Even if one had some kind of gpg-agent configured on the mobile phone, there is currently no option to support it on passforios app.
Thanks for help in advance.

**Comment by mssun** [comment]
I think you can use `openpgp2ssh` (http://manpages.ubuntu.com/manpages/bionic/man1/openpgp2ssh.1.html) to converting key format, but seems that it only works with RSA keys.

**Comment by mssun** [comment]
Here is a good article about converting between openssl/openssh/pgp keys: http://sysmic.org/dotclear/index.php?post/2010/03/24/Convert-keys-betweens-GnuPG%2C-OpenSsh-and-OpenSSL.

For your case, you can also use `gpgsm` to convert pgp key to pkcs12 keys and then use openssl to export as the PEM key.

**Comment by baj0k** [comment]
Thanks! This explained a lot. 
I can't find a way to convert ed25519 keys between different formats, but since some software/firmware still doesn't offer support for EC keys at all I will just be good having few RSA subkeys at the moment.

**Comment by baj0k** [comment]
Just for future reference, this has worked for me with an rsa authentication subkey: (again thanks @mssun for those articles)
$ gpg --list-secret-keys --with-keygrip
 $ gpgsm --gen-key -o temporary.cert
 > Existing Key
 > use keygrip from gpg output
 > fill the X509 values
 > create a self signed certificate
 $ gpgsm --import temporary.cert
 $ gpgsm --list-keys
 > find the key just imported
 $ gpgsm -o cert.p12 --export-secret-key-p12 ${KEY_ID}
 $ openssl pkcs12 -in cert.p12 -nocerts -out gpg-secret-key.pem
 $ openssl rsa -in gpg-secret-key.pem -pubout > gpg-public-key.pem
