### ISSUE TITLE
Fresh Build.  Unsupported URL protocol when connecting via. SSH

### ISSUE THREAD

**Issue by jclement** [mssun/passforios#46]
I've done a fresh build.

When I try and connect to by git server via. SSH using either a password or key files I get a "Unsupported URL protocol".  I've tried everything I can think of for the Git Repository URL:

My server name is correct, listening to SSH on port 22, and has a user called "pass" with the password store repo in "pass.git" in the user's home folder.

* server:pass.git (I think this is the right one)
* pass@server:pass.git
* ssh://pass@server:pass.git
* ssh://pass@server:port/home/pass/pass.git
...

I found this issue and I'm wondering if the underlying libgit wasn't compiled with SSH support.  Maybe Carthage needs some additional hints?

https://github.com/libgit2/git2go/issues/249

```
password-store-temp" UserInfo={NSLocalizedDescription=Failed to clone repository from pass@someserver.net:22/home/pass/pass.git to file:///var/mobile/Containers/Data/Application/..../Library/password-store-temp, NSUnderlyingError=0x17044fc30 {Error Domain=GTGitErrorDomain Code=-1 "Unsupported URL protocol" UserInfo={NSLocalizedDescription=Unsupported URL protocol}}}
```

**Comment by mssun** [comment]
I haven't try/test the ssh protocol. I guess https should be fine. I will work on this.

**Comment by mssun** [comment]
The valid format should be: ssh://server/pass.git. Username is your username: `pass`. BTW, only SSH Key authentication method can be used for ssh protocol.

**Comment by jclement** [comment]
You were able to make it work with that? That is one of the patterns I tried, and I just tried it again, and I get the "unsupported URL protocol".

**Comment by yishilin14** [comment]
@jclement I am unable to clone using either "git@github.com:myusername/xxxxxxxx.git" or "ssh://git@github.com:myusername/xxxxxxxx.git". Let me see whether I could fix this.

**Comment by yishilin14** [comment]
@jclement I am able to clone my Github repository with url "ssh://git@github.com/myusername/myreponame.git" and username "git". I feel that I agree with @mssun about the url and username.

May I know what is the output in your Xcode console? Error messages about the clone process shall be printed there.

**Comment by mssun** [comment]
- set Git repository (URL, username, authentication), note that the valid SSH URL should be `ssh://server:port/url/to/repository.git` (`ssh://github.com:22/mssun/pass.git`) and the username is put in the next field under URL (e.g., git), only SSH key authentication is supported for SSH URL
  - HTTPS URL example:
    - URL: https://gitlab.com/passforios-demo/demo.git
    - Username: passforios-demo
    - Authentication Method: Password
  - SSH URL example:
    - URL: ssh://git@gitlab.com/passforios-demo/demo.git (original is git@gitlab.com:passforios-demo/demo.git)
      - remember to include username in the url
      - remember to change ":" to "/"
    - Username: git
    - Authentication Method: SSH Keys

Updated in the wiki page.

I'm closing this issue. Will consider providing a better UI.

**Comment by fancyoung** [comment]
The bug reopened on new version v0.4.

with ssh://user:server/... + SSH key authentication

**Comment by apfohl** [comment]
#186
