### ISSUE TITLE
RFE: better workflow around OTP

### ISSUE THREAD

**Issue by intelfx** [mssun/passforios#469]
I'm not sure if this can be done due to artificial limitations of iOS, but workflow around OTP needs to be improved.

Right now, when you select and fill a password via the autofill integration, it is not remembered anywhere. If the site consequently asks for an OTP password, the user has to manually open the Pass app, _manually find the corresponding password entry_ and copy the OTP password. Basically the whole convenience of autofill is negated.

Suggestion: instead, when a user selects an entry via the autofill, Pass should somehow remember the selection and offer it when the Pass app is subsequently opened.

**Comment by apfohl** [comment]
An alternative approach would be, to copy the OTP token into the clipboard after autofill was proceeded. The the user could simply paste again to login. I guess OnePass is doing it like that, but not sure. This would provide a seamless workflow What do yo think?

**Comment by intelfx** [comment]
That's very close to what Pass-for-iOS is doing right now. When the notification is shown, you can long-tap it to bring out a menu where you can click "copy to clipboard". Unfortunately, the copying itself does not work for me for some reason.

**Comment by apfohl** [comment]
Okay, though I never seen a notification so far. Is the feature released by now?

**Comment by intelfx** [comment]
Oh. I'm sitting on the TestFlight build. Chances are, it was never released.

**Comment by apfohl** [comment]
Maybe will be soon. Hopefully because it would make life much easier for me doing this every day multiple times. ;)

**Comment by intelfx** [comment]
I'm also seeing a commit with some fixes to the OTP stuff right after the build date. @mssun any chance for a new TestFlight build, or better yet, a release?

**Comment by intelfx** [comment]
Pass is now capable of automatically copying the OTP into the pasteboard, which is good enough for me. Closing.
