### ISSUE TITLE
Support for longer passcodes

### ISSUE THREAD

**Issue by raxod502** [mssun/passforios#49]
I always use at least ten digits for my iPhone passcodes. It would be nice to have support for this in Pass for iOS.

Relevant: https://github.com/yankodimitrov/SwiftPasscodeLock/issues/55

(But the issue might be upstream.)

**Comment by mssun** [comment]
Yes, six-digit passcode needs to custom UI. I think six digits is reasonable. Let me try to implement this. However, providing options to choose from is more flexible.

**Comment by raxod502** [comment]
What I was expecting as a user was the same interface as I get when creating my passcode for the iPhone (i.e. it defaults to 4-digit, but you can select an arbitrary-number-of-digit passcode or an alphanumeric one from the same screen). Is there some reason why Apple doesn't expose an API for generating this screen?

**Comment by mssun** [comment]
Unfortunately, no handful API provided from Apple. Therefore, we have to implement the function by ourselves.

**Comment by mssun** [comment]
@raxod502 Are you working on this? I saw you fork the repo.

**Comment by raxod502** [comment]
@mssun It's one of the issues that I would be interested in finding a solution for. But because I don't have much experience with Swift or Xcode, I'm holding off on working on this in favor of looking at other (simpler) parts.

**Comment by mssun** [comment]
Sure, thanks for you contributions.

**Comment by mssun** [comment]
Hi, I saw you try to change to ten passcode. Is everything OK? I thought the passcode lock UI only support four digits. For more digits, I guess you should customize the lock UI.

**Comment by raxod502** [comment]
@mssun Although the UI doesn't look right, it works just fine with 10 digits. (There are four dots, but it still waits for six more digits after those dots become filled in.)

**Comment by mssun** [comment]
How about I closing this issue right now? Maybe in the next release, we may seek methods to customize the UI for better experience.

**Comment by raxod502** [comment]
If you'd like "open" to mean "is a current goal" in this issue tracker, then that sounds perfectly reasonable.

**Comment by posix4e** [comment]
What else is left to do?

**Comment by raxod502** [comment]
As far as I know, the feature is not implemented. So, we're looking for a better passcode lock framework as per https://github.com/mssun/passforios/issues/122#issuecomment-330180454.

**Comment by yishilin14** [comment]
Pass v0.3.7(12) supports longer passwords now! I implemented a simple passcode lock (with an ugly UI). =D
