### ISSUE TITLE
ITMS-90338: Non-public API usage

### ISSUE THREAD

**Issue by mssun** [mssun/passforios#508]
Starting from the recent commit (82eb13f43ca799ce3d62531a4fc796a318b0d8a9), App Store Connect gives me the following feedback:

> Dear Developer,
>
>We identified one or more issues with a recent delivery for your app, "Pass Beta - Password Store" 0.12.0 (35). Please correct the following issues, then upload again.
>
>ITMS-90338: Non-public API usage - The app references non-public symbols in Frameworks/passKit.framework/passKit: _getentropy. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/
>
> Best regards,
>
> The App Store Team

I'm not sure which library uses this API. I'll investigate the issue. During this period, I cannot upload any TestFlight and new release.

**Comment by SimplyDanny** [comment]
This is an [issue](https://github.com/golang/go/issues/47812) in Go 1.17 and has been fixed in 1.17.1 which is available via Homebrew for half a day. So I expect the problem to be resolved with a new build.

**Comment by SimplyDanny** [comment]
It works again, doesn't it?

**Comment by mssun** [comment]
> This is an [issue](https://github.com/golang/go/issues/47812) in Go 1.17 and has been fixed in 1.17.1 which is available via Homebrew for half a day. So I expect the problem to be resolved with a new build.

Yes, I'm using the latest go in the homebrew. It works.

**Comment by zubairahmad2** [comment]
Yes,  after 2 days i was using version 1.17 and i am facing this issue now I'm using the latest go1.17.2 version in the homebrew. It works. fine Thanks a lot @SimplyDanny
