### ISSUE TITLE
Let User choose if gpg files should be armored or in binary format

### ISSUE THREAD

**Issue by Shinzu** [mssun/passforios#51]
Hi,

i had the last days time to test the app.

one of the points that need attention (in my opinion) that the user should be able to choose in which format new created or changed secrets should be stored ... binary or armored.

I always prefer to have my ggp files armored, even if a diff of this is also useless for a human :)

greetings

**Comment by mssun** [comment]
We try to be compatible with the pass command line tool. Does it support armored format for storage? I didn't see this option.

**Comment by Shinzu** [comment]
You have no setting in pass for it , but it does not change the setting you have in your gpg.conf.

in the lib you are using it is also supported:

https://github.com/krzyzanowskim/ObjectivePGP#encrypt-data-with-previously-loaded-public-key

```
/* encrypt data, armor output (ASCII file)  */
NSData *encryptedData = [pgp encryptData:fileContent usingPublicKey:keyToEncrypt armored:YES error:&error];
if (encryptedData && !error) {
    NSLog(@"encryption success");
    [encryptedData writeToFile:@"/path/to/encrypted/file.gpg" atomically:YES]
}
```

**Comment by mssun** [comment]
Support in 0507c7c. Thanks for your suggestion.

I'm closing this issue. If you have new issue regarding to this feature, please consider to open a new one. Thanks.
