### ISSUE TITLE
Found a possible bug or two using your app in a different way than intended

### ISSUE THREAD

**Issue by bedwardly-down** [mssun/passforios#525]
So, I’ve been using password-store and your app for awhile now to handle my passwords. I love the overall flow and structure of both. Recently, though, I’ve been looking for a good journaling app that offered at least basic encryption and haven’t found too many that worked with my current setup. Then, it dawned on me. Why not try it using password-store?

Surprisingly enough, there doesn’t seem to be a real limit on how many characters its files can take and journaling from your app works really well by just putting my entries in the Additions section and labeling as `Journal/<Today’s Date>` as shown here: 
![0EE48492-9E23-44E7-BB96-D303225DC4D3](https://user-images.githubusercontent.com/59133880/144712195-dd5031ab-f21a-4af3-b354-630e71b4b6be.jpeg)

I did notice some tiny issues, though:

- After so many lines, the box will sometimes start violently shaking up and down if I stop typing long enough (seems to be random when and how long)
- Sometimes, autocorrect and word suggestions don’t work or show above the keyboard meaning higher chance of typos

iOS: 15.1.1
iPhone: 12 mini
App Version: Latest stable release

**Comment by mssun** [comment]
Hi @bedwardly-down, thanks for your feedback.

I'll work on this issue today. Just to confirm, the issues you mentioned here is for the "ADDITIONS" text field?

**Comment by mssun** [comment]
Can you try the beta version in this link: https://testflight.apple.com/join/whK4zUFG?

A lot has changed since the latest stable release.

**Comment by bedwardly-down** [comment]
Just saw this. Yes, the issue was in the additions box. I can definitely try the beta.

**Comment by bedwardly-down** [comment]
So far, the latest stable release: 0.12.0 has been great! It has some minor quirks but is so much smoother and easier to use. Closing this for the time being unless the issue pops back up again.
