### ISSUE TITLE
Pass Beta expired

### ISSUE THREAD

**Issue by rngtng** [mssun/passforios#531]
Hey hey. Can you pls publish a new beta? Mine just expired and I can’t use the app anymore :(
Cheers Tobi

**Comment by greg-minshall** [comment]
+1, or maybe, +100.  happy new year, too!

**Comment by bedwardly-down** [comment]
I was asked to test the beta for a bug I found and definitely would love to be able to try it again.

**Comment by mssun** [comment]
Hi all, I just release a new TestFlight. Sorry, I forgot to notify all testers.

**Comment by greg-minshall** [comment]
hooray -- thanks *so* much!!  (and, for Pass for IOS, too!)

**Comment by rngtng** [comment]
Yes. Thanks a lot! Happy new year!

**Comment by anh193** [comment]
Is there actually anything else to test? I can't wait to use it as an official release! Do you have any estimates when that could actually happen?
