### ISSUE TITLE
FaceID unlocks by itself when autofilling in Safari

### ISSUE THREAD

**Issue by clemisch** [mssun/passforios#537]
I have the app configured with passcode lock and FaceID.

When using it for autofill in Safari, the lock prompt quickly appears, disappears and autofill+login is executed.

However, there **seems to be no actual check on FaceID for unlocking**! If I turn my iPhone away (such that FaceID should not work), passforios happily enters my password in Safari on any site.

Is this intended behavior? Before the recent update, you had to tap on "FaceID" manually and there indeed was a check.

FWIW, the passcode lock and/or FaceID work when opening passforios directly.

**Comment by clemisch** [comment]
Furthermore, because of this instant opening/closing of passforios, it picks the first password suggestion automatically without the possibility to choose. When the first suggestion is not correct for the website, you're out of luck.

**Comment by clemisch** [comment]
Any update on this? Especially the [second bug](https://github.com/mssun/passforios/issues/537#issuecomment-1009633902) is really annoying.

**Comment by jesselucas** [comment]
I experience the same issue but with passcode only (Face ID not enabled)

**Comment by clemisch** [comment]
Any news on this?

**Comment by jesselucas** [comment]
After updating to version 0.13.0 the issue still exists for me. Autofill does not prompt passcode (Face ID not enabled)

**Comment by mssun** [comment]
@jesselucas, the PR is just merged and will be in 0.14.0. I'll publish it in TestFlight.

**Comment by mssun** [comment]
Please reopen this if it is still not fixed.

**Comment by jesselucas** [comment]
💖 Thank you for the quick reply!
