### ISSUE TITLE
Favicon if url is set

### ISSUE THREAD

**Issue by Hans-Maulwurf** [mssun/passforios#54]
If field "url" contains valid url then the entry should get the favicon of the website.

**Comment by mssun** [comment]
Yes, only if:
  - the url starts with https (this is a requirement by Apple)
  - favicon can be obtained

**Comment by mssun** [comment]
This could be improved actually.
  - try to fetch favicon with url content if it is a valid url
  - chante http to https for security

**Comment by mssun** [comment]
Fixed by: f573be9

I'm closing this issue. Please reopen if you have any other related questions.
