### ISSUE TITLE
"Pass Beta" Beta Has Expired

### ISSUE THREAD

**Issue by greg-minshall** [mssun/passforios#553]
hi.  i guess the beta appears to have expired.  would you refresh it?  should we convert to the non-beta version?  cheers!

**Comment by Logicwax** [comment]
Just noticed this too.    I’ve been testing the new yubikey support which is only in the beta versions.

**Comment by rem7** [comment]
Using yubikey as well but now I’m not able to. Any updates on when it’ll be available? Or can we get the beta back?

**Comment by drGrove** [comment]
Looks like Testflight is no longer accepting new beta users. Would love to join the beta if possible

**Comment by hyiltiz** [comment]
This led to quite a lot of inconveniences for me as I relied on pass in my phone for all my passwords, and somehow, without earlier notice, I lost access to them all. Granted I could probably re-install the standard version and set it up, but an early warning would be nice, or keep the current beta testers' account open until they close themselves. Considering it is managing access to everything, it is like your guard no longer lets you into your own building...

**Comment by greg-minshall** [comment]
> This led to quite a lot of inconveniences for me as I relied on pass in my phone for all my passwords, and somehow, without earlier notice, I lost access to them all. Granted I could probably re-install the standard version and set it up, but an early warning would be nice, or keep the current beta testers' account open until they close themselves. Considering it is managing access to everything, it is like your guard no longer lets you into your own building...

it is inconvenient.  but, i suspect many of the restrictions are from `testflight`, Apple's beta application.  obviously, a beta program should only go on "so long".  it might be nice of Apple to warn beta users, etc.

**Comment by mssun** [comment]
I have submitted a new version to the TestFlight. Sorry for the inconvenience. I was very busy in recent months.

Now, I can finally have more time on this. I'll actively work on the project in the following weeks.

**Comment by rngtng** [comment]
Works again. Thanks a lot! 😍

**Comment by ukrainian-im** [comment]
Hi, the beta is about to expire.
Would you please refresh it?

Installed it because of Yubikey, and with a few exceptions it's been working for me.
Sometimes it would fail with an error, _after_ PIN prompt. PIN attempt isn't consumed. So no lockout, etc
App restart didn't help if I remember correctly.
Next time will try to capture the problem and submit problem report .
Should it transition to release? 

Thanks!
