### ISSUE TITLE
some documentation on using gpg-serve-key on a local network

### ISSUE THREAD

**Issue by greg-minshall** [mssun/passforios#554]
hi.  i like gpg-serve-key, but don't want to use it on the public internet, but *do* want to use it with https.  here is something i wrote, if you wanted to put it, or some more-readable version of it, on the wiki maybe?

[the original .org source](http://minshall.org/2022/eiQuo6ch/pass-ios-serve-key-localnet/pass-ios-serve-key-localnet.org) (probably you can't conveniently click on this, but could use `curl(1)` or `wget(1)` to retrieve it.)

[the exported .html file](http://minshall.org/2022/eiQuo6ch/pass-ios-serve-key-localnet/pass-ios-serve-key-localnet.html)

**Comment by greg-minshall** [comment]
i've created a small repo with an updated version [here](https://git.sr.ht/~minshall/pass-ios-serve-key-localnet).

**Comment by mssun** [comment]
Hi @greg-minshall, thanks for the contribution! Do you mind I put this on the wiki page?

**Comment by greg-minshall** [comment]
@mssun go for it!

**Comment by mssun** [comment]
Done. Link: https://github.com/mssun/passforios/wiki/Setting-up-pass-for-ios-using-gpg-serve-key-using-https-on-a-local-network

Maybe I should consider to put all wikis in the `docs` directory so that the community can help.
