### ISSUE TITLE
An option to rename Pass

### ISSUE THREAD

**Issue by lasers** [mssun/passforios#557]
I use both `Pass` and `iCloud Keychain` so when I need to log in, I would get a `Passwords` prompt, I clicked this then I will be prompted with `Pass` and `iCloud Keychain`. I think it would be an improvement to rename `Pass` to `Pass for iOS` to help differentiate between `Pass` and initial `Passwords`. I sometimes clicked `Pass` quickly in some places thinking it would open Apple Passwords.

I understand this might be totally unnecessary because many iOS apps doesn't even do `<name> for iOS`. I just wanted to see if there can be an option to change from `Pass` to something else... In my case, it would be `Pass for iOS` to help drive it home.

**Comment by mssun** [comment]
Thanks for your suggestion. Historically, I want to use "Pass for iOS" as the app name. However, App Store rejected my submission saying that the app name with "iOS" was not allowed. I'm afraid this may be not allowed also.

Also, in terms of changing the name to something else by user, I'm not sure we can do this. This should be a static variable defined in the resource file.
