### ISSUE TITLE
Git Repo Clone Error

### ISSUE THREAD

**Issue by citizencloud** [mssun/passforios#581]
Hi

I am unable to get past this one issue - when attempting to clone my secret repo , the PASS app always throws me an error saying : 

"Failed to clone repo from git@github.com:citizencloud/secretbox.git to file:////...... Underlying error: username does not match previous request"

I'm using SSH and I'm not sure what the problem is.

**Comment by SimplyDanny** [comment]
Make sure to use the URL `ssh://git@github.com/citizencloud/secretbox.git` (note the `ssh://` prefix and the `/` after the domain. Also make sure to use the username `git`.

**Comment by citizencloud** [comment]
awesome - that did the trick. was confused about the `username`, but definitely didn't do the url format right. thanks
