### ISSUE TITLE
Bug: Can't use Pass for iOS when using Gitlab's MFA

### ISSUE THREAD

**Issue by thomasmerz** [mssun/passforios#585]
I'm using current/latest version of "Pass for iOS" since a long time. My secrets are stored on Gitlab. Today I enabled MFA on my Gitlab account and since then I'm getting this error when pulling/pushing:

![image](https://user-images.githubusercontent.com/18568381/200962790-d6859f2a-baf4-4811-95c3-c488f7f9e99d.png)

Please advice how to fix this in the iOS app or fix this bug in the app. Thanks a lot!

**Comment by apfohl** [comment]
I assume you are using HTTPS for connecting to GitLab. In order to use MFA and HTTPS you need to setup a personal access token in GitLab: https://gitlab.com/-/profile/personal_access_tokens

You then use this as the pass word.

**Comment by thomasmerz** [comment]
Thanks for the tipp 👍🏼  
Could you please also add this valuable and detailled information in https://github.com/mssun/passforios/wiki#quick-start-guide-for-pass-for-ios

**Comment by apfohl** [comment]
@thomasmerz I'm just another user. It would be any easy contribution for you to the project.

**Comment by apfohl** [comment]
Maybe @mssun can add it? Not sure though.
