### ISSUE TITLE
Unable to clone repo

### ISSUE THREAD

**Issue by mburakov** [mssun/passforios#601]
I am just trying to switch from keepass, and this is my first attempt to use passforios (and pass in general).
I've set up a git repo using pass commandline, and verified that it works by making a push.

As the next step I tried to set up passforios.
I imported a private ssh key, and configured a path to git repo.
However trying to clone it raises an error popup:

![error_popup](https://user-images.githubusercontent.com/5390386/216831085-f8edcdc9-72c8-48e5-800a-1c2c9324bebf.png)

I am not quite sure how to proceed, am I missing some additional configuration, or is it a bug?

**Comment by mburakov** [comment]
I still have the exact same error on the latest version (0.14.0). What additional information can I provide for the analysis?

**Comment by hwiorn** [comment]
Try "Ed25519" key instead of "RSA" key. Recently, I got this ssh key issue on pass-for-ios only.
Change "master" to "main" if your repo has the "main" branch.

**Comment by mburakov** [comment]
Thanks @hwiorn, just tried this, and it works like a charm!
