### ISSUE TITLE
0.13.0 release crashes on startup on iPad

### ISSUE THREAD

**Issue by ismail** [mssun/passforios#609]
I got a crash dump while running it on iPad, but I also see the crash on startup on macOS. The password fill plug-in does work though. Crash dump attached.
[crash.txt](https://github.com/mssun/passforios/files/10949366/crash.txt)

**Comment by JerryWho** [comment]
Same issue here. I can’t access my passwords on my iPad. Latest version of iPad OS.

**Comment by mssun** [comment]
https://github.com/mssun/passforios/commit/cdaf60da73d148eb37c81ce1efd257c237c74acd should fix this issue. Will publish a new release in the TestFlight channel. Please let me know if this has been fixed. Thanks!

**Comment by ismail** [comment]
TestFlight version works fine, thanks a lot!

**Comment by avioli** [comment]
Same issue here as well.

**Comment by ismail** [comment]
@mssun Could you do a new stable release if possible? Thanks!
