### ISSUE TITLE
[Bug] Yubikey: Failed to get Encrypted MPI.

### ISSUE THREAD

**Issue by lzc256** [mssun/passforios#625]
Device: iPhone se 2, yubikey 5 nfc

After entering pin and touching Yubikey, the app prompts “Failed to get encrypted MPI.”

![8D774A39-65F7-4494-948B-0C87168EA84B](https://github.com/mssun/passforios/assets/36326574/f262b99b-6fc2-40e8-9124-329605392090)

Anyone has a solution? Thanks a lot.

**Comment by dermichal** [comment]
Same issue here. 
Was able to get pubkey from yubikey. Generating passwords works.

Devices: iPhone X, yubikey 5 nfc

**Comment by luk0y** [comment]
Same issue on 17.5. Has anyone fixed this?

**Comment by okukharchuk** [comment]
It looks like passforios does not support ascii-armored passwords with Yubikey. As a workaround you can reencrypt passwords without armoring them. On Linux machine could be done using (MAKE SURE YOU HAVE BACKUP BEFORE DOING THIS!):

`gpg -d <pass-to-password-file.gpg> | gpg -q --yes -e -r <user_id> -o <pass-to-password-file.gpg>`

Also added pull request with fix.

**Comment by mischavandenburg** [comment]
> It looks like passforios does not support ascii-armored passwords with Yubikey. As a workaround you can reencrypt passwords without armoring them. On Linux machine could be done using (MAKE SURE YOU HAVE BACKUP BEFORE DOING THIS!):
> 
> `gpg -d <pass-to-password-file.gpg> | gpg -q --yes -e -r <user_id> -o <pass-to-password-file.gpg>`
> 
> Also added pull request with fix.

Thank you for adding the PR. Unfortunately it hasn't been merged after several months :( 

I've set up my YubiKey using this guide https://github.com/drduh/YubiKey-Guide , but even when recrypting a password like you mentioned, I still get the MPI error.

**Comment by mssun** [comment]
> @mssun thanks for fixing this issue. Would it make sense to release a new version?

Yes, will do it.
