### ISSUE TITLE
Can't clone repository

### ISSUE THREAD

**Issue by webdev4u** [mssun/passforios#651]
When i try to clone repository, i get next error: "Failed to get HEAD (unborn) Underlying Error: reference 'refs/head/master' not found". But the branch name is main.
![IMG_F127881380E2-1](https://github.com/user-attachments/assets/5e2a0f31-2ad4-473f-8cff-6e5cacb468c2)

**Comment by mssun** [comment]
I cannot reproduce this issue. Can you kindly provide more details?

**Comment by webdev4u** [comment]
Sorry for late answer. The problem was in my git server. I found the solution. Thank you.
