### ISSUE TITLE
iOS App PASS cannot authenticate to GitHub Repository

### ISSUE THREAD

**Issue by Chuck-Serious** [mssun/passforios#657]
I tried the new way with Access Token because the username/password works no longer. GitHub has upgraded the security-level.
But PASS cannot work with the long URL these Token caues. Errors sounding like check username in url with username.
I managed the way with ssh and put my pubkey on GitHub and passed the private key on iPhone and into the App PASS. Now the problem is also in the format of the access url. The app has three variants but I can't get one up and running. It is hard to say if there is an error in the app or the app has only a check betwenn the provided data or there is a error from server (GitHub) as the following:
"remote credential provider returned an invalid cred type"
Some help appreciated.

**Comment by mssun** [comment]
Are trying to use personal access token in GitHub? You can fill in the URL in this way:

Git Repository URL: `https://${token}@github.com/${owner}/${repo}.git`
Branch Name: xxx
Username: ${token}
Password: Keep it empty

**Comment by Chuck-Serious** [comment]
Thank you so much: This did the job. I'm very happy.
________________________________
Von: Mingshen Sun ***@***.***>
Gesendet: Sonntag, 1. Dezember 2024 18:24
An: mssun/passforios ***@***.***>
Cc: Chuck Serious ***@***.***>; Author ***@***.***>
Betreff: Re: [mssun/passforios] iOS App PASS cannot authenticate to GitHub Repository (Issue #657)


Are trying to use personal access token in GitHub? You can fill in the URL in this way:

Git Repository URL: ***@***.***/${owner}/${repo}.git
Branch Name: xxx
Username: ${token}
Password: Keep it empty

**Comment by Chuck-Serious** [comment]
Please add this to the wiki, thanks:

Using personal access token in GitHub: You can fill in the URL in this way:

Git Repository URL: https://${token}@github.com/${owner}/${repo}.git
Branch Name: e.g. Master or Main ...
Username: ${token}
Password: Keep it empty
