### ISSUE TITLE
App crashes after entering YubiKey pin

### ISSUE THREAD

**Issue by NoahLutz** [mssun/passforios#661]
#### Issue
App crashes after entering YubiKey pin when trying to decode password. This started happening after updating to the most recent version. 

#### Steps to reproduce the issue

    Open Pass for iOS
    Attempt to decode any password
    Enter YubiKey pin number in the "YubiKey PIN" pop-up prompt
    Tap "OK"

#### Pass for iOS verision
0.15.0 (4)

#### iOS version
18.1.1 (22B91)

#### Device
iPhone 15 Pro

**Comment by jvillasante** [comment]
Same here, also on the BETA testing it crashes!
