### ISSUE TITLE
Crash after entering PIN for Yubikey

### ISSUE THREAD

**Issue by anerisgreat** [mssun/passforios#664]
Password is selected, needs yucky to decrypt.

User is prompted for PIN

After prompt and before scanning Yubikey, app crashes.

**Comment by mssun** [comment]
Which version are you using?

**Comment by anerisgreat** [comment]
Hello thank you for your reply0.15.0(4), double checked.Sent from my iPhoneOn 20 Dec 2024, at 7:10, Mingshen Sun ***@***.***> wrote:﻿
Which version are you using?

**Comment by mssun** [comment]
Can you try the latest Beta 0.16.0 (2)?

You install the beta versions through [TestFlight](https://testflight.apple.com/join/whK4zUFG).

**Comment by anerisgreat** [comment]
Absolutely, will test soon! Thank you!On 21 Dec 2024, at 6:22, Mingshen Sun ***@***.***> wrote:﻿
Can you try the latest Beta 0.16.0 (2)?
You install the beta versions through TestFlight.

**Comment by anerisgreat** [comment]
No issue on 0.16.0 (4). Works fine!On 21 Dec 2024, at 9:52, ***@***.*** wrote:﻿Absolutely, will test soon! Thank you!On 21 Dec 2024, at 6:22, Mingshen Sun ***@***.***> wrote:﻿
Can you try the latest Beta 0.16.0 (2)?
You install the beta versions through TestFlight.

**Comment by mssun** [comment]
Thanks for the confirmation. I have submitted the current beta for a new App Store release.
