### ISSUE TITLE
consolidate dependency managers

### ISSUE THREAD

**Issue by samdmarshall** [mssun/passforios#68]
Hi, could you please consider consolidating the number of dependency managers used for this project? Switching to only using CocoaPods or Carthage would be much preferred over using them both together. If build-time is an issue here, you could consider using [this](https://github.com/CocoaPods/Rome) plugin to CocoaPods to help make this work a bit more like Carthage.

**Comment by mssun** [comment]
Very good suggestion. The only thing troubles me is that ObjectivePGP doesn't support Carthage. If possible, could you help ObjectivePGP to compile a framework for Carthage release? https://github.com/krzyzanowskim/ObjectivePGP/issues/47

**Comment by samdmarshall** [comment]
As mentioned, the project could be switched to use cocoapods plugin "rome" instead of carthage, especially as that requires no additional work by third parties to make this change.

**Comment by mssun** [comment]
I tried cocoapods-rome, but got an error:

```
Downloading dependencies
Installing ObjectivePGP (0.5)
Installing OpenSSL-Universal (1.0.1.20)
[!] The 'Pods-pass' target has transitive dependencies that include static binaries: (/.../Code/passforios/Pods/OpenSSL-Universal/lib-ios/libcrypto.a and /.../Code/passforios/Pods/OpenSSL-Universal/lib-ios/libssl.a)
```

My pod file is

```
platform :ios, '10.3'
plugin 'cocoapods-rome'

target 'pass' do
  pod 'ObjectivePGP'
end
```

Do you know how to workaround this?

**Comment by samdmarshall** [comment]
Not that I'm aware of, I believe you will have this problem regardless of dependency management solution. The correct thing to do here is to get ObjectivePGP to not rely on OpenSSL on iOS (instead use the Security and CommonCrypto frameworks that Apple provides).

**Comment by yishilin14** [comment]
I am closing this issue now because it seems like impossible for now (and "not gonna happen" in https://github.com/krzyzanowskim/ObjectivePGP/issues/47). 

Feel free to re-opon if this becomes possible. :-)
