### ISSUE TITLE
Folder bug?

### ISSUE THREAD

**Issue by terpmeister** [mssun/passforios#72]
When I try to create a new entry like: `test/joe@xyz.com` I always get back the error: `Cannot Add Password. Illegal character.`.  Does passforios support creating folders?  Also I tried to create a new entry in an existing folder, same error.

**Comment by mssun** [comment]
Sorry. Creating folder or creating entry inside folder are not supported. I'm working on it.

**Comment by mssun** [comment]
Support folder operations  in commit: d8ecd1e889bf5b3b268403d65254b13f0ff83b9e

**Comment by mssun** [comment]
Folder operation functions are merged into master branch. A new version is also released via TestFlight. I'm closing this issue. Feel free to open a new if you meet related issues. Thanks.

- You can create an entry. E.g., `dir/password`.
- You can change folder name. E.g., `dir1/password` to `dir2/password`
- You can also delete folders. E.g., `dir1/dir2/password` to `dir1/password`

**Comment by terpmeister** [comment]
Thanks, so far everything is working good!  Thanks for adding the functionality.
