### ISSUE TITLE
Syncing not working correctly when moving under a folder

### ISSUE THREAD

**Issue by terpmeister** [mssun/passforios#73]
Been doing some testing, changed some passwords on my local workstation by moving some of them under a folder. Committed to gitlab (using ssh keys).  Did a resync on my iPhone, no changes.  When I look under `Settings -> General -> About Repositry -> Commit Logs` I can see the app knows about my changes (I see all my check ins), but nothing is changed in the app.  Have exited/entered the app multiple times to see if it would refresh, it does not.

So I created a new password (not under my test folder) and committed.  Now when the app resyncs it shows my new password and the ones I moved under the folder.

Using version 0.2.4 (4)
iPhone: 6s Plus
iOS version: 10.3.1

**Comment by mssun** [comment]
Fixed in commit: 1b68c6f

Please test, thanks.

**Comment by mssun** [comment]
Merged in to master and released in the TestFlight. I'm closing this issue. Feel free to reopen it if you meet the issue again.
