### ISSUE TITLE
Passforios no longer requiring PGP passphrase

### ISSUE THREAD

**Issue by raxod502** [mssun/passforios#74]
I have "Remember Passphrase" disabled in the settings. However, after I applied d8ecd1e889bf5b3b268403d65254b13f0ff83b9e to my local build (I bisected), passforios no longer prompts me for my PGP passphrase when decrypting a password. Alarmingly, it just decrypts it straight away! passforios is not secretly caching my passphrase, is it?

**Comment by mssun** [comment]
Should be a bug of passphrase logic. Please stay on the stable branch.

**Comment by raxod502** [comment]
Will do. Thanks.

**Comment by mssun** [comment]
Thanks for the report. Fixed in d6c7b67fcc313642e0115193e41a2f0fb2fbce24

**Comment by raxod502** [comment]
Thanks. However, the old passphrase is still cached in the keychain. How can I delete it? I tried uninstalling and reinstalling the app, but this did not seem to do it.

**Comment by mssun** [comment]
@raxod502 You can go to Settings and switch on then off the "Remember Passphrase" option.

**Comment by raxod502** [comment]
It works perfectly, thanks. Perhaps the passphrase should be deleted when the user tries to access a password, if they have "Remember Passphrase" turned off. As it is, if the passphrase somehow gets saved to the keychain while "Remember Passphrase" is off, the effect of "Remember Passphrase" is nullified until it is turned on and off again.
