### ISSUE TITLE
Cannot clone GitLab repostiory

### ISSUE THREAD

**Issue by tuphamnguyen** [mssun/passforios#75]
I'm using the version from TestFlight.
Getting the error "Failure to clone repository from ssh://gitlab.com:22/*******/*****.git to file ......

**Comment by mssun** [comment]
### SSH URL example
- Git repository URL: `ssh://git@gitlab.com/passforios-demo/demo.git` (original is `git@gitlab.com:passforios-demo/demo.git`)
  - remember to include username in the url
  - remember to change ":" to "/"
- Username: `git`
- Supported authentication Method: SSH Keys, Password (only for self-built Git server, but note that GitHub, GitLab, etc. don't support password authentication.)

Please refer to: wiki page

**Comment by tuphamnguyen** [comment]
My mistake, I didn't notice the username must also be included in the URL. Thank you for your help.

**Comment by yishilin14** [comment]
Adding the link to wiki page to the "repo setting" tab seems necessary. Just my two cents.
