### ISSUE TITLE
Passphrase always remembered

### ISSUE THREAD

**Issue by magullo** [mssun/passforios#76]
Hi, I just upgraded to version 21 and the app doesn't ask the gnupg passphrase anymore, even if the option is OFF.

**Comment by yishilin14** [comment]
Hi. I just switched off the "Remember Passphrase" option, and the app started to ask for the passphrase. By switching off that option, the app shall remove the remembered passphrase. 

Would you please turn that option on, then turn it off, and see what happens?

**Comment by yishilin14** [comment]
BTW, I found out that the "long-press to decrypt" feature does not work without remembering the gpg passphrase. Will fix that soon.

**Comment by magullo** [comment]
I can confirm that switching ON and OFF it works again.
Thank you very much!

**Comment by yishilin14** [comment]
We recently polished the related codes and changed the logic. I guess that's the reason behind.
