### ISSUE TITLE
Crashes on launch, can't find crash logs

### ISSUE THREAD

**Issue by raxod502** [mssun/passforios#78]
When I run passforios from Xcode on my iPhone, it works fine. It continues to work for a while after that. Unfortunately, a while later, it inevitably stops working, and instead crashes instantly on launch (until I run it again from Xcode). I can't find any crash logs in `~/Library/Logs/CrashReporter/MobileDevice`—is there any way I can debug this problem?

**Comment by mssun** [comment]
Are you using master or develop branch?

Actually, if you are using TestFlight. The crash log will be sent to me. But I don't know how to find log locally. It should be stored in a file on the device.

**Comment by raxod502** [comment]
@mssun I'm on develop now, but I believe this was also a problem back when I was on master. I can double-check if you'd like. I'm not using TestFlight currently, but would be happy to if it helps debugging. My email address is radon.neon@gmail.com.

**Comment by mssun** [comment]
Done. I will leave this issue open for now.

**Comment by raxod502** [comment]
I've switched to the TestFlight version, and will update this issue if I encounter the crash again. (Based on prior experience, this will probably happen after a few days if the issue remains.)

**Comment by mssun** [comment]
Sure, thanks. We aim for an enough stable version right now for the first App Store release.

**Comment by raxod502** [comment]
I have not experienced any crashes since. This leads me to believe that something about my manual installation of the app was incorrect. I'll close this issue for now, unless you'd like to keep it open.
