### ISSUE TITLE
App crashes when trying to open Settings > Password Repository

### ISSUE THREAD

**Issue by akiroz** [mssun/passforios#79]
Disclaimer: I know nothing about iOS development / Swift so I'll try to provide as much info as possible...

iOS version: 10.3
XCode version: 8.3.2

What I did:

- follow install steps on README
- create Apple provision profile using my Apple ID
- change bundle name from `me.mssun.passforios` to `akiroz.mssun.passforios` (error on something about unique string... ?_?)
- set destination to my iPhone
- build & run
- trust my certificate
- tap `Settings`
- tap `Password Repository`

What happened:

- On launch:
```
Error Domain=me.mssun.pass.error Code=1 "Cannot find remote branch origin/master."
```
This didn't crash the app so I ignored it
- When pressing Password Repository:
```
UserInfo={NSLocalizedDescription=Cannot find remote branch origin/master.}
fatal error: unexpectedly found nil while unwrapping an Optional value
```
at
```swift
class GitServerSettingTableViewController {
  func viewDidLoad() {
    // ...
    checkAuthenticationMethod(method: authenticationMethod!)
  }
}
```
so it seems like `authenticationMethod` was nil somehow?

**Comment by yishilin14** [comment]
Hi. We have fixed the bug of "authenticationMethod!" in the develop branch, please try the develop branch.

About the "unique string" error, it seems like you have successfully built the app, so I guess the error/warning went away when you built the app. (FYI. Here is what I usually do: Check "Automatically manage signing", change team to my personal team, change the bundle identifier to a different one. )

**Comment by akiroz** [comment]
Awesome, thanks!

=== OFF TOPIC ===
@yishilin14 
wow, apparently we study in the same place (I'm an undergrad student though)
nice dango = ]

**Comment by yishilin14** [comment]
I am closing this issues. Happy testing!

=== OFF TOPIC TOO ===
Wow. That's amazing.

**Comment by mssun** [comment]
Thanks all.

I think it’s time to merge develop into master branch. Will work on it later today.
