### ISSUE TITLE
[wiki] don't transfer GPG keys over the internet

### ISSUE THREAD

**Issue by akiroz** [mssun/passforios#81]
I think it would be safer to transfer GPG keys on a local network in the guide:
```
$ gpg --output akiroz.gpg --export <Key ID>
$ gpg --output akiroz.asc --export-secret-keys <Key ID>
$ python3 -m http.server
```
![photo6111500877958326200](https://cloud.githubusercontent.com/assets/8231917/26059244/a4393148-39b3-11e7-8ad8-900e6508a984.jpg)

**Comment by mssun** [comment]
This is a good suggestion. However, the local network may still not safe.

I think it's better to *alert* users that downloading keys via url is dangerous whether it is in the local network or internet.

**Comment by akiroz** [comment]
Yep, I actually created a new temporary network with a spare router to transfer my keys :P

**Comment by mssun** [comment]
You should later try our developing new feature to import keys by a gif picture. It's really fast.

**Comment by akiroz** [comment]
Wow, how does that work?

**Comment by mssun** [comment]
We can convert keys to several QR codes (since there is a limitation of the content size) and then animate them to a gif. By scanning the animated gif, we can quickly get the key information.

**Comment by akiroz** [comment]
Sounds awesome! Is this going to become a generic tool to transfer sensitive data? Transferring keys and certs between devices has always been a pain for me...

**Comment by mssun** [comment]
Absolutely, especially for small size of data, e.g., key sharing, password sharing. Let us see then.

**Comment by yishilin14** [comment]
The master branch now supports adding PGP keys by scanning armored keys embedded in QR codes. We will also support adding SSH keys in the same way soon.

As mentioned by @mssun, the local network may still not safe. We do hope that adding keys by scanning QR codes is both convenient and safe. I am closing this discussion for now, stay tuned for our updates.
