### ISSUE TITLE
Document using iTunes File Sharing for SSH keys

### ISSUE THREAD

**Issue by raxod502** [mssun/passforios#82]
From looking at the commit history, it seems like you can use iTunes to upload not only PGP keys but also SSH keys. Is this the case? If so, it should probably be documented.

**Comment by mssun** [comment]
This part needs to be polished. I'm not sure if SSH keys are supported by uploading via iTunes.

**Comment by yishilin14** [comment]
Uploading SSH keys via iTunes has been supported. I just updated the WiKi page. 

Starting from a31f5b797d2533137b2df6265846cb4c8501ea08 (currently in the develop branch), it is not necessary to import the public ssh key. We will merge it into the master branch soon, so I intentionally ignore the public key filename in the document.
