### ISSUE TITLE
Search should match on directory/pass

### ISSUE THREAD

**Issue by nnutter** [mssun/passforios#83]
The request here is different from #59.  Given a password store with contents, 

```
/
    Dir_A/
        File_A
    File_B
```

I would want to search for "Dir_A" and still see "File_A" as a match.

**Comment by yishilin14** [comment]
If you switch on "General -> Show Folder" and search for "Dir_A", you will be able to see "File_A" as a match. Otherwise, we do not support this kind of search now. 

But your suggestion sounds reasonable, we will work it. Thanks.
