### ISSUE TITLE
Support pass phrases

### ISSUE THREAD

**Issue by asymmetric** [mssun/passforios#85]
It would be great if this app could generate passphrases, like [correct horse battery staple](https://xkcd.com/936/).

1Password does this already, allowing the user to choose the separator too.

Of course you would need a dictionary for this.

**Comment by yishilin14** [comment]
Sounds interesting. I do need some passwords like this.

**Comment by yishilin14** [comment]
It has been a while, not sure whether you are still using the app.

I have been generating memorable passwords in https://xkpasswd.net/ for a while. Just added a link to in the password editor to the website (421b5ae). Users have to copy the generated password from the website and paste it in the app. Anyway, I think it's better than nothing.

Will be release in the next version.

![wechatimg184](https://user-images.githubusercontent.com/7790907/44804975-916d5980-abf5-11e8-806b-da5ab61b3520.jpeg)

**Comment by asymmetric** [comment]
I've been using [diceware](https://github.com/ulif/diceware) on Linux, not sure how easy it would be to use this on iOS.

**Comment by yishilin14** [comment]
@asymmetric Thank you for your reference. Seems like it is not too hard to implement one. Maybe we will implement one in the future. XD

**Comment by yishilin14** [comment]
Status:
- 421b5ae: Add a link to [https://xkpasswd.net/](https://xkpasswd.net/); In Testflight v0.5.1(8) 
- 826357c: Open xkpasswd using an "internal" Safari view, improve user experience

**Comment by mssun** [comment]
A new version (0.5.1) has been published in App Store to address this issue.

I'm closing this issue. Free feel to reopen it or create a separate new issue if you think it can be further improved.
