### ISSUE TITLE
Hide TouchID option on devices that don't support it

### ISSUE THREAD

**Issue by asymmetric** [mssun/passforios#87]
Running the app on an iPod Touch 6th gen., that doesn't support TouchID.

The option should be hidden IMHO, since it has basically no effect.

**Comment by mssun** [comment]
Support in commit: 3921b89a120fefbc6dcbead3361a7185fdc6f46b

**Comment by mssun** [comment]
I'm closing issue. It will be released in TestFlight and merged into master branch soon.
