### ISSUE TITLE
Unable to pull git changes

### ISSUE THREAD

**Issue by angus-g** [mssun/passforios#90]
I'm using a self-hosted git server (SSH key authentication), from which I'm able to clone my password store without problems -- everything works as expected here. However, when I attempt to pull changes from the remote repository (without having made local changes), I get "Error: Failed to fetch from remote".

Perhaps related: in "About Repository", there are apparently 0 commits (there should be 110), and "Commit Logs" gives "Error: The operation couldn't be completed. (Foundation._GenericObjCError error 0.)"

**Comment by mssun** [comment]
Thanks for the report. I will try to reproduce this issue first and give you a feedback.

**Comment by mssun** [comment]
Thanks for waiting. I can reproduce your issue. I am working on it.

**Comment by mssun** [comment]
The fix was in the latest TestFlight. Please try. Thanks.

**Comment by angus-g** [comment]
Thanks! I can confirm that it's working for me (both pulling changes and viewing commit info for the repository).
