### ISSUE TITLE
App Store Submission Timeline

### ISSUE THREAD

**Issue by mssun** [mssun/passforios#91]
For you guys who want to know the current status of App Store submission, here are several attempts. Feel free to give suggestions.

**Comment by mssun** [comment]
> Jun 4, 2017 at 4:48 PM
> 
> From Apple
> 4. 2 Design: Minimum Functionality
> Guideline 4.2.1 - Design - Minimum Functionality
> 
> 
> Your app has the UIFileSharingEnabled key set to true in the Info.plist, but we were unable to verify the functionality of the file sharing feature.
> 
> Next Steps
> 
> If your app does not require the file sharing feature, please set the UIFileSharingEnabled key in the Info.plist to false.
>
> 0.2.6 Binary Rejected Jun 4, 2017

I explained our usage for UIFileSharingEnabled key in iTunes sharing and resubmitted.

**Comment by mssun** [comment]
> Jun 6, 2017 at 9:21 AM
> From Apple
> 5. 2.5 Legal: Intellectual Property - Apple Products
> 0. 10.0 Before You Submit: Program License Agreement
> Hello,
> 
> Thank you for your resubmission. Upon further review, we found the following:
> 
> Guideline 5.2.5 - Legal - Intellectual Property
> 
> 
> Your app does not comply with the Guidelines for Using Apple's Trademarks and Copyrights. Specifically, your app includes:
> 
> - Apple trademark, Apple logo, imagery - or likeness - in the app preview and app screenshots.
> 
> Please see attached screenshots for details.
> 
> Next Steps
> 
> To resolve this issue, please revise your app and its metadata to address these trademark issues.
> 
> For your convenience, we've provided the relevant sections of the Guidelines for Using Apple's Trademarks and Copyrights:
> 
> Apple Logo and Apple-owned Graphic Symbols
> 
> You may not use the Apple Logo or any other Apple-owned graphic symbol, logo, or icon on or in connection with web sites, products, packaging, manuals, promotional/advertising materials, or for any other purpose except pursuant to an express written trademark license from Apple, such as a reseller agreement.
> 
> PLA 2.3
> 
> 
> Additionally, we found that your app description states:
> 
> - Encrypt and decrypt password entries by PGP keys
> 
> However, your app does not have Export Compliance, which does not comply with the Apple Developer Program License Agreement, as required by the App Store Review Guidelines.
> 
> Section 2.3 of the Apple Developer Program License Agreement specifies,
> 
> "You certify that (i) none of the Licensed Applications contains, uses or supports any data encryption or cryptographic functions; or (ii) in the event that any Licensed Application contains, uses or supports any such data encryption or cryptographic functionality, You will, upon request, provide Apple with a PDF copy of Your Encryption Registration Number (ERN), or export classification ruling (CCATS) issued by the United States Commerce Department, Bureau of Industry and Security and PDF copies of appropriate authorizations from other countries that mandate import authorizations for that Licensed Application, as required."
> 
> Please review your app's encryption ability, and when resubmitting your binary, check the appropriate answers to the questions in the Export Compliance section of iTunes Connect. You may be asked some follow-up questions to determine the level of encryption in your app; you may also be asked to provide a copy of your CCATS.
> 
> If you have questions related to export compliance and your app's use of encryption, please contact the App Store Export Compliance team at appstore.ec@apple.com.
> 
> We look forward to reviewing your resubmission.
> 
> Best regards,
> 
> App Store Review

> 0.2.6 Binary Rejected Jun 6, 2017

I removed Apple logo in the app preview and app screenshots, and explained the "Export Compliance" of Pass in the note and resubmitted.

**Comment by hallabro** [comment]
Thanks for keeping us updated. Love your work! 👍

**Comment by mssun** [comment]
![img_0922](https://user-images.githubusercontent.com/1270392/26900019-c48efc00-4b85-11e7-8084-3c75748a8b7c.png)

**Comment by mssun** [comment]
https://itunes.apple.com/us/app/pass-password-store/id1205820573?ls=1&mt=8

**Comment by steffen9000** [comment]
You should absolutely make it a paid app, or at least allow us to donate through PayPal etc. This app  improves my iOS device usage greatly and I'd love to send some money your way. :)

**Comment by geoffmacintosh** [comment]
Agreed. An in-app tip purchase would be super convenient if you don't want to make the app paid. I think those are allowed?

**Comment by rnkn** [comment]
I would gladly pay for this app. I've already downloaded from the App Store so I can't repurchase, but would like to donate via PayPal.

**Comment by mssun** [comment]
Thanks for your huge supports. After discussing with my collaborator @yishilin14, we decided to make the app **free**. Since we all get a lot of benefits from free software / open source software, this could be the best way to contribute to the community.

I also added a PayPal donation button [![Donate](https://img.shields.io/badge/Paypal-donate-blue.svg)](https://www.paypal.me/mssun) on the homepage. If you guys want to buy us a cup of coffee, we are very glad to accept your offers. I guess this may also push us to continue improving the functionalities and make Pass the best/secure password management app.

In addition to the donation, I am more than happy to see bug reports, features suggestions and pull requests from you guys. Without your supports, Pass for iOS cannot become such a useful app. Huge thanks for you.

**Comment by jrick** [comment]
You two are a class act.  Keep up the great work!

**Comment by davidjb** [comment]
Donated accordingly!  As others have said, you're fantastic for making this app and for making it open source.  So a huge thank you @mssun and @yishilin14. 

I never quite got there with https://github.com/davidjb/pass-ios so I'm super-excited to see where this gets to.  Looking super-promising.  It goes without saying if any of that old code helps, you're welcome to it.

**Comment by mssun** [comment]
Guys, 0.3.0 is online. Thanks for your support.
