### ISSUE TITLE
Crash without repository

### ISSUE THREAD

**Issue by rnkn** [mssun/passforios#92]
Navigating to Settings > General > About Repository will reliably crash the app if a repository is not set.

**Comment by yishilin14** [comment]
Fixed in 174128998c89e10ede395d46c65e117503d3e08d (dev branch). 

We have submitted the updated app for the TestfFlight beta review. Will keep you posted. :-)

**Comment by yishilin14** [comment]
Fixed in v0.2.6(34) in App Store and v0.2.7(1) in TestFlight.
