### ISSUE TITLE
Use the Pass extension to fill in Browsers and apps

### ISSUE THREAD

**Issue by yishilin14** [mssun/passforios#98]
We are now working on an "app extension" of Pass with the ultimate goal of "using the Pass extension to fill in Safari and apps" (just like [1Password](https://support.1password.com/1password-extension-ios/) and LastPass)! We would like to share with you the status here so that you will know what's going to happen soon (and what's not).

**High level features**
- In Safari/Chrome, visit the website where you want to use Pass. Tap the Share icon, then tap Pass, find and copy your password.
- In "supported" apps, tap the 1Password icon, open Pass, and fill (see [URL scheme proposed by 1Password](https://blog.agilebits.com/2014/08/04/filling-with-your-approval-on-1passwords-app-extension-and-ios-8-security/)).

**Done**
- Autofill of apps that use 1password-extension (Jun 23, 2017: 5710f496fceee8e34ee5255c509fcd0525670ffd in develop)
- Autofill Safari/Chrome  (Jun 25, 2016: 5d71f99 in develop)

**Todo-list**
- Create a new entry from the extension
- Generate a new password from the extension

**Features with lower priorities for now**
- Autofill addresses/credit cards...

If you have general suggestions, please leave them here. If you want to report bugs, or you have suggestions about a specific feature, please file a new issue. :-)

**Comment by yishilin14** [comment]
Pass extension now fills usernames and passwords in Chrome and Safari (commit: 5d71f997119ce9e33ec454ab24368f990873b5f3).

- **Safari**: A javascript file `passforios/passExtension/passProcessor.js` is used to fill usernames and passwords. It may not be very robust now (I am new to this), if you have any suggestions please let us know. Pull requests are always welcome!

- **Chrome**: If you find some websites that Pass cannot fill, it is very likely that other password managers cannot fill them too. We are all simply returning a "username/password" dictionary to Chrome and let the Chrome fill the page. (Reference: https://bugs.chromium.org/p/chromium/issues/detail?id=405894)

Also, since auto filling is supported now, copying passwords directly from the extension is no longer supported, for security concerns. The app extension cannot clear the clipboard after a certain period of time. It seems like LastPass does not support copying passwords directly from the extension too, not sure whether it is because of the same concern.

**Comment by craigcabrey** [comment]
I tried this out on a financial site (would rather not specify publicly) and it didn't fill in the username, only the password field. The password it did paste in was far too long and even after entering my username manually, it was the incorrect password.

I think it might've paste in the entire contents of the pgp file in the password field but it's hard to tell. All of my password entries are formatted as:

```
{password}
login: {username}
```

Great to see this functionality though!

**Comment by yishilin14** [comment]
@craigcabrey 

For the username field, we are only looking for "username: xxxx" or "Username: xxxx". I think I will add "login" as an additional key. Meanwhile, would you please try to modify "login" to "username" temporary to see whether the username filed could be filled? (You could go to Settings->Advanced->Discard all local changes to cancel the change.)

For the password field, I am not sure why. Are you using Safari? If so, it is either because of some special settings of the financial site, or the Javascript file we use is not robust enough. If you are using Chrome, there is nothing we can do, Chrome handles the filling by itself.

**Comment by craigcabrey** [comment]
Makes sense. I was using `login:` since that is what browserpass looks for. Just tried it out and changing to `username:` solves that issue.

Password field is still incorrect though. If Safari (I am using Safari, not Chrome) has a remote debugger I might be able to see what's going on.

**Comment by yishilin14** [comment]
Just took a look at browserpass' readme. Now I think adding "login" is a must-do. (I am using browserpass too.)

I tried a banking site and the auto filling worked correctly there. If you don't mind, you could send us an email about the site or a similar site, we will give it a try.

**Comment by asymmetric** [comment]
> For the username field, we are only looking for "username: xxxx" or "Username: xxxx"

I think it would make sense to make this configurable, so that it's customizable and that it also acts as a form of documentation.

**Comment by mssun** [comment]
Can we close this issue? @yishilin14 

I don't think these features in the TODO list are technically possible in iOS:
  - Create a new entry from the extension
  - Generate a new password from the extension

We should ignore this one for many reasons:
  - Autofill addresses/credit cards...

@asymmetric, for your "configurable in the UI" suggestion, I think this may be a "over-engineering" idea. Current naming convention is just fine.

**Comment by yishilin14** [comment]
I think we can close this one for now.
For more advanced features, I don't think I have enough time to implement them any time soon.

**Comment by martinhoefling** [comment]
@yishilin14 and @mssun, concerning the detection of login fields: In my [gopass](https://github.com/justwatchcom/gopass) browser extension [gopassbridge](https://github.com/martinhoefling/gopassbridge), I wrote a [content script](https://github.com/martinhoefling/gopassbridge/blob/master/web-extension/content.js) for detecting username and password fields. It's almost fully covered by tests and handles several edge cases like decoy password fields etc.. If it is considered useful, we could make it applicable to both projects.
